class GWM_Clip : Clip replaces Clip
{
	Default
	{
		Inventory.PickupSound "pickups/clip";
	}
}
class GWM_ClipBox : ClipBox replaces ClipBox
{
	Default
	{
		Inventory.PickupSound "pickups/clipbox";
	}
}

class GWM_Shell : Ammo // had to basically define my own shells so the spawner would play nice.
{
	Default
	{
		Inventory.PickupSound "pickups/shells";
		Inventory.PickupMessage "$GOTSHELLS"; // Redefined in LANGUAGE -- "Picked up a small box of shotgun shells."
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "SHELA0";
	}
	States
	{
		Spawn:
			SHEL A -1;
			Stop;
	}
}
class GWM_ShellBox : GWM_Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLBOX"; // Redefined in LANGUAGE -- "Picked up a large box of shotgun shells."
		Inventory.Amount 20;
	}
	States
	{
		Spawn:
			SBOX A -1;
			Stop;
	}
}

class GWM_IceShell : Ammo
{
	Default
	{
		Inventory.PickupSound "pickups/shells";
		Inventory.PickupMessage "$GOTICESHELLS"; // "Picked up a small box of ice shotgun shells."
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "ISHLA0";
	}
	States
	{
		Spawn:
			ISHL A -1;
			Stop;
	}
}
class GWM_IceShellBox : GWM_IceShell
{
	Default
	{
		Inventory.PickupMessage "$GOTICESHELLBOX"; // "Picked up a large box of ice shotgun shells."
		Inventory.Amount 20;
	}
	States
	{
		Spawn:
			ISHL B -1;
			Stop;
	}
}

class GWM_RocketAmmo : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET"; // "Picked up a rocket."
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "ROCKA0";
	}
	States
	{
		Spawn:
			ROCK A -1;
			Stop;
	}
}
class GWM_RocketBox : GWM_RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKBOX"; // "Picked up a box of rockets."
		Inventory.Amount 5;
	}
	States
	{
		Spawn:
			BROK A -1;
			Stop;
	}
}

class GWM_VenomVial : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTVENOMVIAL";// "Picked up a small vial of venom."
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "VNMVC0";
	}
	States
	{
		Spawn:
			VNMV ABCDCB 6;
			Loop;
	}
}
class GWM_LargeVenomVial : GWM_VenomVial
{
	Default
	{
		Inventory.PickupMessage "$GOTLARGEVENOMVIAL"; // "Picked up a large vial of venom."
		Inventory.Amount 5;
	}
	States
	{
		Spawn:
			VNMV EFGHGF 6;
			Loop;
	}
}

class GWM_MineAmmo : Ammo
{
	Default
	{
		Inventory.PickupMessage "$DISARMEDMINE";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "MINEZ0";
	}
	States
	{
		Spawn:
			MINE Z -1;
			Stop;
	}
}

class GWM_CellPack : CellPack {} // solely exists to prevent an infinite loop

Class EverIce : Ammo replaces BlasterAmmo
{
	Default
	{
		Inventory.PickupMessage "EverIce Chunk";
		Inventory.Amount 25;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 25;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "EICEI0";
		Scale 0.4;
	}

	States
	{
		Spawn:
			EICE ABCD 6;
			Loop;
	}
}
Class EverIceHefty : EverIce replaces BlasterHefty
{
	Default
	{
		Inventory.PickupMessage "EverIce Cluster";
		Inventory.Amount 50;
		Scale 0.4;
	}

	States
	{
		Spawn:
			EICE EFGH 6;
			Loop;
	}
}