class PlayerSpawnLines : StaticEventHandler
{
    override void WorldLoaded(WorldEvent _event)
    {
        if (_event.IsSaveGame) return;
        
        let player = players[consoleplayer].mo;
        player.A_StartSound("player/battlecry", CHAN_VOICE);
    }
    
    override void PlayerRespawned(PlayerEvent _event)
    {
        let player = players[_event.playernumber].mo;
        player.A_StartSound("player/respawn", CHAN_VOICE);
    }
}

class MonsterReplacer : StaticEventHandler
{
    override void CheckReplacement(ReplaceEvent e)
    {
        CVar replaceMonsters = CVar.FindCVar('gwm_replacemonsters');
        if (replaceMonsters.GetBool())
        {
            if (e.Replacee == "WolfensteinSS")
            {
                e.Replacement = "GWM_WolfensteinSS";
            }
        }
    }
}