#include "./Monsters/Zombiemen.zsc"
#include "./Monsters/Shotgunners.zsc"
#include "./Monsters/Chaingunners.zsc"
#include "./Monsters/Imps.zsc"
#include "./Monsters/Pinkies.zsc"
#include "./Monsters/Hell Knights.zsc"
#include "./Monsters/Barons.zsc"
#include "./Monsters/Cacodemons.zsc"
#include "./Monsters/Lost Souls.zsc"
#include "./Monsters/Cyberdemons.zsc"
#include "./Monsters/Arachnotrons.zsc"
#include "./Monsters/Mancubi.zsc"
#include "./Monsters/Pain Elementals.zsc"
#include "./Monsters/Revenants.zsc"
#include "./Monsters/Spider Masterminds.zsc"
#include "./Monsters/Wolfenstein SS.zsc"

class GWM_EnemyRocket : Rocket
{
	Default
	{
		-ROCKETTRAIL // I have my own rocket trails, thanks.
		DamageFunction (90); // Derandomized damage
		DamageType "Rocket";
	}
	States
	{
		Spawn:
			MISL A 2 Bright A_SpawnItemEx("GWM_RocketTrail", -20);
			Loop;
		Death:
			TNT1 A 0 A_QuakeEx(3, 3, 3, 10, 0, 512, flags: QF_SHAKEONLY);
			Goto Super::Death;
	}
}

class GWM_EnemyPlasma : ArachnotronPlasma
{
	Default
	{
		DamageFunction (23);
		DamageType "Plasma";
	}
}