class GWM_ExplosiveBarrel : ExplosiveBarrel
{
	Default
	{
		Tag "Explosive Barrel";
		+PUSHABLE
		Friction 0.8;
		DeathSound "objects/barrel_explode";
	}
	States
	{
		Spawn:
			XBAR A -1;
			Stop;
		Death:
			XBAR B 10;
			TNT1 A 0 {
				A_Scream();
				A_Explode();
			}
			XBAR CDEFGHIJKL 2 Bright;
			TNT1 A 1050 Bright A_BarrelDestroy;
			TNT1 A 5 A_Respawn;
			Wait;
	}
}

class GWM_DeadBaronStick : DeadStick
{
	States
	{
		Spawn:
			POL1 B -1;
			Stop;
	}
}
class GWM_DeadBaronStickGreenBlood : DeadStick
{
	States
	{
		Spawn:
			POL1 C -1;
			Stop;
	}
}
class GWM_DeadHellKnightStick : DeadStick
{
	States
	{
		Spawn:
			POL1 D -1;
			Stop;
	}
}
