class GWM_ExplosiveBarrel : ExplosiveBarrel
{
	Default
	{
		Tag "Explosive Barrel";
		+PUSHABLE
		Friction 0.8;
		DamageFactor "Kick", 0.1;
		PainChance "Kick", 256;
		DeathSound "objects/barrel_explode";
	}
	States
	{
		Spawn:
			XBAR A -1;
			Stop;
		Pain.Kick:
			XBAR A 1 {
				bDontThrust = false;
				bMissile = true;
				bStepMissile = true;
			}
			BNOB A 0 A_FaceTarget;
			Goto Rolling;
		Rolling:
			XBAR B 1 A_ChangeVelocity(-20, 0, 0, CVF_RELATIVE|CVF_REPLACE);
			Loop;
		Death:
			XBAR BCD 1;
			//TNT1 A 0 {
				
				
			//}
			//XBAR CDEFGHIJKL 2 Bright;
			TNT1 A 0 
			{
				A_Scream();
				A_SpawnitemEX("GWM_BarrelBlast",0,0,5);
				A_Explode();
			}
			TNT1 A 1050 Bright A_BarrelDestroy;
			TNT1 A 5 A_Respawn;
			Wait;
	}
}

Class GWM_BarrelBlast : Actor
{
	Default
	{
		+NoInteraction
	}
	States
	{
		Spawn:
			TNT1 A 1 NoDelay A_SpawnItemEX("ShakeItBaby",0,0,5);
			TNT1 AAA 0 A_SpawnItemEX("GWMBlastDebris",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
			TNT1 AA 0 A_SpawnItemEX("GWMBlastDebris",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-20,20),frandom(-20,20),frandom(-20,20),frandom(1,359));
			TNT1 AAAAA 1
			{
				A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-6,6),frandom(-6,6),frandom(-6,6),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
				A_SpawnItemEX("GWMBlastDebris",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-3,3),frandom(-3,3),frandom(-3,3),frandom(1,359));
			}
			stop;
	}
}

Class ShakeitBaby : Actor
{
	States
	{
		Spawn:
			TNT1 A 5 Radius_Quake (7, 8, 0, 50, 0);
			TNT1 A 5 Radius_Quake (5, 8, 0, 50, 0);
			TNT1 A 5 Radius_Quake (3, 8, 0, 50, 0);
			stop;
	}
}

Class BlastFlameFX : Actor
{
	Default
	{
		Scale 0.75;
		RenderStyle "Add";
		+NoInteraction
		+ForceXYBillboard
	}

	States
	{
	Spawn:
		XFIR ACEGIKMOQ 1 bright;
		stop;
	}
}

Class BlastFlameFX2 : Actor
{
	Default
	{
		Scale 1.25;
		RenderStyle "Add";
		+NoInteraction
		+ForceXYBillboard
	}

	States
	{
	Spawn:
		ZFIR ABCDEGHIJKLMNOP 1 bright;
		stop;
	}
}

Class GWMBlastDebris : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Gravity 0.5;
		Projectile;
		-NoGravity;
		Bouncefactor 0.50;
		Bouncetype "Hexen";
		Scale 0.6;
		renderstyle "Add";
		Reactiontime 125;
	}
	States
	{
		Spawn:
			YFIR A 1 bright A_SpawnitemEX("BlastDebrisFire",frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(-.5,.5),frandom(-.5,.5),frandom(2,3));
			TNT1 A 0 A_Countdown;
			TNT1 AAA 0 A_Jump(150,"Spawn");
			TNT1 A 0 A_Countdown;
			loop;

		Death:
			ZFIR A 1 bright A_Setscale(0.5,0.5);
			YFIR AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_SpawnItemEX("BlastDebrisFire2",frandom(-5,5),frandom(-5,9),frandom(1,5),frandom(-.3,.3),frandom(-.3,.3),frandom(2,3));
			ZFIR A 1 bright A_Setscale(0.4,0.4);
			YFIR AAAAAAAAAAAAAAAAAAAAAAA 1 A_SpawnItemEX("BlastDebrisFire3",frandom(-3,3),frandom(-3,3),2,frandom(-.1,.1),frandom(-.1,.1),frandom(2,3));
			ZFIR A 1 bright A_Setscale(0.3,0.3);
			YFIR AAAAAAAAAAAAAA 1 A_SpawnItemEX("BlastDebrisFire4",frandom(-1,1),frandom(-1,1),1,0,0,frandom(2,3));
			ZFIR A 1 bright A_Setscale(0.2,0.2);
			YFIR AAAAAAAAAAAAAAAA 1 A_FadeOut(0.08);
			stop;
	}
}

Class BlastDebrisFire : Actor
{
	Default
	{
		Scale 0.25;
		RenderStyle "Add";
		+NoInteraction
		+ForceXYBillboard
		+Randomize
	}
	States
	{
		Spawn:
			ZFIR ABCDEFGHIJKLMNOP 1 bright A_ScaleVelocity(frandom(0.9,0.99));
			stop;
	}
}

Class BlastDebrisFire2 : BlastDebrisFire
{
	Default
	{
		Scale 0.17;
	}
	States
	{
		Spawn:
			ZFIR DEFGHIJKLMNOP 1 bright A_ScaleVelocity(frandom(0.9,0.99));
			stop;
	}
}

Class BlastDebrisFire3 : BlastDebrisFire
{
	Default
	{
		Scale 0.1;
	}
	States
	{
		Spawn:
			ZFIR GHIJKLMNOP 1 bright A_ScaleVelocity(frandom(0.9,0.99));
			stop;
	}
}

Class BlastDebrisFire4 : BlastDebrisFire
{
	Default
	{
		Scale 0.09;
	}
	States
	{
		Spawn:
			ZFIR JKLMNOP 1 bright A_ScaleVelocity(frandom(0.9,0.99));
			stop;
	}
}

class GWM_DeadBaronStick : DeadStick
{
	States
	{
		Spawn:
			POL1 B -1;
			Stop;
	}
}
class GWM_DeadBaronStickGreenBlood : DeadStick
{
	States
	{
		Spawn:
			POL1 C -1;
			Stop;
	}
}
class GWM_DeadHellKnightStick : DeadStick
{
	States
	{
		Spawn:
			POL1 D -1;
			Stop;
	}
}
class GWM_DeadChaingunGuyStick1 : DeadStick
{
	States
	{
		Spawn:
			POL1 E -1;
			Stop;
	}
}
class GWM_DeadChaingunGuyStick2 : DeadStick
{
	States
	{
		Spawn:
			POL1 F -1;
			Stop;
	}
}
class GWM_DeadCacodemonStick : DeadStick
{
	States
	{
		Spawn:
			POL1 G -1;
			Stop;
	}
}
class GWM_DeadPinkyStick : DeadStick
{
	States
	{
		Spawn:
			POL1 H -1;
			Stop;
	}
}