class GWM_HealthBonus : HealthBonus replaces HealthBonus
{
	Default
	{
		Inventory.MaxAmount 300;
		Inventory.PickupSound "pickups/healthbonus";
	}
}

class GWM_ArmorBonus : ArmorBonus replaces ArmorBonus
{
	Default
	{
		Armor.MaxSaveAmount 300;
		Inventory.PickupSound "pickups/armorbonus";
	}
}

class GWM_Soulsphere : Soulsphere replaces Soulsphere
{
	Default
	{
		Inventory.MaxAmount 300;
	}
}

class GWM_Backpack : Backpack replaces Backpack
{
	Default
	{
		Inventory.PickupSound "pickups/backpack";
	}
}

class GWM_Berserk : Berserk replaces Berserk
{
	override void Touch(Actor toucher) {
		toucher.A_StartSound("player/berserk", CHAN_VOICE);
		Super.Touch(toucher);
	}
	States
	{
		Pickup:
			TNT1 A 0 {
				A_GiveInventory("PowerStrength");
				HealThing(100, 0);
				A_SelectWeapon("GWM_Fist");
			}
			Stop;
	}
}