class GWM_WeaponSpawner : RandomSpawner
{
	override void BeginPlay()
	{
		Super.BeginPlay();
		if (random(0,3) == 3)
			Spawn("GWM_Mine", self.pos);
	}
}

class GWM_ClipSpawner : GWM_WeaponSpawner replaces Clip
{
	Default
	{
		DropItem "GWM_LowCaliberClip";
		DropItem "GWM_HighCaliberClip";
	}
}
class GWM_ClipBoxSpawner : GWM_WeaponSpawner replaces ClipBox
{
	Default
	{
		DropItem "GWM_LowCaliberBox";
		DropItem "GWM_HighCaliberBelt";
	}
}

class GWM_ShellSpawner : GWM_WeaponSpawner replaces Shell
{
	Default
	{
		DropItem "GWM_Shell";
		DropItem "GWM_IceShell";
	}
}
class GWM_ShellBoxSpawner : GWM_WeaponSpawner replaces ShellBox
{
	Default
	{
		DropItem "GWM_ShellBox";
		DropItem "GWM_IceShellBox";
	}
}

class GWM_RocketAmmoSpawner : GWM_WeaponSpawner replaces RocketAmmo
{
	Default
	{
		DropItem "GWM_RocketAmmo";
		DropItem "GWM_VenomVial";
	}
}
class GWM_RocketBoxSpawner : GWM_WeaponSpawner replaces RocketBox
{
	Default
	{
		DropItem "GWM_RocketBox";
		DropItem "GWM_LargeVenomVial";
	}
}

class GWM_CellSpawner : GWM_WeaponSpawner replaces Cell
{
	Default
	{
		DropItem "GWM_Cell";
		DropItem "GWM_NapalmAmmo";
	}
}

class GWM_CellPackSpawner : RandomSpawner replaces CellPack
{
	Default
	{
		DropItem "GWM_CellPack";
		DropItem "GWM_NapalmStack";
	}
}

class GWM_ChainsawSpawner : GWM_WeaponSpawner replaces Chainsaw
{
	Default
	{
		DropItem "GWM_Impactor";
		DropItem "GWM_Lumberjack";
	}
}

class GWM_ShotgunSpawner : GWM_WeaponSpawner replaces Shotgun
{
	Default
	{
		DropItem "GWM_Shotgun";
		DropItem "GWM_IceShotgun";
	}
}

class GWM_SuperShotgunSpawner : GWM_WeaponSpawner replaces SuperShotgun
{
	Default
	{
		DropItem "GWM_SuperShotgun";
		DropItem "GWM_PFSuperShotgun";
	}
}

class GWM_ChaingunSpawner : GWM_WeaponSpawner replaces Chaingun
{
	Default
	{
		DropItem "GWM_Chaingun";
		DropItem "GWM_BurstRifle";
	}
}

class GWM_RocketLauncherSpawner : GWM_WeaponSpawner replaces RocketLauncher
{
	Default
	{
		DropItem "GWM_RocketLauncher";
		DropItem "GWM_VenomCannon";
	}
}

class GWM_PlasmaRifleSpawner : GWM_WeaponSpawner replaces PlasmaRifle
{
	Default
	{
		DropItem "GWM_PlasmaRifle";
		DropItem "GWM_Melter";
		DropItem "GWM_NoiseCrusher";
	}
}

class GWM_BFG9000Spawner : GWM_WeaponSpawner replaces BFG9000
{
	Default
	{
		DropItem "GWM_BFG9000";
		DropItem "GWM_NapalmLauncher";
	}
}

class GWM_BlurSphereSpawner : RandomSpawner replaces BlurSphere
{
	Default
	{
		DropItem "GWM_BlurSphere", 255, 2;
		DropItem "GWM_DrainSphere", 255, 1;
		DropItem "GWM_Stopwatch", 255, 1;
	}
}

class GWM_InvulnerabilitySphereSpawner : RandomSpawner replaces InvulnerabilitySphere
{
	Default
	{
		DropItem "GWM_InvulnerabilitySphere";
		DropItem "GWM_ReflectSphere";
	}
}

class GWM_SoulsphereSpawner : RandomSpawner replaces Soulsphere
{
	Default
	{
		DropItem "GWM_Soulsphere";
		DropItem "GWM_PortableMedkit";
	}
}