class GWM_WeaponSpawner : Actor
{
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf((random(0, 2)%2), "Spawn_Mine");
			TNT1 A 0 {return ResolveState("Spawn2");}
		Spawn_Mine:
			TNT1 A 0 A_SpawnItemEx("GWM_Mine");
			TNT1 A 0 {return ResolveState("Spawn2");}
		Spawn2:
			Stop;
	}
}

class GWM_ShellSpawner : GWM_WeaponSpawner replaces Shell
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_Shell");
		Spawn_IceShell:
			TNT1 A 0 A_SpawnItemEx("GWM_IceShell");
			Stop;
		Spawn_Shell:
			TNT1 A 0 A_SpawnItemEx("GWM_Shell");
			Stop;
	}
}
class GWM_ShellBoxSpawner : GWM_WeaponSpawner replaces ShellBox
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_ShellBox");
		Spawn_IceShellBox:
			TNT1 A 0 A_SpawnItemEx("GWM_IceShellBox");
			Stop;
		Spawn_ShellBox:
			TNT1 A 0 A_SpawnItemEx("GWM_ShellBox");
			Stop;
	}
}

class GWM_RocketAmmoSpawner : GWM_WeaponSpawner replaces RocketAmmo
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_RocketAmmo");
		Spawn_VenomVial:
			TNT1 A 0 A_SpawnItemEx("GWM_VenomVial");
			Stop;
		Spawn_RocketAmmo:
			TNT1 A 0 A_SpawnItemEx("GWM_RocketAmmo");
			Stop;
	}
}
class GWM_RocketBoxSpawner : GWM_WeaponSpawner replaces RocketBox
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_RocketBox");
		Spawn_LargeVenomVial:
			TNT1 A 0 A_SpawnItemEx("GWM_LargeVenomVial");
			Stop;
		Spawn_RocketBox:
			TNT1 A 0 A_SpawnItemEx("GWM_RocketBox");
			Stop;
	}
}

class GWM_CellPackSpawner : Actor replaces CellPack
{
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf((random(0, 8)%8), "Spawn2");
		Spawn_Heatsink:
			TNT1 A 0 A_SpawnItemEx("GWM_MelterHeatsink");
		Spawn2:
			TNT1 A 0 A_SpawnItemEx("GWM_CellPack");
			Stop;
	}
}

class GWM_ChainsawSpawner : GWM_WeaponSpawner replaces Chainsaw
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_Impactor");
		Spawn_Icebreaker:
			TNT1 A 0 A_SpawnItemEx("GWM_Icebreaker");
			Stop;
		Spawn_Impactor:
			TNT1 A 0 A_SpawnItemEx("GWM_Impactor");
			Stop;
	}
}

class GWM_ShotgunSpawner : GWM_WeaponSpawner replaces Shotgun
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_Shotgun");
		Spawn_IceShotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_IceShotgun");
			Stop;
		Spawn_Shotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_Shotgun");
			Stop;
	}
}

class GWM_SuperShotgunSpawner : GWM_WeaponSpawner replaces SuperShotgun
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_SuperShotgun");
		Spawn_PFSuperShotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_PFSuperShotgun");
			Stop;
		Spawn_SuperShotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_SuperShotgun");
			Stop;
	}
}

class GWM_ChaingunSpawner : GWM_WeaponSpawner replaces Chaingun
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_Chaingun");
		Spawn_BurstRifle:
			TNT1 A 0 A_SpawnItemEx("GWM_BurstRifle");
			Stop;
		Spawn_Chaingun:
			TNT1 A 0 A_SpawnItemEx("GWM_Chaingun");
			Stop;
	}
}

class GWM_RocketLauncherSpawner : GWM_WeaponSpawner replaces RocketLauncher
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_RocketLauncher");
		Spawn_VenomCannon:
			TNT1 A 0 A_SpawnItemEx("GWM_VenomCannon");
			Stop;
		Spawn_RocketLauncher:
			TNT1 A 0 A_SpawnItemEx("GWM_RocketLauncher");
			Stop;
	}
}

class GWM_PlasmaRifleSpawner : GWM_WeaponSpawner replaces PlasmaRifle
{
	States
	{
		Spawn2:
			TNT1 A 0 A_JumpIf(random(0, 1), "Spawn_PlasmaRifle");
		Spawn_Melter:
			TNT1 A 0 A_SpawnItemEx("GWM_Melter");
			Stop;
		Spawn_PlasmaRifle:
			TNT1 A 0 A_SpawnItemEx("GWM_PlasmaRifle");
			Stop;
	}
}

class GWM_BlurSphereSpawner : Actor replaces BlurSphere
{
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf((random(0, 3) == 3), "Spawn_DrainSphere");
			TNT1 A 0 A_JumpIf((random(0, 3) == 1 || random(0, 3) == 2), "Spawn_BlurSphere");
			TNT1 A 0 A_JumpIf((random(0, 3) == 0), "Spawn_Stopwatch");
		Spawn_DrainSphere:
			TNT1 A 0 A_SpawnItemEx("GWM_DrainSphere");
			Stop;
		Spawn_Stopwatch:
			TNT1 A 0 A_SpawnItemEx("GWM_Stopwatch");
			Stop;
		Spawn_BlurSphere:
			TNT1 A 0 A_SpawnItemEx("GWM_BlurSphere");
			Stop;
	}
}

class GWM_InvulnerabilitySphereSpawner : Actor replaces InvulnerabilitySphere
{
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf(random(0, 1), "Spawn_InvulnerabilitySphere");
		Spawn_ReflectSphere:
			TNT1 A 0 A_SpawnItemEx("GWM_ReflectSphere");
			Stop;
		Spawn_InvulnerabilitySphere:
			TNT1 A 0 A_SpawnItemEx("GWM_InvulnerabilitySphere");
			Stop;
	}
}