class ShellSpawner : Actor replaces Shell
{
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn_IceShell");
			TNT1 A 0 A_Jump(128, "Spawn_Shell");
			Loop;
		Spawn_IceShell:
			TNT1 A 0 A_SpawnItemEx("IceShell");
			Stop;
		Spawn_Shell:
			TNT1 A 0 A_SpawnItemEx("Shell");
			Stop;
	}
}

class ShellBoxSpawner : Actor replaces ShellBox
{
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn_IceShellBox");
			TNT1 A 0 A_Jump(128, "Spawn_ShellBox");
			Loop;
		Spawn_IceShellBox:
			TNT1 A 0 A_SpawnItemEx("IceShellBox");
			Stop;
		Spawn_ShellBox:
			TNT1 A 0 A_SpawnItemEx("ShellBox");
			Stop;
	}
}

class ShotgunSpawner : Actor replaces Shotgun
{
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn_IceShotgun");
			TNT1 A 0 A_Jump(128, "Spawn_Shotgun");
			Loop;
		Spawn_IceShotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_IceShotgun");
			Stop;
		Spawn_Shotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_Shotgun");
			Stop;
	}
}

class SuperShotgunSpawner : Actor replaces SuperShotgun
{
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn_PFSuperShotgun");
			Loop;
		Spawn_PFSuperShotgun:
			TNT1 A 0 A_SpawnItemEx("GWM_PFSuperShotgun");
			Stop;
	}
}