// Weapon bases
#include "./Weapons/Weapon base classes.zsc"

#include "./Weapons/Slot 1/GWM_Fist.zsc"					// Fist, taken from Super Skulltag and rewritten slightly, then damage randomization was removed
#include "./Weapons/Slot 1/GWM_Impactor.zsc"				// Impactor Gauntlet, taken from Realm667.
#include "./Weapons/Slot 1/GWM_Lumberjack.zsc"			// "Lumberjack" Chainsaw, sprites by Captain J
#include "./Weapons/Slot 1/GWM_Levenbrech.zsc"			// Levenbrech

#include "./Weapons/Slot 2/GWM_Pistol.zsc"				// Pistol
	#include "./Weapons/Slot 2/GWM_TwinPistol.zsc"			// TwinPistol
#include "./Weapons/Slot 2/GWM_SMG.zsc"					// SMG
	#include "./Weapons/Slot 2/GWM_MP40.zsc"					// MP40
#include "./Weapons/Slot 2/GWM_Revolver.zsc"				// Revolver
#include "./Weapons/Slot 2/GWM_GoldWand.zsc"				// Gold Wand

#include "./Weapons/Slot 3/GWM_ZombieShotgun.zsc"			// The beginning of a long road of various scatterguns!
	#include "./Weapons/Slot 3/GWM_SlayersKahuna.zsc"			// Slayer's Kahuna
	#include "./Weapons/Slot 3/GWM_WhiteWedding.zsc"			// ITS A NICE DAY TO START AGAAAAAAAAIN
#include "./Weapons/Slot 3/GWM_SawedOffShotgun.zsc"			// Sawed Off Shotgun
	#include "./Weapons/Slot 3/GWM_SuperShotgun.zsc"			// Super Shotgun
	#include "./Weapons/Slot 3/GWM_Hydra.zsc"					// Shocking
#include "./Weapons/Slot 3/GWM_ImpalerCrossbow.zsc"		// Impaler Crossbow

#include "./Weapons/Slot 4/GWM_Minigun.zsc"				// Minigun
	#include "./Weapons/Slot 4/GWM_MadVulcan.zsc"				// Mad Vulcan
		#include "./Weapons/Slot 4/GWM_Basilisk.zsc"				// Basilisk
#include "./Weapons/Slot 4/GWM_AssaultRifle.zsc"			// Assault Rifle
	#include "./Weapons/Slot 4/GWM_BurstRifle.zsc"			// Burst Rifle
#include "./Weapons/Slot 4/GWM_Scrapgun.zsc"				// Not exactly TangoScrapgun anymore... (from Supercharge)
#include "./Weapons/Slot 4/GWM_FrostFang.zsc"				// Frost Fang... Both shit and busted. How???

#include "./Weapons/Slot 5/GWM_RocketLauncher.zsc"		// Rocket Launcher
#include "./Weapons/Slot 5/GWM_GrenadeLauncher.zsc"		// Yep, they're split again... -g     For the better tbh -m
	#include "./Weapons/Slot 5/GWM_THE_BOUNCERRR.zsc"	    	// I was gonna copy the wikipedia article on the BOUNCERRRRRR here but it fucked stuff up. :( -Mengo
	#include "./Weapons/Slot 5/GWM_GoldenBouncer.zsc"	    	// A ratchet and clank AND gundam reference at once? I've outdone myself -Mengo
#include "./Weapons/Slot 5/GWM_Stomper.zsc"				// THE STOMPERRR (from Supercharge)
#include "./Weapons/Slot 5/GWM_Trumpetbuss.zsc"			// Trumpetbuss (from Golden Souls 2)
	#include "./Weapons/Slot 5/GWM_Tromboomer.zsc"			// Tromboomer (originally Golden Trumpetbuss) (from Golden Souls 2)

#include "./Weapons/Slot 6/GWM_PlasmaRifle.zsc"			// Plasma Rifle
#include "./Weapons/Slot 6/GWM_NoiseCrusher.zsc"		// Noise Crusher! I'll make it good eventually I promise man -mengo
#include "./Weapons/Slot 6/GWM_Railgun.zsc"				// Railgun, from Skulltag

#include "./Weapons/Slot 7/GWM_BFG9000.zsc"				// BFG9000 (Vanilla but kinda shittier)
#include "./Weapons/Slot 7/GWM_BFG10K.zsc"				// BFG10K (newer but not necessarily better in every situation)

#include "./Weapons/Slot 8/GWM_EldritchAnnihilator.zsc"	// Shroine Tew, out now!
#include "./Weapons/Slot 8/GWM_Perforator.zsc"			// Evitahnity Tew, out now!

#include "./Weapons/Slot 9/GWM_IceShotgun.zsc"			// Ice Shotgun
#include "./Weapons/Slot 9/GWM_PFMissileLauncher.zsc"		// Perfect Freeze Missile Launcher
#include "./Weapons/Slot 9/GWM_Flamethrower.zsc"			// Flamethrower
#include "./Weapons/Slot 9/GWM_AcidCannon.zsc"			// Acid Cannon (corrosive goop gun)
#include "./Weapons/Slot 9/GWM_Melter.zsc"				// Melter