class GWM_BFG9000 : BFG9000 replaces BFG9000
{
	States
	{
		Ready:
			BFUG A 1 A_WeaponReady;
			Loop;
		Deselect:
			BFUG A 1 A_Lower(12);
			Loop;
		Select:
			BFUG A 1 A_Raise(12);
			Loop;
		Fire:
			TNT1 A 0 A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
			BFUG A 5 A_BFGSound;
			BFUG B 10 A_Overlay(-2, "Flash");
			BFUG C 5;
			BFUG C 5 {
				A_FireBFG();
				A_WeaponOffset(0, 63, flags: WOF_ADD);
				A_OverlayScale(OverlayID(), 1.60, 0, WOF_INTERPOLATE);
			}
			BFUG CCB 2 {
				A_WeaponOffset(0, -21, flags: WOF_ADD);
				A_OverlayScale(OverlayID(), -0.20, 0, WOF_ADD);
			}
			BFUG BBB 2;
			BFUG A 5 A_ReFire;
			Goto Ready;
		Flash:
			TNT1 A 0 A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
			BFUF AB 5 Bright A_Light1;
			BFUF C 5 Bright A_Light2;
			BFUF C 5 Bright {
				A_Light2();
				A_OverlayScale(OverlayID(), 1.60, 0, WOF_INTERPOLATE);
			}
			BFUF DEF 2 Bright {
				A_OverlayScale(OverlayID(), -0.20, 0, WOF_ADD);
			}
			Goto LightDone;
		Spawn:
			BFUG Z -1;
			Stop;
	}
}