class GWM_EldritchAnnihilator : GWM_WeaponBase
{
	Default
	{
		Weapon.SelectionOrder 2800;
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 50;
		Weapon.AmmoType "GWM_AnnihilatorAmmo";
		Tag "$TAG_ANNIHILATOR";
		Inventory.PickupMessage "$GOTANNIHILATOR";
		Obituary "$KILLANNIHILATOR";
	}
	States
	{
	
		Ready:
			BF27 A 1 A_WeaponReady;
			Loop;
		Deselect:
			BF27 A 1 A_Lower(18);
			Loop;
		Select:
			BF27 A 1 A_Raise(18);
			Loop;
		
		  Fire:
			BF27 A 15 A_StartSound("weapons/ANNHC1",CHAN_AUTO);
			BF27 B 15;
			BF27 C 4 Bright;
			TNT1 A 0 A_Overlay(2,"SoundStart");
		Hold:
			TNT1 A 0 A_GiveInventory("FiringAnnihilator",1);
			BF27 DE 1 Bright
			{
				A_FireProjectile("ELDRITCHBALL",random(-10,10),1,10,0,0,random(-10,10));
				A_FireProjectile("ELDRITCHBALL",random(-10,10),0,10,0,0,random(-10,10));
				A_FireProjectile("ELDRITCHBALL",random(-10,10),0,10,0,0,random(-10,10));
			}		
		
	TNT1 A 0 A_Refire();
	Fired:
	TNT1 A 0 A_TakeInventory("FiringAnnihilator",1);
	BF27 EC 1 Bright;
	BF27 B 10;
	Goto Ready;
	
  SoundStart:
	TNT1 A 10 A_StartSound("weapons/ANNHF1",CHAN_AUTO);
	SoundContinue:
	TNT1 A 20 A_StartSound("weapons/ANNHF2",CHAN_AUTO);
	TNT1 A 0 A_JumpifInventory("FiringAnnihilator",1,"SoundContinue");
	TNT1 A 1 A_StartSound("weapons/ANNHF3",CHAN_AUTO);
	stop;	
			
		Spawn:
			BF27 Z -1;
			Stop;
	}
}
Class FiringAnnihilator : inventory {Default {Inventory.Maxamount 1;}}


Class ELDRITCHBALL : Actor
{
	Default
	{
		Damagefunction (20);
		BounceType "Hexen";
		BounceFactor 1;
		+USEBOUNCESTATE;
		+EXTREMEDEATH;
		+FORCEXYBILLBOARD;
		Damagetype "Annihilator";
		Projectile;
		Speed 45;
		Obituary "$KILLANNIHILATOR";
		Seesound "Annihilator/Fire";
	}
	States
	{
		Bounce:
			TNT1 AAA 0 A_SpawnitemEX("MiniAnnihilatorpuff",random(-10,10),random(-10,10),random(-10,10),random(-4,4),random(-4,4),random(-4,4));
			TNT1 A 0 A_Fadeout(0.05);
			goto Spawn;
			
		Spawn:
			BBGB AB 6 Bright;
		Loop;
		
		Death:
			TNT1 A 0 A_SpawnitemEX("AnnihilatorShaker");
			TNT1 AAAAA 0 A_SpawnitemEX("Annihilatorpuff",random(-10,10),random(-10,10),random(-10,10),random(-9,9),random(-9,9),random(-9,9));
			TNT1 A 0 A_Explode(10,40);
			BBGB C 6 Bright;
			BBGB DE 4 Bright;
			Stop;
		

		
}
}

Class MiniAnnihilatorpuff : Annihilatorpuff
{
Default
{
Alpha 0.25;
Scale 0.45;
}
}

Class Annihilatorpuff : Actor
{
Default
{
+Nointeraction;
+FORCEXYBILLBOARD;
Renderstyle "Add";
Scale 0.75;
}
States
{
Spawn:
	BBGB CCCDDEE 2 Bright 
	{
	A_Fadeout(0.05);
	A_ScaleVelocity(0.9);
	}
	Stop;
}
}

Class AnnihilatorShaker : Actor
{
States
{
Fuckoff:
TNT1 A 1;
stop;
Spawn:
TNT1 A 3 Radius_Quake (5, 8, 0, 50, 0);
TNT1 A 3 Radius_Quake (4, 8, 0, 50, 0);
TNT1 A 3 Radius_Quake (3, 8, 0, 50, 0);
stop;
}}
