class GWM_IceShotgun : GWM_WeaponBase
{
	Default
	{
		Weapon.SelectionOrder 1300;
		Inventory.PickupSound "weapons/icepickup";
		Weapon.UpSound "weapons/draw_secondary";
		Weapon.AmmoType "GWM_IceShell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Inventory.PickupMessage "$GOTICESHOTGUN";
		Tag "Ice Shotgun";
	}
	States
	{
		Ready:
			ISHT A 1 A_WeaponReady;
			Loop;
		Deselect:
			ISHT A 1 A_Lower(12);
			Loop;
		Select:
			ISHT A 1 A_Raise(12);
			Loop;
		Fire:
			TNT1 A 0 {
				A_OverlayPivot(OverlayID(), 0.5, 0.5, 0);
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_OverlayScale(OverlayID(), 1, 0, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayID(), 0, WOF_INTERPOLATE);
			}
			ISHT A 1 {
				A_FireProjectile("GWM_ShotgunIce");
				A_StartSound("weapons/iceshgn", CHAN_WEAPON);
				A_SpawnItemEx("GWM_IceFlash");
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				A_WeaponOffset(0, 20, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.15, 0, WOF_INTERPOLATE);
			}
			ISHT A 2;
			ISHT AA 4 {
				A_WeaponOffset(0, -10, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.075, 0, WOF_ADD);
			}
			ISHT B 5;
			ISHT CCC 2;
			ISHT D 4 {
				ZWL_EjectCasing("GWM_IceShotgunCasing", offset: (24, -6, -14));
			}
			ISHT CCC 2;
			ISHT B 5;
			ISHT A 3;
			ISHT A 7 A_ReFire;
			Goto Ready;
		AltFire:
			TNT1 A 0 {
				A_OverlayPivotAlign(OverlayID(), PSPA_RIGHT, PSPA_BOTTOM);
				A_OverlayPivot(OverlayID(), 0.5, 0.5, 0);
				A_OverlayScale(OverlayID(), 1, 0, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayID(), 0, WOF_INTERPOLATE);
			}
			ISHT A 2 {
				A_Overlay(-2, "AltFireUnderlay");
				A_OverlayRotate(OverlayID(), 15, WOF_ADD);
			}
			ISHT A 2 {
				A_OverlayRotate(OverlayID(), 15, WOF_ADD);
			}
			ISHT A 4;
			ISHT A 5;
			ISHT AA 2 A_OverlayRotate(OverlayID(), -15, WOF_ADD);
			ISHT A 5 A_ReFire;
			Goto Ready;
		AltFireUnderlay:
			KICK A 4;
			KICK B 4 A_Punch;
			KICK C 5;
			KICK B 4;
			KICK A 5;
			Stop;
		Flash:
			TNT1 A 0 A_OverlayOffset(OverlayID(), 159, 92);
			SGFL ABCCDE 1 Bright;
			Stop;
		Spawn:
			ISHT Z -1;
			Stop;
	}
}
class GWM_ShotgunIce : GWM_IceProjectile
{
	Default
	{
		Radius 13;
		Height 13;
		Speed 50;
		Damage 30;
		Scale 0.33;
		+THRUGHOST
		+RANDOMIZE
		+FORCEXYBILLBOARD
		DeathSound "weapons/icehit";
		Obituary "$KILLICESHOTGUN";
	}
	States
	{
		Spawn:
			SHGI A 6 Bright A_SpawnItemEx("GWM_ShotgunIceTrail");
			loop;
		Death:
			TNT1 A 1 {
				A_SpawnItemEx("GWM_ShotgunIceChunk", 0, 0, 0, -50, 0, 0, 10);
				A_SpawnItemEx("GWM_ShotgunIceChunk", 0, 0, 0, -50, 0, 5, 0);
				A_SpawnItemEx("GWM_ShotgunIceChunk", 0, 0, 0, -50, 0, 0, 0);
				A_SpawnItemEx("GWM_ShotgunIceChunk", 0, 0, 0, -50, 0, -5, 0);
				A_SpawnItemEx("GWM_ShotgunIceChunk", 0, 0, 0, -50, 0, 0, -10);
			}
			stop;
		XDeath:
			SHGI FBCDE 4 Bright;
//			TNT1 A 0 A_ScaleVelocity(0.50, AAPTR_TARGET);	// AAPTR_TARGET is the player, for some reason.
			Stop;
	}
}
class GWM_ShotgunIceChunk : GWM_ShotgunIce
{
	Default
	{
		Radius 7;
		Height 7;
		Damage 6;
		+RIPPER
		BounceType "Doom";
		BounceCount 2;
	}
	States
	{
		Spawn:
			SHGI F 6 Bright A_SpawnItemEx("GWM_ShotgunIceTrail");
			loop;
		Death:
			SHGI BCDE 4 Bright;
			stop;
	}
}
class GWM_ShotgunIceTrail : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 45; // parent - 5
		Damage 0;
		Projectile;
		+RANDOMIZE;
		RenderStyle "Add";
		Alpha 0.75;
		DeathSound "weapons/icehit";
		Obituary "$KILLICESHOTGUN";
	}
	States
	{
		Spawn:
			SHGI BCDE 6 Bright A_FadeOut(0.2);
			loop;
		Death:
			SHGI BCDE 4 Bright;
			stop;
	}
}