class GWM_Shotgun : Shotgun
{
	Default
	{
		Weapon.AmmoType "GWM_Shell";
		Tag "Slayer's Kahuna";
		Inventory.PickupMessage "You got the Slayer's Kahuna!";
		Obituary "%o caught the wave (of pellets) produced by %k's Slayer's Kahuna.";
		AttackSound "weapons/skshot";
	}
	States
	{
		Ready:
			SKSG A 1 A_WeaponReady;
			Loop;
		Deselect:
			SKSG A 1 A_Lower;
			Loop;
		Select:
			SKSG A 1 A_Raise;
			Loop;
		Fire:
			SKSG A 1 {
				A_FireBullets(2.5, 0.83, 8, 6);
				A_SpawnItemEx("GWM_Flash");
				A_GunFlash();
			}
			SKSG AAAA 3;
			SKSG B 5;
			SKSG CCDD 1;
			SKSG E 4 A_StartSound("weapons/skpump1");
			SKSG DDCC 1; // These two play on CHAN_BODY because the firing sound is just too fucking long
			SKSG B 5 A_StartSound("weapons/skpump2");
			SKSG A 3;
			SKSG A 7 A_ReFire;
			Goto Ready;
		Spawn:
			SKSG Z -1;
			Stop;
		Flash:
			SKSF A 4 Bright A_Light1;
			SKSF B 3 Bright A_Light2;
			Goto LightDone;
	}
}