// This is a flammenwerfer. It werfs flammen!
// Alt: BIG BALLS OF FIRE AND MAGMA
class GWM_Volcannon : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "Volcannon
		Tag "$TAG_VOLCANNON";
		Weapon.SlotNumber 9;
		Weapon.UpSound "weapons/draw_primary";
		Inventory.PickupSound "misc/w_pkup";
		Inventory.PickupMessage "$GOTVOLCANNON";
		Obituary "$KILLVOLCANNON";
		Weapon.AmmoType1 "GWM_GasCanister";
		Weapon.AmmoType2 "GWM_GasCanister";
		Weapon.AmmoGive 9;
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 5;
		+Weapon.Explosive
	}
	States
	{
		Spawn:
			VOLG Z -1;
			Loop;
		Ready:
			TNT1 A 0 A_StartSound("weapons/vcready", CHAN_WEAPON);
		Ready2:
			VOLG A 1 A_WeaponReady;
			Loop;
		Deselect:
			VOLG A 1 A_Lower(18);
			Loop;
		Select:
			VOLG A 1 A_Raise(18);
			Loop;
		Fire:
			TNT1 A 0 A_StartSound("weapons/vcfiring", CHAN_WEAPON);
			VOLG A 2 A_StartSound("weapons/vcsqueak", CHAN_BODY);
			VOLG B 1 Bright {
				A_GunFlash();
				A_FireProjectile("GWM_VCFireShot", 0, 1, Random(-4, 4), 0);
				A_FireProjectile("GWM_VCFIREFX", frandom(-10,10), false, 0, 0,0,frandom(-3,3));
				A_FireProjectile("GWM_VCFIREFX", frandom(-10,10), false, 0, 0,0,frandom(-3,3));
				A_FireProjectile("GWM_VCFIREFX", frandom(-10,10), false, 0, 0,0,frandom(-3,3));
				A_FireProjectile("GWM_VCFIREFX", frandom(-10,10), false, 0, 0,0,frandom(-3,3));
				A_FireProjectile("GWM_VCFIREFX", frandom(-10,10), false, 0, 0,0,frandom(-3,3));
			}
			VOLG BC 1 bright A_setpitch(pitch-2);
			VOLG D 2 A_StartSound("weapons/vcend", CHAN_WEAPON);
			VOLG EEEAA 2;
			Goto Ready;
		AltFire:
			TNT1 A 0 A_StartSound("weapons/vcfiring", CHAN_WEAPON);
			VOLG A 2 A_StartSound("weapons/vcsqueak", CHAN_BODY);
			VOLG BBBB 1 {
				A_GunFlash();
				
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-22,22), false, 0, 0,0,frandom(-12,12));
				
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VolcFX2", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				}
			VOLG B 1 bright A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), true, 0, 0,0,frandom(-9,9));
			VOLG BC 1 bright A_setpitch(pitch-2);
			VOLG D 2 A_StartSound("weapons/vcend", CHAN_WEAPON);
			VOLG EEEAA 2;
			Goto Ready;
		Flash:
			TNT1 A 2 A_Light1();
			TNT1 A 2 A_Light2();
			TNT1 A 1 A_Light1();
			TNT1 A 1 A_Light0();
			Stop;
	}
}
Class GWM_VCFireShot : GWM_FlameProjectile
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	Default
	{
		Radius 24;
		Height 24;
		Speed 18;
		DamageFunction (0);
		RenderStyle "Add";
		DamageType "Fire";
		Alpha 0.75;
		Scale 1.17;
		Obituary "$KILLFLAMETHROWER";
		GWM_FlameProjectile.FireBurnCount 50;
	}
	States
	{
		Spawn:
			ZFIR AABBCCDDEEFFGGHHIIJJKKLLMM 1 bright 
			{
			A_SpawnItemEX("GWM_VCFIREFX",0,frandom(-5,5),frandom(-5,5),frandom(6,15),frandom(-1,1),frandom(-2,2));
			A_ScaleVelocity(0.98);
			}
			ZFIR NOP 2 bright A_ScaleVelocity(0.9);
			Stop;
	}
}

Class GWM_VCFIREFX : Actor
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	Default
	{
		+NoInteraction;
		RenderStyle "Add";
		DamageType "Fire";
		Alpha 0.67;
		Scale 1;
		Speed 10;
	}
	States
	{
	Spawn:
		ZFIR ABCDEFGHIJKLMNOP 1 bright A_ScaleVelocity(0.9);
		stop;
	}
}

Class GWM_VolcFX : Actor
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	

	Default
	{
		+NoInteraction;
		RenderStyle "Add";
		DamageType "Fire";
		Alpha 0.27;
		Scale 0.75;
		Speed 10;
	}
	States
	{
	Spawn:
		ZFIR ABCDEFGHIJKLMNOP 1 bright A_ScaleVelocity(0.9);
		stop;
	}
}

Class GWM_VolcFX2 : Actor
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	

	Default
	{
		RenderStyle "Add";
		DamageType "Fire";
		Scale 0.75;
		Speed 10;
	}
	States
	{
	Spawn:
		YFIR A 1 bright A_Fadeout(0.01);
		loop;
	}
}

Class GWM_VolcFX3 : Actor
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	

	Default
	{
		RenderStyle "Add";
		DamageType "Fire";
		Scale 0.15;
		Speed 10;
	}
	States
	{
	Spawn:
		YFIR A 1 bright A_Fadeout(0.01);
		loop;
	}
}


class GWM_VOLCMAGMA : GWM_FlameProjectile
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}	
	Default
	{
		Speed 20;
		DamageFunction (4);
		GWM_FlameProjectile.FireBurnCount 40;
		Height 18;
		Radius 18;
		Scale 2.75;
		Gravity 0.43;
		-NOGRAVITY
		+FORCEXYBILLBOARD
		+RANDOMIZE
		+THRUGHOST
		Projectile;
		BounceSound "weapons/acdcsplt";
		DeathSound "weapons/acdcbomb";
		Obituary "$KILLACIDCANNONBALL";
		-NoGravity;
		Renderstyle "Add";
	}
	States
	{
		Spawn:
			YFIR A 2 bright {
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-2,2),frandom(-2,2),frandom(-2,2));
			}
			Loop;
		Death:
			TNT1 A 0 {
				A_Scream();
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX2",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				A_SpawnItemEX("GWM_VolcFX3",frandom(-22,22),frandom(-22,22),frandom(-22,22),frandom(-12,12),frandom(-12,12),frandom(-12,12));
				
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
				
				
				A_SpawnItemEx("GWM_MagmaPuddle",0,0,5,0,0,0,0,SXF_NOCHECKPOSITION);
			}
			Stop;
			
	}
}



class GWM_MagmaPuddle : GWM_FlameProjectile
{
	
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	Default
	{
		Height 2;
		Projectile;
		Radius 16;
		+NOTELEPORT
		+MOVEWITHSECTOR
		+FORCEXYBILLBOARD
		Scale 2.75;
		DamageFunction (8);
		GWM_FlameProjectile.FireBurnCount 40;
		Obituary "$KILLACIDCANNONPUDDLE";
		Renderstyle "Add";
	}
	States
	{
		Spawn:
			YFIR A 5 bright 
			{
			self.Vel.X = 0; 
			self.Vel.Y = 0; 
			A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
			}
			TNT1 A 0 A_Fadeout(0.0075);
			Loop;
	}
}
