//BIG BALLS OF FIRE AND MAGMA
class GWM_Volcannon : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "Volcannon
		Tag "$TAG_Volcannon";
		Weapon.SlotNumber 9;
		Weapon.UpSound "weapons/draw_primary";
		Inventory.PickupSound "misc/w_pkup";
		Inventory.PickupMessage "$GOTVolcannon";
		Obituary "$KILLVolcannon";
		Weapon.AmmoType "GWM_GasCanister";
		Weapon.AmmoGive 9;
		Weapon.AmmoUse 3;
		+Weapon.Explosive
	}
	States
	{
		Spawn:
			FLTG Z -1;
			Loop;
		Ready:
			TNT1 A 0 A_StartSound("weapons/ftready", CHAN_WEAPON);
		Ready2:
			FLTG A 1 A_WeaponReady;
			Loop;
		Deselect:
			FLTG A 1 A_Lower(18);
			Loop;
		Select:
			FLTG A 1 A_Raise(18);
			Loop;
		Fire:
			TNT1 A 0 A_StartSound("weapons/ftfiring", CHAN_WEAPON);
			FLTG A 2 A_StartSound("weapons/ftsqueak", CHAN_BODY);
			FLGG E 0 {
				A_GunFlash();
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				A_FireProjectile("GWM_VOLCMAGMA", frandom(-18,18), false, 0, 0,0,frandom(-9,9));
				
				}
			FLTG E 1 bright;
			FLTG BC 1 bright A_setpitch(pitch-2);
			FLTG D 2 A_StartSound("weapons/ftend", CHAN_WEAPON);
			FLTG EEEAA 2;
			Goto Ready;
		Flash:
			TNT1 A 2 A_Light1();
			TNT1 A 2 A_Light2();
			TNT1 A 1 A_Light1();
			TNT1 A 1 A_Light0();
			Stop;
	}
}

Class GWM_VolcFX : Actor
{
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	

	Default
	{
		+NoInteraction;
		RenderStyle "Add";
		DamageType "Fire";
		Alpha 0.67;
		Scale 1;
		Speed 10;
	}
	States
	{
	Spawn:
		ZFIR ABCDEFGHIJKLMNOP 1 bright A_ScaleVelocity(0.9);
		stop;
	}
}


class GWM_VOLCMAGMA : GWM_FlameProjectile
{
	
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	
	//actor victim;
    array<actor> hitList;

    override int SpecialMissileHit(actor victim) //G: This is weird. REALLY weird.
    {
        if (hitList.Find(victim) == hitList.Size() && !self.victim && victim.bSHOOTABLE && victim != target && victim.bDORMANT == 0)
        {
			if (victim.CountInv("FireBurnCount")== 0)
			{
				victim.A_SpawnProjectile("GWM_FlameStatusThinker");
			}
			A_StartSound("Status/FireHit");
			
			victim.A_GiveInventory("FireBurnCount",50);
            victim.DamageMobj(self,target,5,'Fire');
            hitlist.Push(victim);
        }
        return 1;
    }
	
	Default
	{
		Speed 20;
		DamageFunction (20);
		GWM_FlameProjectile.FireBurnCount 40;
		Height 24;
		Radius 24;
		BounceCount 11;
		Scale 0.25;
		Gravity 0.43;
		-NOGRAVITY
		+FORCEXYBILLBOARD
		+RANDOMIZE
		+THRUGHOST
		Projectile;
		BounceSound "weapons/acdcsplt";
		DeathSound "weapons/acdcbomb";
		Obituary "$KILLACIDCANNONBALL";
		-NoGravity;
	}
	States
	{
		Spawn:
			MAGP A 2 {
				A_SetScale(0.45, 0.45);
				A_SpawnItemEX("GWM_VolcFX",0,0,12,frandom(-2,2),frandom(-2,2),frandom(-2,2));
			}
			Loop;
		Death:
			TNT1 A 0 {
				A_Scream();
				A_SetScale(0.25, 0.25);
				A_SpawnItemEx("GWM_FloorMagmaPuddle");
			}
			MAGP BCDEF 1;
			Stop;
			
	}
}



class GWM_FloorMagmaPuddle : GWM_FlameProjectile
{
	
	override void Tick()
	{
		Super.Tick();
		if (self.waterlevel > 0)
		{
			self.Destroy();
		}
	}
	
	//actor victim;
    array<actor> hitList;

    override int SpecialMissileHit(actor victim) //G: This is weird. REALLY weird.
    {
        if (hitList.Find(victim) == hitList.Size() && !self.victim && victim.bSHOOTABLE && victim != target && victim.bDORMANT == 0)
        {
			if (victim.CountInv("FireBurnCount")== 0)
			{
				victim.A_SpawnProjectile("GWM_FlameStatusThinker");
			}
			A_StartSound("Status/FireHit");
			
			victim.A_GiveInventory("FireBurnCount",50);
            victim.DamageMobj(self,target,5,'Fire');
            hitlist.Push(victim);
        }
        return 1;
    }
	
	Default
	{
		Height 2;
		Projectile;
		Radius 16;
		-NOGRAVITY
		+NOTELEPORT
		+FLATSPRITE
		+FLOORHUGGER
		+MOVEWITHSECTOR
		Scale 0.8;
		DamageFunction (8);
		GWM_FlameProjectile.FireBurnCount 40;
		Obituary "$KILLACIDCANNONPUDDLE";
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf(random(0, 1), "Puddle3");
			TNT1 A 0 A_JumpIf(random(0, 1), "Puddle2");
		Puddle1:
			MAGP G 1 {self.Vel.X = 0; self.Vel.Y = 0;
			if (Scale.X < 3.1) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.8) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.6) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}}
			Loop;
		Puddle2:
			MAGP H 1 {self.Vel.X = 0; self.Vel.Y = 0;
			if (Scale.X < 3.1) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.8) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.6) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}}
			Loop;
		Puddle3:
			MAGP I 1 {self.Vel.X = 0; self.Vel.Y = 0;
			if (Scale.X < 3.1) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.8) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}
			if (Scale.X < 2.6) {A_Setscale(Scale.X+0.001,Scale.X+0.001);}}
			Loop;
	}
}
