class GWM_GrenadeLauncher : DoomWeapon
{
	Default
	{
		Tag "Grenade Launcher";
		+WEAPON.NOAUTOFIRE
		+WEAPON.NOAUTOAIM
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "RocketAmmo";
		Inventory.PickupMessage "You got the grenade launcher!";
	}
	States
	{
		Spawn:
			GRLA Z -1;
			Stop;
		Ready:
			GRLA A 1 A_WeaponReady;
			Loop;
		Deselect:
			GRLA A 1 A_Lower;
			Loop;
		Select:
			GRLA A 1 A_Raise;
			Loop;
		Fire:
			GRLA A 4;
			GRLA B 4 {
				A_Overlay(-2,"Flash");
				A_PlaySound("weapons/glshot");
			}
			GRLA B 12 {
				A_FireProjectile ("Grenade", 0, true, 0, 0, 0, -6.328125); // A_FireSTGrenade
			}
			GRLA B 0 A_ReFire;
			Goto Ready;
		Flash:
			GRLF ABCD 2 Bright;
			Stop;
	}
}