class GWM_VenomCannon : DoomWeapon
{
	Default
	{
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "GWM_VenomVial";
		Weapon.AmmoType2 "GWM_VenomVial";
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "You got the Venom Cannon!";
		Tag "Venom Cannon";
	}
	States
	{
		Ready:
			VNMG A 1 A_WeaponReady;
			Loop;
		Deselect:
			VNMG A 1 A_Lower;
			VNMG A 0 A_Lower;
			Loop;
		Select:
			VNMG A 1 A_Raise;
			VNMG A 0 A_Raise;
			Loop;
		Fire:
			VNMG B 4 A_Overlay(-2, "Flash");
			VNMG C 6 {
				A_FireProjectile("GWM_VenomBall", 0, true, 0, 0, 0);
				A_StartSound("weapons/vnmcfire", CHAN_WEAPON);
			}
			VNMG BA 2;
			TNT1 A 0 A_ReFire;
			Goto Ready;
		AltFire:
			VNMG B 4 A_Overlay(-2, "Flash");
			VNMG C 6 {
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, true, 0, 10);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 5, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", -5, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, false, 0, -10);
				A_StartSound("weapons/vnmcfire", CHAN_WEAPON);
			}
			VNMG BA 2;
			TNT1 A 0 A_ReFire;
			Goto Ready;
		Flash:
			VNMF ABCDE 2;
			Stop;
		Spawn:
			VNMG Z -1;
			Stop;
	}
}
class GWM_VenomBall : GWM_PoisonProjectile
{
	Default
	{
		Speed 20;
		Damage 80;
		Height 24;
		Radius 24;
		BounceCount 11;
		Scale 0.25;
		Gravity 0.33;
		-NOGRAVITY
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BOUNCEAUTOOFF
		+USEBOUNCESTATE
		+FORCEXYBILLBOARD
		+RANDOMIZE
		BounceSound "weapons/vnmcsplt";
		DeathSound "weapons/vnmcbomb";
		Obituary "%o drank %k's toxic goop.";
	}
	States
	{
		Spawn:
			VNMP A 6 A_SetScale(0.25, 0.25);
			VNMP A 2 A_SetScale(0.25, 0.24);
			VNMP A 2 A_SetScale(0.25, 0.23);
			VNMP A 2 A_SetScale(0.25, 0.22);
			VNMP A 2 A_SetScale(0.25, 0.21);
			VNMP A 2 A_SetScale(0.25, 0.20);
			VNMP A 2 A_SetScale(0.25, 0.21);
			VNMP A 2 A_SetScale(0.25, 0.22);
			VNMP A 2 A_SetScale(0.25, 0.23);
			VNMP A 2 A_SetScale(0.25, 0.24);
			VNMP A 6 A_SetScale(0.25, 0.25);
			VNMP A 2 A_SetScale(0.24, 0.25);
			VNMP A 2 A_SetScale(0.23, 0.25);
			VNMP A 2 A_SetScale(0.22, 0.25);
			VNMP A 2 A_SetScale(0.21, 0.25);
			VNMP A 2 A_SetScale(0.20, 0.25);
			VNMP A 2 A_SetScale(0.21, 0.25);
			VNMP A 2 A_SetScale(0.22, 0.25);
			VNMP A 2 A_SetScale(0.23, 0.25);
			VNMP A 2 A_SetScale(0.24, 0.25);
			Loop;
		Bounce.Ceiling:
			TNT1 A 0 A_SpawnItemEx("GWM_SmallVenomBall");
			Goto Bounce.Vertical;
		Bounce.Floor:
			TNT1 A 0 A_SpawnItemEx("GWM_FloorVenomPuddle");
		Bounce.Vertical:
			VNMP A 1 A_SetScale(0.25, 0.1875);
			VNMP A 1 A_SetScale(0.25, 0.125);
			VNMP A 1 A_SetScale(0.25, 0.1875);
			VNMP A 1 A_SetScale(0.25, 0.25);
			Goto Spawn;
		Bounce.Wall:
			TNT1 A 0 A_JumpIf(random(0, 1), "Bounce.Vertical");	// Randomly jumps to the floor bounce version, for variation.
			VNMP A 1 A_SetScale(0.1875, 0.25);
			VNMP A 1 A_SetScale(0.125, 0.25);
			VNMP A 1 A_SetScale(0.1875, 0.25);
			VNMP A 1 A_SetScale(0.25, 0.25);
			Goto Spawn;
		Death:
			TNT1 A 0 {
				A_Scream();
				A_SetScale(0.25, 0.25);
				A_SpawnItemEx("GWM_SmallVenomBall", xvel: 5, zvel: 10, angle: random(1,360));
				A_SpawnItemEx("GWM_SmallVenomBall", xvel: 5, zvel: 10, angle: random(1,360));
				A_SpawnItemEx("GWM_SmallVenomBall", xvel: 5, zvel: 10, angle: random(1,360));
				A_SpawnItemEx("GWM_SmallVenomBall", xvel: 5, zvel: 10, angle: random(1,360));
				A_SpawnItemEx("GWM_SmallVenomBall", xvel: 5, zvel: 10, angle: random(1,360));
				A_SpawnItemEx("GWM_FloorVenomPuddle");
			}
			VNMP BCDEF 1;
			Stop;
	}
}
class GWM_SmallVenomBall : GWM_VenomBall
{
	Default
	{
		Speed 0;
		Damage 16;
		Height 12;
		Radius 12;
		Scale 0.125;
		Gravity 0.66;
	}
	States
	{
		Spawn:
			VNMP A 6 A_SetScale(0.125, 0.125);
			VNMP A 2 A_SetScale(0.125, 0.124);
			VNMP A 2 A_SetScale(0.125, 0.123);
			VNMP A 2 A_SetScale(0.125, 0.122);
			VNMP A 2 A_SetScale(0.125, 0.121);
			VNMP A 2 A_SetScale(0.125, 0.120);
			VNMP A 2 A_SetScale(0.125, 0.121);
			VNMP A 2 A_SetScale(0.125, 0.122);
			VNMP A 2 A_SetScale(0.125, 0.123);
			VNMP A 2 A_SetScale(0.125, 0.124);
			VNMP A 6 A_SetScale(0.125, 0.125);
			VNMP A 2 A_SetScale(0.124, 0.125);
			VNMP A 2 A_SetScale(0.123, 0.125);
			VNMP A 2 A_SetScale(0.122, 0.125);
			VNMP A 2 A_SetScale(0.121, 0.125);
			VNMP A 2 A_SetScale(0.120, 0.125);
			VNMP A 2 A_SetScale(0.121, 0.125);
			VNMP A 2 A_SetScale(0.122, 0.125);
			VNMP A 2 A_SetScale(0.123, 0.125);
			VNMP A 2 A_SetScale(0.124, 0.125);
			Loop;
		Bounce.Floor:
			TNT1 A 0 A_SpawnItemEx("GWM_FloorVenomPuddle");
			Goto Death;
		Bounce.Wall:
			TNT1 A 0 A_JumpIf(random(0, 1), "Bounce.Ceiling");	// Randomly jumps to the floor bounce version, for variation.
			VNMP A 1 A_SetScale(0.09375,0.125);
			VNMP A 1 A_SetScale(0.0625,0.125);
			VNMP A 1 A_SetScale(0.09375,0.125);
			VNMP A 1 A_SetScale(0.125,0.125);
			Goto Spawn;
		Bounce.Ceiling:
			VNMP A 1 A_SetScale(0.125,0.09375);
			VNMP A 1 A_SetScale(0.125,0.0625);
			VNMP A 1 A_SetScale(0.125,0.09375);
			VNMP A 1 A_SetScale(0.125,0.125);
			Goto Spawn;
		Death:
			TNT1 A 0 {
				A_Scream();
				A_SetScale(0.125, 0.125);
			}
			VNMP BCDEF 1;
			Stop;
	}
}
class GWM_SmallVenomBall_Shotgun : GWM_SmallVenomBall {Default {Speed 20;}}
class GWM_FloorVenomPuddle : GWM_PoisonProjectile
{
	Default
	{
		Height 2;
		Radius 16;
		-NOGRAVITY
		+NOTELEPORT
		+FLATSPRITE
		+FLOORHUGGER
		+MOVEWITHSECTOR
		Damage 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_JumpIf(random(0, 1), "Puddle3");
			TNT1 A 0 A_JumpIf(random(0, 1), "Puddle2");
		Puddle1:
			VNMP G 1 {self.Vel.X = 0; self.Vel.Y = 0;}
			Loop;
		Puddle2:
			VNMP H 1 {self.Vel.X = 0; self.Vel.Y = 0;}
			Loop;
		Puddle3:
			VNMP I 1 {self.Vel.X = 0; self.Vel.Y = 0;}
			Loop;
	}
}