class GWM_Bouncer : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "The Bouncer
		Weapon.SelectionOrder 2800;
		Weapon.SlotNumber 5;
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "GWM_RocketAmmo";
		Tag "$TAG_BOUNCER";
		Inventory.PickupMessage "$GOTBOUNCER";
		Obituary "$KILLBOUNCER";
		GWM_WeaponBase.BaseVersion "GWM_GrenadeLauncher";
		
	}
	States
	{
		Ready:
			BNCL A 1 A_WeaponReady;
			Loop;
		Deselect:
			BNCL A 1 A_Lower(18);
			Loop;
		Select:
			BNCL A 1 A_Raise(18);
			Loop;
		

		Fire:
			TNT1 A 0 {let player = GWM_Player(player.mo);}
			//TNT1 A 0 A_JumpIfInventory("GWM_ChargedGrenades",1,"Fire2");
			BNCL A 2 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_MuzzleFlashLight2");
				A_WeaponOffset(0, 24, WOF_ADD);
				A_StartSound("weapons/bounf1", CHAN_WEAPON);
				A_FireProjectile("GWM_BouncerShot", 0, true);
				A_OverlayScale(OverlayID(), 0.13, 0, WOF_ADD);
			}
			BNCL AAA 1 A_OverlayScale(OverlayID(), 0.13, 0, WOF_ADD);
			TNT1 A 0
			{
				let player = GWM_Player(player.mo); 
				player.PW_FiringGrenade = true; //boolean instead of token.
			}
			Goto Fire.Done;
		Fire.Done:
			BNCL A 3;
			BNCL AAAA 2 {
				A_WeaponOffset(0, -6, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.13, 0, WOF_ADD);
			}
			BNCL A 0 A_OverlayScale(OverlayID(), 1, 0);
			RTKL A 0 A_ReFire;
			Goto Ready;
		
		PowerFire:
			BNCL A 8 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_MuzzleFlashLight2");
				A_SpawnItemEx("GWM_MuzzleFlashLight2");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/bounf1", CHAN_WEAPON);
				A_FireProjectile("GWM_BouncerMiniMega");
				A_OverlayScale(OverlayID(), 1.33, 0, WOF_INTERPOLATE);
			}
			Goto Fire.Done;
		
		Spawn:
			BNCL Z -1;
			Stop;
	}
}

class GWM_BouncerShot : Actor
{
	bool missed;
	int timer;
	
	int blastradius;
	int blastradius2;
	int blastradius3;
	int blastspeed;
	
	action State GrenadeTimerJump()
	{
		A_SpawnItemEx("GWM_BouncerTrail");
		if (invoker.timer < 81) {
			if (!invoker.missed) {
				return ResolveState(null);
			}
			else invoker.timer++;
		}
		if (invoker.timer >= 81) {
			return ResolveState("Death");
		}
		return State(null);
	}
	Default
	{
		Radius 8;
		Height 8;
		Speed 20;
		DamageFunction (125);
		Projectile;
		-NOGRAVITY
		+RANDOMIZE
		+USEBOUNCESTATE
		+THRUGHOST
		BounceType "Hexen";
		Gravity 0.25;
		Scale 2;
		SeeSound "";
		DeathSound "weapons/explode";
		BounceSound "weapons/grndimp";
		Obituary "$KILLGRENADE";
		DamageType "Rocket";
	}
	int charge;
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{	
				let gren = GWM_Grenade(self);
				let player = GWM_Player(target);
				if(gren)
				{
					gren.charge = player.chargedGrenades;
				}
			}
		Spawnloop:
			BONC A 1 Bright {
				GrenadeTimerJump();
				
			}
			BONC A 1 Bright GrenadeTimerJump;
			goto Spawnloop;
		Bounce:
			TNT1 A 0 {GrenadeTimerJump();}
			TNT1 A 0 {invoker.missed = true;}
			Goto Spawnloop;
		Bounce.Actor:
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_SpawnItemEx("GWM_MuzzleFlashLight3",0,0,5);
				A_SpawnItemEx("GWM_MuzzleFlashLight3",0,0,5);
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(125,215+15*invoker.charge);
			}
		TNT1 A 0 A_SpawnItemEX("ShakeItBaby",0,0,5);
		TNT1 AAAAA 1
		{
		blastradius = 65+15*invoker.charge;
		blastradius2 = blastradius * 0.5;
		blastradius3 = blastradius * 0.25;
		blastspeed = 4+1*invoker.charge;
		for (int i = 4; i > 0; i--)
		{
		A_SpawnItemEX("BlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-blastradius3,blastradius3),frandom(-blastradius3,blastradius3),frandom(-blastradius3,blastradius3),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
		}
		
		A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		
		if(invoker.charge>0)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>1)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>2)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>3)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
			
		if(invoker.charge>4)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
			
		if(invoker.charge>5)
			{
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>3)
			{
			A_SpawnItemEX("BlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			}
			
		if(invoker.charge>5)
			{
			A_SpawnItemEX("BlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			}
		}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}

class GWM_BouncerMini : GWM_BouncerShot
{
	
	Default
	{
		Radius 8;
		Height 8;
		Speed 10;
		DamageFunction (50);
		Projectile;
		-NOGRAVITY
		+RANDOMIZE
		+USEBOUNCESTATE
		+THRUGHOST
		BounceType "Hexen";
		Gravity 0.40;
		SeeSound "";
		Scale 1.25;
		DeathSound "weapons/bounx2";
		BounceSound "weapons/bounb2";
		Obituary "$KILLBOUNCE2";
		DamageType "Rocket";
		Reactiontime 80;
		+SEEKERMISSILE;
		+SCREENSEEKER;
	}
	States
	{
		Spawn:
			BONC A 1 Bright {
				A_Countdown();
				//A_SpawnItemEx("GWM_RocketTrail", -20);
			}
			BONC AAAA 1 Bright;
			Loop;
		Bounce:
			TNT1 A 0 A_Countdown();
			BONC AA 1 A_SeekerMissile(90,90,SMF_LOOK);
			TNT1 A 0 A_CheckCeiling("BounceDown");
			
			TNT1 A 0 
			{
			A_Changevelocity(8,0,6,CVF_REPLACE|CVF_RELATIVE);
			A_Startsound("weapons/bounb2");
			}
			
			Goto Spawn;
		BounceDown:	
			TNT1 A 0 
			{
			A_Changevelocity(8,0,-7,CVF_REPLACE|CVF_RELATIVE);
			A_Startsound("weapons/bounb2");
			}
			goto Spawn;
		
		Bounce.Actor:
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,5);
				
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-1,1),frandom(-1,1),frandom(-1,1),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-1,1),frandom(-1,1),frandom(-1,1),frandom(1,359));
				
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(30,45);
				A_QuakeEx(3, 3, 3, 10, 0, 512, flags: QF_SHAKEONLY);
			}
			Stop;
	}
}

class GWM_BouncerMiniMega : GWM_BouncerShot
{
	
	Default
	{
		Radius 66;
		Height 66;
		Speed 10;
		DamageFunction (120);
		BounceType "Hexen";
		BounceCount 50;
		BounceFactor 0.9;
		Gravity 0.4;
		Obituary "$KILLBOUNCE";
		DamageType "Rocket";
		Reactiontime 25;
		Scale 8;
	}
	States
	{
		Spawn:
			BONC A 1 Bright {
				A_Countdown();
				//A_SpawnItemEx("GWM_RocketTrail", -20);
			}
			BONC AAAA 1 Bright;
			Loop;
		Bounce:
			BONC A 1 A_Startsound("weapons/bounb1");
			goto Spawn;
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SpawnItemEX("GWM_BouncerBlastMega");
				
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					A_SpawnItemEX("GWM_BouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
					
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(85,190);
				A_QuakeEx(3, 3, 3, 10, 0, 512, flags: QF_SHAKEONLY);
			}
			Stop;
	}
}

Class GWM_BouncerBlastMega : Actor
{
	Default
	{
		+NoInteraction
	}

	States
	{
	Spawn:
		TNT1 A 1 nodelay A_SpawnItemEX("ShakeItBaby",0,0,5);
		TNT1 AAA 1
		{
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-6,6),frandom(-6,6),frandom(-6,6),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-6,6),frandom(-6,6),frandom(-6,6),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-6,6),frandom(-6,6),frandom(-6,6),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-10,10),frandom(-10,10),frandom(-10,10),frandom(1,359));
		}
		stop;
	}
}

class GWM_BouncerTrail : Actor
{
	int charge;
	Default
	{
		+NOTELEPORT;
		+NOINTERACTION;
		Renderstyle "Add";
		Scale 1;
		Alpha 0.75;
	}
	States
	{
		Spawn:
			
		Spawnloop:
			GNDE J 2 Bright A_Fadeout(0.075);
			loop;
	}
}