class GWM_RocketLauncher : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "Rocket Launcher
		Weapon.SelectionOrder 2500; // Don't blow yourself up!!
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "GWM_RocketAmmo";
		Weapon.AmmoType2 "GWM_RocketAmmo";
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "$GOTROCKETLAUNCHER";
		Tag "$TAG_ROCKETLAUNCHER";
	}
	States
	{
		Ready:
			RKTL A 1 A_WeaponReady;
			Loop;
		Deselect:
			RKTL A 1 A_Lower(18);
			Loop;
		Select:
			RKTL A 1 A_Raise(18);
			Loop;
		Fire:
			RKTL A 2 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_Flash");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/rocketfire", CHAN_WEAPON);
				A_FireProjectile("GWM_Rocket");
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			RKTL A 2;
			Goto Fire.Done;
		Fire.Done:
			RKTL A 3;
			RKTL AAA 3 {
				A_WeaponOffset(0, -6, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.11, 0, WOF_ADD);
			}
			RTKL A 0 A_ReFire;
			Goto Ready;
		AltFire:
			RKTL A 2 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_Flash");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/grenadefire", CHAN_WEAPON);
				A_FireProjectile("GWM_Grenade", 0, true);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			RKTL A 2;
			Goto Fire.Done;
		Flash:
			RKTF ABC 2 Bright {
				A_Light1();
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTF DE 2 Bright A_Light2;
			Stop;
		Spawn:
			RKTL Z -1;
			Stop;
	}
}
class GWM_Rocket : Actor
{
	Default
	{
		Radius 11;
		Height 8;
		Speed 30; // faster.
		DamageFunction (110);
		Projectile;
		+RANDOMIZE
		+THRUGHOST
		SeeSound "";
		DeathSound "weapons/explode";
		Obituary "$KILLROCKET";
		DamageType "Rocket";
	}
	States
	{
		Spawn:
			RCKT A 2 Bright A_SpawnItemEx("GWM_RocketTrail", -20);
			Loop;
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(100,150);
				A_SpawnItemEX("GWM_RocketBlast");
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_Grenade : Actor
{
	bool missed;
	int timer;
	action State GrenadeTimerJump()
	{
		if (invoker.timer < 81) {
			if (!invoker.missed) {
				return ResolveState(null);
			}
			else invoker.timer++;
		}
		if (invoker.timer >= 81) {
			return ResolveState("Death");
		}
		return State(null);
	}
	Default
	{
		Radius 8;
		Height 8;
		Speed 25;
		DamageFunction (90);
		Projectile;
		-NOGRAVITY
		+RANDOMIZE
		+USEBOUNCESTATE
		+THRUGHOST
		BounceType "Hexen";
		Gravity 0.25;
		SeeSound "";
		DeathSound "weapons/explode";
		BounceSound "weapons/grndimp";
		Obituary "$KILLGRENADE";
		DamageType "Rocket";
	}
	States
	{
		Spawn:
			GNDE A 1 Bright {
				GrenadeTimerJump();
				A_SpawnItemEx("GWM_RocketTrail", -20);
			}
			GNDE A 1 Bright GrenadeTimerJump;
			Loop;
		Bounce:
			TNT1 A 0 {invoker.missed = true;}
			Goto Spawn;
		Bounce.Actor:
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(110,215);
				A_SpawnItemEX("GWM_RocketBlast");
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_RocketTrail : Actor
{
	Default
	{
		+NOBLOCKMAP +NOGRAVITY +NOTELEPORT +NOINTERACTION
	}
	States
	{
		Spawn:
			RCKT BCDEF 2 Bright;
			Stop;
	}
}

Class GWM_RocketBlast : Actor
{
	Default
	{
		+NoInteraction
	}

	States
	{
	Spawn:
		TNT1 A 1 nodelay A_SpawnItemEX("ShakeItBaby",0,0,5);
		TNT1 AA 1
		{
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		}
		stop;
	}
}