class GWM_ChargedRockets : Inventory {Default{Inventory.Maxamount 4;}}

class GWM_RocketLauncher : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "Rocket Launcher
		Weapon.SelectionOrder 2500; // Don't blow yourself up!!
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 3;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "GWM_RocketAmmo";
		Weapon.AmmoType2 "GWM_RocketAmmo";
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "$GOTROCKETLAUNCHER";
		Tag "$TAG_ROCKETLAUNCHER";
	}
	States
	{
		Ready:
			RKTL A 1 A_WeaponReady;
			Loop;
		Deselect:
			RKTL A 1 A_Lower(18);
			Loop;
		Select:
			RKTL A 1 A_Raise(18);
			Loop;
		Fire:
			TNT1 A 0
			{
			let player = GWM_Player(player.mo);
			}
			TNT1 A 0 A_JumpIfInventory("GWM_ChargedRockets",1,"Fire2");//A_Jumpif(player.ChargedRockets > 0,"Fire2");
			RKTL A 2 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_Flash");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/rocketfire", CHAN_WEAPON);
				A_FireProjectile("GWM_Rocket");
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			RKTL A 2;
			Goto Fire.Done;
		Fire.Done:
			RKTL A 3;
			RKTL AAA 3 {
				A_WeaponOffset(0, -6, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.11, 0, WOF_ADD);
			}
			RTKL A 0 A_ReFire;
			Goto Ready;
		Fire2:
			RKTL A 0 {
				A_TakeInventory("GWM_ChargedRockets",1);
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_Flash");
				A_SpawnItemEx("GWM_Flash");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/rocketfire", CHAN_WEAPON);
				A_StartSound("weapons/chargedrocketfire", CHAN_AUTO);
				A_FireProjectile("GWM_ChargedRocket");
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			RKTL AAA 3 {
				A_WeaponOffset(0, -6, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.11, 0, WOF_ADD);
			}
			RTKL A 0 A_ReFire;
			Goto Ready;
			
		AltFire:
			RKTL A 2 {
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_Flash");
				A_WeaponOffset(0, 18, WOF_ADD);
				A_StartSound("weapons/rocketfire", CHAN_WEAPON);
				A_StartSound("weapons/chargedrocketfire", CHAN_AUTO);
				if (CountInv("GWM_ChargedRockets")==4){A_FireProjectile("GWM_HomingRocket4");}
				if (CountInv("GWM_ChargedRockets")==3){A_FireProjectile("GWM_HomingRocket3");}
				if (CountInv("GWM_ChargedRockets")==2){A_FireProjectile("GWM_HomingRocket2");}
				if (CountInv("GWM_ChargedRockets")==1){A_FireProjectile("GWM_HomingRocket1");}
				if (CountInv("GWM_ChargedRockets")==0){A_FireProjectile("GWM_HomingRocket");}
				A_TakeInventory("GWM_ChargedRockets",8);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			RKTL A 2;
			Goto Fire.Done;
		Flash:
			RKTF ABC 2 Bright {
				A_Light1();
				A_OverlayPivot(OverlayID(), 0.66, 1);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			RKTF DE 2 Bright A_Light2;
			Stop;
		Spawn:
			RKTL Z -1;
			Stop;
	}
}
class GWM_Rocket : Actor
{
	Default
	{
		Radius 11;
		Height 8;
		Speed 30; // faster.
		DamageFunction (110);
		Projectile;
		+RANDOMIZE
		+THRUGHOST
		SeeSound "";
		DeathSound "weapons/explode";
		Obituary "$KILLROCKET";
		DamageType "Rocket";
	}
	States
	{
		Spawn:
			RCKT A 2 Bright A_SpawnItemEx("GWM_RocketTrail", -20);
			Loop;
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(100,150);
				A_SpawnItemEX("GWM_RocketBlast");
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_ChargedRocket : GWM_Rocket
{
	Default
	{
		Speed 40; // faster.
		DamageFunction (115);
		Scale 1.25;
		+EXTREMEDEATH
	}
	States
	{
		Spawn:
			RCKT A 1 Bright 
			{
			A_SpawnItemEx("GWM_RocketTrail", -20,0,0,frandom(-0.5,0.5),frandom(-0.5,0.5),frandom(-0.5,0.5));
			A_SpawnItemEx("GWM_RocketTrail", -20,0,0,frandom(-0.5,0.5),frandom(-0.5,0.5),frandom(-0.5,0.5));
			}
			Loop;
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(125,175);
				A_SpawnItemEX("GWM_RocketBlast");
				A_SpawnItemEX("GWM_RocketBlast");
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_RocketTrail : Actor
{
	Default
	{
		+NOBLOCKMAP +NOGRAVITY +NOTELEPORT +NOINTERACTION
	}
	States
	{
		Spawn:
			RCKT BCDEF 2 Bright;
			Stop;
	}
}
class GWM_SuperRocketTrail : GWM_RocketTrail
{
	Default
	{
		Scale 1.5;
	}
	States
	{
		Spawn:
			RCKT BCDEF 3 Bright;
			Stop;
	}
}
Class GWM_RocketBlast : Actor
{
	Default
	{
		+NoInteraction
	}

	States
	{
	Spawn:
		TNT1 A 1 nodelay A_SpawnItemEX("ShakeItBaby",0,0,5);
		TNT1 AA 1
		{
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX2",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-4,4),frandom(-4,4),frandom(-4,4),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		A_SpawnItemEX("BlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-12,12),frandom(-12,12),frandom(-12,12),frandom(1,359));
		}
		stop;
	}
}
class GWM_HomingRocket : GWM_Rocket
{
	Default
	{
		Speed 30; // faster.
		DamageFunction (100);
		Scale 1;
		+SeekerMissile;
		+ScreenSeeker;
	}
	int homing;
	int dist;
	int dmg;
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				homing = 1;
				dist = 100;
				dmg = 100;
			}
		Spawnloop:
			RCKT A 1 Bright 
			{
			A_SeekerMissile(invoker.homing,invoker.homing,SMF_LOOK);
			A_SpawnItemEx("GWM_RocketTrail", -20,0,0,frandom(-0.5,0.5),frandom(-0.5,0.5),frandom(-0.5,0.5));
			}
			Loop;
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(invoker.dmg,invoker.dist);
				A_SpawnItemEX("GWM_RocketBlast");
			}
			Blast:
			TNT1 A 0;
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_HomingRocket1 : GWM_HomingRocket
{
	Default
	{
		+EXTREMEDEATH;
		Speed 35; // faster.
		DamageFunction (125);
		
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				homing = 3;
				dist = 125;
				dmg = 125;
			}
			goto Spawnloop;
	}
}
class GWM_HomingRocket2 : GWM_HomingRocket1
{
	Default
	{
		+EXTREMEDEATH;
		Speed 40; // faster.
		DamageFunction (150);
		
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				homing = 10;
				dist = 125;
				dmg = 150;
			}
			goto Spawnloop;
		Blast:
			TNT1 AAA 1
			{
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_HomingRocket3 : GWM_HomingRocket2
{
	Default
	{
		+EXTREMEDEATH;
		Speed 40; // faster.
		DamageFunction (175);
		
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				homing = 30;
				dist = 150;
				dmg = 180;
			}
			goto Spawnloop;
		Blast:
			TNT1 AAA 1
			{
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}
class GWM_HomingRocket4 : GWM_HomingRocket3
{
	Default
	{
		+EXTREMEDEATH;
		Speed 40; // faster.
		DamageFunction (200);
		
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				homing = 90;
				dist = 150;
				dmg = 200;
			}
			goto Spawnloop;
		Blast:
			TNT1 AAA 1
			{
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX2",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-9,9),frandom(-9,9),frandom(-9,9),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-86,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
				A_SpawnItemEX("BlastFlameFX",frandom(-85,85),frandom(-15,15),frandom(2,45),frandom(-24,24),frandom(-24,24),frandom(-24,24),frandom(1,359));
			}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}