class GWM_GoldenBouncer : GWM_WeaponBase 
{
	Default
	{
		//$Category Weapons
		//$Title "Bouncer Mk-II Phoenix"
		Weapon.SelectionOrder 2800;
		Weapon.SlotNumber 5;
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "GWM_RocketAmmo";
		Tag "$TAG_BOUNCER2";
		Inventory.PickupMessage "$GOTBOUNCER2";
		Obituary "$KILLBOUNCER2";
		GWM_WeaponBase.BaseVersion "GWM_Bouncer";
		GWM_WeaponBase.BaseVersion2 "GWM_GrenadeLauncher";
		
	}
	States
	{
		Ready:
			GNCL A 1 A_WeaponReady;
			Loop;
		Deselect:
			GNCL A 1 A_Lower(18);
			Loop;
		Select:
			GNCL A 1 A_Raise(18);
			Loop;
		Fire:
			TNT1 A 0 {let player = GWM_Player(player.mo);}
			GNCL A 2 {
				A_OverlayPivot(OverlayID(), 0.6125, 1);
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("GWM_MuzzleFlashLight2");
				A_WeaponOffset(0, 24, WOF_ADD);
				A_StartSound("weapons/bounf1", CHAN_WEAPON);
				A_FireProjectile("GWM_GoldBouncerShot", 0, true);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			GNCL AA 2 A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			TNT1 A 0
			{
				let player = GWM_Player(player.mo); 
				player.PW_FiringGrenade = true; //boolean instead of token.
			}
			GNCL A 3;
			GNCL AAA 3 {
				A_WeaponOffset(0, -8, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.11, 0, WOF_ADD);
			}
			TNT1 A 0 A_OverlayScale(OverlayID(), 1, 0);
			TNT1 A 0 A_ReFire;
			Goto Ready;
		Flash:
			GNCF ABC 2 Bright {
				A_Light1();
				A_OverlayPivot(OverlayID(), 0.6125, 1);
				A_OverlayScale(OverlayID(), 0.11, 0, WOF_ADD);
			}
			GNCF DE 3 Bright A_Light2;
			Stop;
		Spawn:
			GNCL Z -1;
			Stop;
	}
}

class GWM_GoldBouncerShot : Actor
{
	bool missed;
	int timer;
	int flicker;
	
	int blastradius;
	int blastradius2;
	int blastradius3;
	int blastspeed;
	
	action State GrenadeTimerJump()
	{
		
		if (invoker.flicker == 0) 
		{
			A_Setscale(1,1);
			invoker.flicker = 1;
		}
		else
		{
			A_Setscale(-1.5,-1.5);
			invoker.flicker = 0;
		}
		
		A_SpawnItemEx("GWM_GoldBouncerTrail");
		if (invoker.timer < 81) {
			if (!invoker.missed) {
				return ResolveState(null);
			}
			else invoker.timer++;
		}
		if (invoker.timer >= 81) {
			return ResolveState("Death");
		}
		return State(null);
	}
	Default
	{
		Radius 8;
		Height 8;
		Speed 20;
		DamageFunction (125);
		Projectile;
		-NOGRAVITY
		+RANDOMIZE
		+USEBOUNCESTATE
		+THRUGHOST
		BounceType "Hexen";
		Gravity 0.25;
		Scale 2;
		SeeSound "";
		DeathSound "weapons/explode";
		BounceSound "weapons/grndimp";
		Obituary "$KILLBOUNCER2";
		DamageType "Rocket";
		Renderstyle "Add";
	}
	int charge;
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{	
				let gren = GWM_Grenade(self);
				let player = GWM_Player(target);
				if(gren)
				{
					gren.charge = player.chargedGrenades;
				}
			}
		Spawnloop:
			GONC B 1 Bright 
			{
				GrenadeTimerJump();
			}
			GONC B 1 Bright GrenadeTimerJump;
			goto Spawnloop;
		Bounce:
			TNT1 A 0 {GrenadeTimerJump();}
			TNT1 A 0 {invoker.missed = true;}
			Goto Spawnloop;
		Bounce.Actor:
		Death:
			TNT1 A 0 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				A_Setscale(3,3);
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(180,200+15*invoker.charge);
			}
		TNT1 A 0 A_StartSound("weapons/goldboom",CHAN_AUTO);
		GONC CDEFGH 1 bright;
		TNT1 A 0 A_SpawnItemEX("ShakeItBaby",0,0,5);
		TNT1 AAAAA 1
		{
		blastradius = 95+15*invoker.charge;
		blastradius2 = blastradius * 0.5;
		blastradius3 = blastradius * 0.25;
		blastspeed = 4+1*invoker.charge;
		for (int i = 4; i > 0; i--)
		{
		A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
		A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
		A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius3,blastradius3),frandom(-blastradius3,blastradius3),frandom(-blastradius3,blastradius3),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
		}
		
		A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
		
		if(invoker.charge>0)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>1)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>2)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>3)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
			
		if(invoker.charge>4)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
			
		if(invoker.charge>5)
			{
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			A_SpawnItemEX("GWM_GoldBouncerMini",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-8,8),frandom(-8,8),frandom(3,8),frandom(1,359));
			}
		
		if(invoker.charge>3)
			{
			A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			}
			
		if(invoker.charge>5)
			{
			A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			A_SpawnItemEX("BlueBlastFlameFX2",frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastradius,blastradius),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(-blastspeed,blastspeed),frandom(1,359));
			}
		}
			//EXPL ABCDEFGHIJ 1 Bright;
			Stop;
	}
}

class GWM_GoldBouncerMini : GWM_GoldBouncerShot
{
	
	Default
	{
		Radius 8;
		Height 8;
		Speed 30;
		DamageFunction (50);
		Projectile;
		-NOGRAVITY
		+RANDOMIZE
		+USEBOUNCESTATE
		+THRUGHOST
		BounceType "Hexen";
		Gravity 0.40;
		SeeSound "";
		Scale 1.25;
		DeathSound "weapons/bounx2";
		BounceSound "weapons/bounb2";
		Obituary "$KILLBOUNCE2";
		DamageType "Rocket";
		RenderStyle "Normal";
		Reactiontime 100;
		+SEEKERMISSILE;
		+SCREENSEEKER;
	}
	States
	{
		Spawn:
			GONC A 1 Bright {
				A_Countdown();
				A_SpawnItemEx("GWM_GoldBouncerTrailMini");
			}
			GONC AAAA 1 Bright A_SpawnItemEx("GWM_GoldBouncerTrailMini");
			Loop;
		Bounce:
			TNT1 A 0 A_Countdown();
			GONC AA 1 A_SeekerMissile(360,360,SMF_LOOK);
			TNT1 A 0 A_CheckCeiling("BounceDown");
			
			TNT1 A 0 
			{
			A_Changevelocity(9,0,8,CVF_REPLACE|CVF_RELATIVE);
			A_Startsound("weapons/bounb2");
			}
			
			Goto Spawn;
		BounceDown:	
			TNT1 A 0 
			{
			A_Changevelocity(9,0,-10,CVF_REPLACE|CVF_RELATIVE);
			A_Startsound("weapons/bounb2");
			}
			goto Spawn;
		
		Bounce.Actor:
		Death:
			TNT1 AAAA 7 {
				bMISSILE = false;
				bNOGRAVITY = true;
				self.Vel.X = 0;
				self.Vel.Y = 0;
				self.Vel.Z = 0;
				
				A_SpawnItemEX("BlueBlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-1,1),frandom(-1,1),frandom(-1,1),frandom(1,359));
				A_SpawnItemEX("BlueBlastFlameFX",frandom(-15,15),frandom(-15,15),frandom(2,45),frandom(-1,1),frandom(-1,1),frandom(-1,1),frandom(1,359));
				
				A_Scream();
				A_SetRenderstyle(alpha, STYLE_Add);
				A_Explode(30,45);
				A_QuakeEx(3, 3, 3, 10, 0, 512, flags: QF_SHAKEONLY);
			}
			Stop;
	}
}

Class BlueBlastFlameFX : Actor
{
	Default
	{
		Scale 1.45;
		RenderStyle "Add";
		+NoInteraction
		+ForceXYBillboard
	}

	States
	{
	Spawn:
		XBIR ACEGIKMOQ 1 bright;
		stop;
	}
}

Class BlueBlastFlameFX2 : Actor
{
	Default
	{
		Scale 1.75;
		RenderStyle "Add";
		+NoInteraction
		+ForceXYBillboard
	}

	States
	{
	Spawn:
		ZBIR ABCDEGHIJKLMNOP 1 bright;
		stop;
	}
}

class GWM_GoldBouncerTrail : Actor
{
	Default
	{
		+NOTELEPORT;
		+NOINTERACTION;
		Renderstyle "Add";
		Scale 1.5;
		Alpha 1;
	}
	States
	{
		Spawn:
			
		Spawnloop:
			GNDE K 3 Bright A_Fadeout(0.075);
			loop;
	}
}

class GWM_GoldBouncerTrailMini : GWM_GoldBouncerTrail
{
	Default
	{
		Scale 0.7;
		Alpha 0.8;
	}
	States
	{
		Spawn:
			
		Spawnloop:
			GNDE K 3 Bright A_Fadeout(0.075);
			loop;
	}
}