class GWM_VenomCannon : DoomWeapon
{
	Default
	{
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "GWM_VenomVial";
		Weapon.AmmoType2 "GWM_VenomVial";
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "You got the Venom Cannon!";
		Tag "Venom Cannon";
	}
	States
	{
		Ready:
			VNMG A 1 A_WeaponReady;
			Loop;
		Deselect:
			VNMG A 1 A_Lower;
			VNMG A 0 A_Lower;
			Loop;
		Select:
			VNMG A 1 A_Raise;
			VNMG A 0 A_Raise;
			Loop;
		Fire:
			VNMG B 4 A_Overlay(-2, "Flash");
			VNMG C 6 {
				A_FireProjectile("GWM_VenomBall", 0, true, 0, 0, 0);
				A_StartSound("weapons/vnmcfire", CHAN_WEAPON);
			}
			VNMG BA 2;
			TNT1 A 0 A_ReFire;
			Goto Ready;
		AltFire:
			VNMG B 4 A_Overlay(-2, "Flash");
			VNMG C 6 {
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, true, 0, 10);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 5, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", -5, false, 0, 0);
				A_FireProjectile("GWM_SmallVenomBall_Shotgun", 0, false, 0, -10);
				A_StartSound("weapons/vnmcfire", CHAN_WEAPON);
			}
			VNMG BA 2;
			TNT1 A 0 A_ReFire;
			Goto Ready;
		Flash:
			VNMF ABCDE 2;
			Stop;
		Spawn:
			VNMG Z -1;
			Stop;
	}
}