// Baron of Hell =============================
class GWM_BaronOfHell : BaronOfHell
{
	Default
	{
		//$Category Monsters
		//$Title "Baron of Hell
		Tag "$TAG_BARON";
		BloodColor "93 2F 00";
	}
	States
	{
		Spawn:
			BARN AB 10 A_Look;
			Loop;
		See:
			BARN AABBCCDD 3 A_Chase;
			Loop;
		Melee:
		Missile:
			BARN EF 8 A_FaceTarget;
			BARN G 8 A_CustomComboAttack("GWM_BaronBall", 32, 45, "baron/melee");
			Goto See;
		Pain:
			BARN H 2;
			BARN H 2 A_Pain;
			Goto See;
		Death:
			BARN I 8;
			BARN J 8 A_Scream;
			BARN K 8;
			BARN L 8 A_NoBlocking;
			BARN MN 8;
			BARN O -1 A_BossDeath;
			Stop;
		XDeath:
			BARN P 5;
			BARN Q 5 A_XScream;
			BARN R 5 A_NoBlocking;
			BARN STUVW 5;
			BARN X -1 A_BossDeath;
			Stop;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			BARN P 5;
			BARN Q 5 A_StartSound("monsters/burndeath");
			BARN R 5 A_NoBlocking;
			BARN STUVW 5;
			BARN X -1 A_BossDeath;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			BARN O 8;
			BARN NMLKJI 8;
			Goto See;
	}
}
class GWM_BaronBall : BaronBall
{
	Default
	{
		DamageFunction 36;
	}
	States
	{
		Spawn:
			BARB AB 4 Bright;
			Loop;
		Death:
			BARB CDE 6 Bright;
			Stop;
	}
}

// Annihilator ===============================
class GWM_Annihilator : Actor
{
	Default
	{
		Health 1100;
		Speed 10;
		Radius 24;
		Height 64;
		ReactionTime 8;
		PainChance 20;
		Mass 1000;
		Monster;
		+FLOORCLIP
		+BOSSDEATH
		SeeSound "monsters/annihilator/sight";
		PainSound "monsters/annihilator/pain";
		DeathSound "monsters/annihilator/death";
		ActiveSound "monsters/annihilator/active";
		Obituary "$OB_ANNIHILATOR";
		Tag "$TAG_ANNIHILATOR";
		DropItem "GWM_RocketAmmo";
		DropItem "GWM_RocketAmmo";
		DropItem "GWM_Cell";
	}
	States
	{
		Spawn:
			ANNI AB 10 A_Look;
			Loop;
		See:
			ANNI AA 3 A_Chase;
			ANNI B 0 A_StartSound("monsters/annihilator/step");
			ANNI BBCC 3 A_Chase;
			ANNI D 0 A_StartSound("monsters/annihilator/step");
			ANNI DD 3 A_Chase;
			Loop;
		Pain:
			ANNI J 3;
			ANNI J 3 A_Pain;
			Goto See;
		Missile:
			ANNI E 8 Bright A_FaceTarget;
			ANNI F 12 Bright A_SpawnProjectile("GWM_EnemyRocket",27,16,0);
			ANNI GS 10 A_FaceTarget;
			ANNI HIHIHIH 3 Bright A_SpawnProjectile("GWM_EnemyPlasma", 32, 0, 0); // "HighCaliberFast"
			ANNI S 10 A_FaceTarget;
			Goto See;
		Death:
			ANNI K 8;
			ANNI L 8 Bright A_Scream;
			ANNI M 8 Bright A_Fall;
			ANNI NOP 8 Bright;
			ANNI Q 8 Bright;
			ANNI R -1 A_BossDeath;
			Stop;
		Raise:
			ANNI QPONMLK 5;
			Goto See;
	}
}