class GWM_ChaingunGuy : ChaingunGuy
{
	int shotsfired;
	Default
	{
		//$Category Monsters
		//$Title "Mad Vulcan Zombie
		Tag "$TAG_CHAINGUNNER";
		Obituary "$OB_CHAINGUNNER";
		AttackSound "weapons/chainfire";
		DropItem "GWM_MiniGun",108;
		DropItem "GWM_FMJBelt",74;
		DropItem "GWM_FMJMagazine",84;
	}
	States
	{		
		Missile:
			CPOS E 18 A_FaceTarget;
		Shoot:
			CPOS F 2 Bright 
			{
				A_CustomBulletAttack(17.5, 8, 1, 6, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 26, spawnofs_xy: 7);
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-2,4),frandom(3,8),frandom(3,8));
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			CPOS E 2
			{
				invoker.shotsfired = invoker.shotsfired+1;
				//if (invoker.shotsfired > random(45,59))
				//{
				//SetStateLabel("StopFiring");
				//}
			}
			TNT1 A 0 A_Jumpif(target.health==0,"KeepFiring");
			TNT1 A 0 A_JumpIfinTargetLOS("Shoot");
		KeepFiring:
			CPOS F 2 Bright 
			{
				A_CustomBulletAttack(25.5, 10, 1, 6, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 26, spawnofs_xy: 7);
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-2,4),frandom(3,8),frandom(3,8));
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			CPOS E 2;
			CPOS E 1
			{
				if (invoker.shotsfired > 70) {invoker.shotsfired = invoker.shotsfired-2;}
				if (invoker.shotsfired > 30) {invoker.shotsfired = invoker.shotsfired-2;}
					
				invoker.shotsfired = invoker.shotsfired-5;
				
				if (invoker.shotsfired > 1)
					{
					SetStateLabel("KeepFiring");
					}
			}
		Stopfiring:
			CPOS E 10
			{
				invoker.shotsfired = 0;
				A_JumpIfinTargetLOS("Shoot");
			}
			Goto See;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			CPOS O 5;
			CPOS P 5 A_StartSound("monsters/burndeath");
			CPOS Q 5 A_NoBlocking;
			CPOS RS 5;
			CPOS T -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			Goto Super::Raise;
	}
}

class GWM_VulcanGuy : ChaingunGuy
{
	
	
	
	int shotsfired;
	Default
	{
		Health 125;
		Speed 12;
		//$Category Monsters
		//$Title "Mad Vulcan Zombie
		Tag "$TAG_VULCANGUY";
		Obituary "$OB_VULCANGUY";
		AttackSound "weapons/vulcanfire";
		DropItem "GWM_MadVulcan",36;
		DropItem "GWM_FMJBelt",220;
		
		SeeSound "monsters/vulcan/see";
		PainSound "monsters/vulcan/pain";
		DeathSound "monsters/vulcan/die";
		ActiveSound "monsters/vulcan/idle";
	}
	States
	{
		Spawn:
			MVPO AB 10 A_Look;
			Loop;
		See:
			MVPO AABBCCDD 3 A_Chase;
			Loop;
		Missile:
			MVPO E 25 A_FaceTarget;
		Shoot:
			MVPO F 2 Bright 
			{
				A_CustomBulletAttack(28.5, 15, 9, 3, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 26, spawnofs_xy: 7);
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			MVPO E 1
			{
				invoker.shotsfired = invoker.shotsfired+1;
				//if (invoker.shotsfired > random(45,59))
				//{
				//SetStateLabel("StopFiring");
				//}
			}
			TNT1 A 0 A_Jumpif(!target,"KeepFiring");
			TNT1 A 0 A_Jumpif(target.health==0,"KeepFiring");
			TNT1 A 0 A_JumpIfinTargetLOS("Shoot");
		KeepFiring:
			MVPO F 2 Bright 
			{
				A_CustomBulletAttack(33.5, 18, 10, 5, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 26, spawnofs_xy: 7);
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEX("GWM_RifleCasing",5,0,20,frandom(-4,6),frandom(3,15),frandom(3,12));
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			MVPO E 2;
			MVPO E 1
			{
				if (invoker.shotsfired > 70) {invoker.shotsfired = invoker.shotsfired-2;}
				if (invoker.shotsfired > 30) {invoker.shotsfired = invoker.shotsfired-2;}
					
				invoker.shotsfired = invoker.shotsfired-2;
				
				if (invoker.shotsfired > 1)
					{
					SetStateLabel("KeepFiring");
					}
			}
		Stopfiring:
			MVPO E 10
			{
				invoker.shotsfired = 0;
				A_JumpIfinTargetLOS("Shoot");
			}
			Goto See;
		Pain:
			MVPO G 3;
			MVPO G 3 A_Pain;
			Goto See;
		Death:
			MVPO H 5;
			MVPO I 5 A_Scream;
			MVPO J 5 A_NoBlocking;
			MVPO KLM 5;
			MVPO N -1;
			Stop;
		XDeath:
			MVPO O 5;
			MVPO P 5 A_XScream;
			MVPO Q 5 A_NoBlocking;
			MVPO RS 5;
			MVPO T -1;
			Stop;
		Raise:
			MVPO NMLKJIH 5;
			Goto See;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			MVPO O 5;
			MVPO P 5 A_StartSound("monsters/burndeath");
			MVPO Q 5 A_NoBlocking;
			MVPO RS 5;
			MVPO T -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			Goto Super::Raise;
	}
}

class GWM_HeavyRifleman : ChaingunGuy
{
	Default
	{
		//$Category Monsters
		//$Title "Heavy Rifleman
		Tag "$TAG_HEAVYRIFLEMAN";
		AttackSound "weapons/riflesht";
		Obituary "$OB_HEAVYRIFLEMAN";
		DropItem "GWM_BurstRifle", 100;
		DropItem "GWM_FMJMagazine", 100;
		DropItem "GWM_FMJBelt", 55;
		
		
	}
	States
	{
		Spawn:
			HEVY AB 10 A_Look;
			Loop;
		See:
			HEVY AABBCCDD 4 A_Chase;
			Loop;
		Missile:
			HEVY E 2 A_FaceTarget;
			HEVY F 1 Bright 
			{
				A_CustomBulletAttack(22.5, 0, 1, 9, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnofs_xy: 9);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			HEVY G 2 A_FaceTarget;
			HEVY F 1 Bright 
			{
				A_CustomBulletAttack(22.5, 0, 1, 9, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnofs_xy: 9);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			HEVY G 2 A_FaceTarget;
			HEVY F 1 Bright 
			{
				A_CustomBulletAttack(22.5, 0, 1, 9, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnofs_xy: 9);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,15);	
			}
			HEVY G 6; // nerfed and also matches actual burst rifle now
			HEVY E 3 A_CPosRefire;
			Goto Missile;
		Pain:
			HEVY H 3;
			HEVY H 3 A_Pain;
			Goto See;
		Death:
			HEVY I 5;
			HEVY J 5 A_Scream;
			HEVY K 5 A_NoBlocking;
			HEVY L 5;
			HEVY M 5;
			HEVY N -1;
			Stop;
		XDeath:
			HEVY O 5;
			HEVY P 5 A_XScream;
			HEVY Q 5 A_NoBlocking;
			HEVY RS 5;
			HEVY T -1;
			Stop;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			HEVY O 5;
			HEVY P 5 A_StartSound("monsters/burndeath");
			HEVY Q 5 A_NoBlocking;
			HEVY RS 5;
			HEVY T -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			HEVY M 5;
			HEVY LKJI 5;
			Goto See;
	}
}