class GWM_HellKnight : HellKnight
{
	Default
	{
		//$Category Monsters
		Tag "Hell Knight";
		BloodColor "30 67 23";
	}
	States
	{
		Spawn:
			HKNI AB 10 A_Look;
			Loop;
		See:
			HKNI AABBCCDD 3 A_Chase;
			Loop;
		Melee:
		Missile:
			HKNI EF 8 A_FaceTarget;
			HKNI G 8 A_CustomComboAttack("GWM_KnightBall", 32, 10 * random(1, 8), "baron/melee");
			Goto See;
		Pain:
			HKNI H 2;
			HKNI H 2 A_Pain;
			Goto See;
		Death:
			HKNI I 8;
			HKNI J 8 A_Scream;
			HKNI K 8;
			HKNI L 8 A_NoBlocking;
			HKNI MN 8;
			HKNI O -1;
			Stop;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			HKNI I 8;
			HKNI J 8 A_StartSound("monsters/burndeath");
			HKNI K 8;
			HKNI L 8 A_NoBlocking;
			HKNI MN 8;
			HKNI O -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			HKNI O 8;
			HKNI NMLKJI 8;
			Goto See;
	}
}
class GWM_KnightBall : BaronBall
{
	States
	{
		Spawn:
			HBAL AB 4 BRIGHT;
			Loop;
		Death:
			HBAL CDE 6 BRIGHT;
			Stop;
	}
}

class GWM_CyberHellKnight : GWM_HellKnight
{
	Default
	{
		Tag "Cyber Hell Knight";
		obituary "%o was splayed by a Cyber Hell Knight";
		hitobituary "%o was ripped to shreds by a Cyber Hell Knight";
		health 600;
		radius 24;
		height 64;
		mass 1000;
		speed 8;
		painchance 40;
		seesound "chknight/sight";
		painsound "chknight/pain";
		deathsound "chknight/death";
		activesound "chknight/active";
		+NORADIUSDMG
	}
	States
	{
		Spawn:
			CBO2 AB 10 A_Look;
			loop;
		See:
			CBO2 A 3 A_chase;
			CBO2 A 3 A_chase;
			CBO2 B 0 A_StartSound("cbaron/metal");
			CBO2 BB 3 A_chase;
			CBO2 CC 3 A_chase;
			CBO2 D 3 A_chase;
			CBO2 D 3 A_hoof;
			loop;
		Melee:
			CBO2 PQ 8 A_FaceTarget;
			CBO2 R 8 A_BruisAttack;
			Goto See;
		Missile:
			CBO2 E 0 A_jump(80,5);
			CBO2 E 10 A_FaceTarget;
			CBO2 E 10 A_FaceTarget;
			CBO2 F 10 Bright A_SpawnProjectile("Rocket",27,16,0);
			CBO2 E 10 A_FaceTarget;
			goto See;
			CBO2 PQ 8 A_FaceTarget;
			CBO2 R 8 A_CustomComboAttack("GWM_KnightBall", 32, 10 * random(1, 8), "baron/melee");
			Goto See;
		Pain:
			CBO2 H 2;
			CBO2 H 2 A_Pain;
			goto See;
		Death:
			CBO2 I 8;
			CBO2 J 8 A_Scream;
			CBO2 K 8 bright A_StartSound("world/barrelx");
			CBO2 L 8 bright A_NoBlocking;
			CBO2 M 8 bright;
			CBO2 N 8 bright;
			CBO2 O -1;
			stop;
	}
}