class GWM_NightmareImp : DoomImp
{
	Default
	{
		PainChance 128;
		Speed 16;
		RenderStyle "Translucent";
		Translation "GWM_NightmareImp";
		Alpha 0.7;
		BloodColor "78 58 80";
		Obituary "$OB_NIGHTMAREIMPSCRATCH";
	}
	States
	{
		Melee:
		Missile:
			TROO EF 8 A_FaceTarget;
			TROO G 6 A_CustomComboAttack("GWM_NightmareImpBall", 32, 3 * random(1, 8), "imp/melee");
			Goto See;
	}
}

class GWM_NightmareImpBall : DoomImpBall
{
	Default
	{
		Translation "GWM_NightmareImp";
		Speed 20;
		FastSpeed 40;
		Obituary "$OB_NIGHTMAREIMPFIRE";
	}
}