class GWM_LostSoulSpawner : RandomSpawner
{
	override void BeginPlay()
	{
		if (self.curSector.lightlevel <= 112 && random(0,2) == 2)
		{
			Spawn("GWM_Blot", self.Pos);
			self.Destroy();
		}
		else Super.BeginPlay();
	}
	Default
	{
		DropItem "GWM_LostSoul";
	}
}

class GWM_LostSoul : LostSoul // to prevent recursion, i guess
{
	Default
	{
		//$Category Monsters
		//$Title "Lost Soul
		+NOBLOOD
		Tag "$TAG_LOSTSOUL";
		DamageFunction (14);
	}
}

class GWM_BlotSmoke : Actor
{
	Default
	{
		+NOINTERACTION
		+CLIENTSIDEONLY
		RenderStyle "Translucent";
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_Jump(256, "Blot1", "Blot2", "Blot3", "Blot4");
		Blot1:
			BLOT A 2;
			BLOT BCDE 2 A_FadeOut(0.2);
			Stop;
		Blot2:
			BLOT F 2;
			BLOT GHIJ 2 A_FadeOut(0.2);
			Stop;
		Blot3:
			BLOT K 2;
			BLOT LMNO 2 A_FadeOut(0.2);
			Stop;
		Blot4:
			BLOT P 2;
			BLOT QRST 2 A_FadeOut(0.2);
			Stop;
	}
}
class GWM_Blot : Actor
{
	Default
	{
		//$Category Monsters
		//$Angled
		//$Sprite BLOPA0
		//$Title "Blot
		Tag "$TAG_BLOT";
		Obituary "$OB_BLOT";
		Health 20;
		Radius 8;
		Height 16;
		Mass 50;
		Speed 0;
		Deathsound "monsters/blot/death";
		DamageFactor "Blot", 0;
		BloodType "None";
		Scale 0.6;

		MONSTER;
		-SOLID
		-CANPASS
		+STANDSTILL
		+MISSILEMORE
		+MISSILEEVENMORE
		+DONTHARMCLASS
		+NODAMAGETHRUST
		+BLOODLESSIMPACT
		+LOWGRAVITY
		+BRIGHT
		+NOEXTREMEDEATH
	}
	States
	{
		Spawn:
			EYES A 10 A_Look;
			Loop;
		IdleSpawn:
			EYES A 1 A_LookEx(LOF_NOSEESOUND, 0, 0, 0, 360);
			EYES AAA 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			Loop;
		See:
			EYES A 1 A_Chase;
			EYES AAA 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			Loop;
		Missile:
			EYES A 0 A_CheckSight("IdleSpawn");
		LeapSight:
			EYES B 1 A_FaceTarget;
			EYES BBB 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			EYES B 1 ThrustThingZ(0, 13, 0, 0);
			EYES BBB 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			TNT1 B 0 ThrustThing(angle*256/360, 8, 0, 0);
			TNT1 B 0 A_StartSound("monsters/blot/attack");
		MidLeap:
			EYES B 1 A_SpawnItem("GWM_BlotDamage");
			EYES BBB 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			TNT1 B 0 A_JumpIf(Vel.Z < 0, "Falling");
			Loop;
		Falling:
			EYES A 1 A_SpawnItem("GWM_BlotDamage");
			EYES AAA 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			TNT1 A 0 A_CheckFloor("Land");
			Loop;
		Land:
			EYES A 1 A_Stop;
			EYES AAA 0 A_SpawnItemEx("GWM_BlotSmoke", -4, random(-10, 10), random(-10, 10), 0, random(-1, 1), random(-1, 1));
			EYES A 0 A_ClearTarget;
			Goto IdleSpawn;
		Death:
			TNT1 A 1 A_Stop;
			TNT1 A 0 A_ScreamAndUnblock;
			TNT1 AAAAAAAA 1 A_SpawnItemEx("GWM_BlotSmoke", 0, 0, 0, random(-4, 4), 0, random(-4, 4), random(0, 360));
			Stop;
	}
}
class GWM_BlotDamage : Actor
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 0;
		DamageType "Blot";
		Projectile;
		+NODAMAGETHRUST
		+BLOODLESSIMPACT
	}
	States
	{
		Spawn:
			TNT1 A 1 NoDelay A_Explode(1, 40, 0);
			Stop;
	}
}

class GWM_ChillerSoul : Actor
{
	Default
	{
		//$Category Monsters
		//$Title "Chiller Soul
		Tag "$TAG_CHILLERSOUL";
		Health 100;
		Radius 16;
		Height 56;
		Mass 50;
		Speed 4;
		Scale 1.2;
		DamageFunction (23);
		PainChance 128;
		Monster;
		+Float
		+NoGravity
		+MissileEvenMore
		+DontFall
		+NoIceDeath
//		+DontHurtSpecies
		BloodColor "61A5D3";
		DamageType "Ice";
		DamageFactor "Ice", 0.0;
		AttackSound "";
		PainSound "ChillerSoul/Pain";
		DeathSound "ChillerSoul/Death";
		ActiveSound "ChillerSoul/Active";
		Obituary "%o was frozen solid by a Chiller Soul.";
		MaxTargetRange 2560;
	}
	States
	{
		Spawn:
			CHSL A 1 {
				A_Look();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			Loop;
		See:
			CHSL A 1 {
				A_Chase();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			CHSL AA 1 {
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			Loop;
		Missile:
			CHSL A 0 A_JumpIfCloser(512,"Charge");
		Missile.FaceTarget:
			CHSL AAAA 1 BRIGHT {
				A_FaceTarget();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
		Missile.Shoot:
			CHSL B 1 BRIGHT {
				A_SpawnProjectile("GWM_ChillerSoulBall", 6);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			CHSL BBB 1 BRIGHT {
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			Goto See;
		Charge:
			CHSL AA 5 Bright A_FaceTarget;
			CHSL B 1 Bright {
				A_PlaySound("ChillerSoul/Attack");
				A_SkullAttack();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
		KeepCharging:
			CHSL BBB 1 Bright {
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			CHSL B 0 Bright A_JumpIfTargetInLOS("HomeIn", 80);
			CHSL B 0 A_Jump(24, "StopCharging");
			CHSL B 4 Bright;
			Goto Missile.Shoot;
		HomeIn:
			CHSL BBBB 1 BRIGHT {
				A_FaceTarget();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			Goto KeepCharging;
		StopCharging:
			CHSL A 0 A_Stop;
			Goto See;
		Pain:
			CHSL BBB 1 Bright {
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			CHSL B 1 Bright {
				A_Pain();
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			CHSL BB 1 Bright {
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
				A_SpawnItemEx("GWM_ChillerSoulFrost", random(-3,-13), random(10,-10), random(8, 25), 0, 0, 0.1*Random(5, 20), 0, 160, 0);
			}
			Goto See;
		Death:
			CHSL A 6 {
				A_Scream();
				A_IceGuyDie();
			}
			Stop;
	}
}
class GWM_ChillerSoulFrost : Actor
{
	Default
	{
		Radius 6;
		Height 8;
		Speed 1;
		DamageFunction (0);
		RenderStyle "Translucent";
		Alpha 0.3;
		Scale 0.4;
		+NoBlockMap
		+NoGravity
		+Missile
		+NoTeleport
		+DontSplash
	}
	States
	{
		Spawn:
			FRST ABCDEFGHIJKLMNO 1 A_FadeOut(0.03);
			Stop;
	}
}
class GWM_ChillerSoulBall : Actor
{
	Default
	{
		Radius 4;
		Height 6;
		Speed 15;
		DamageFunction (23);
		Scale 0.5;
		Decal "MummyScorch";
//		Decal "RevenantScorch"
		Renderstyle "Add";
		Alpha 0.65;
		DamageType "Ice";
		Seesound "ChillerSoul/Ball";
		Deathsound "ChillerSoul/BallDie";
		Projectile;
		+Randomize
	}
	States
	{
		Spawn:
			RCBL A 0 Bright A_BishopMissileWeave;
			RCBL AA 1 Bright A_SpawnItemEx("GWM_ChillerSoulTrail", 0, Random(2,-2), Random(2,-2), 0, 0, 0, 0, 160);
			RCBL A 0 Bright A_BishopMissileWeave;
			RCBL AB 1 Bright A_SpawnItemEx("GWM_ChillerSoulTrail", 0, Random(2,-2), Random(2,-2), 0, 0, 0, 0, 160);
			RCBL B 0 Bright A_BishopMissileWeave;
			RCBL BB 1 Bright A_SpawnItemEx("GWM_ChillerSoulTrail", 0, Random(2,-2), Random(2,-2), 0, 0, 0, 0, 160);
			Loop;
		Death:
			RCBL J 4 Bright A_Explode(2,16,1);
			RCBL JJJJJ 0 Bright A_SpawnItemEx("GWM_ChillerSoulTrail", 0, 0, 0, 2, 0, Random(1,-1), Random(0,360), 128, 0);
			RCBL KLMN 4 Bright;
			Stop;
	}
}
class GWM_ChillerSoulTrail : Actor
{
	Default
	{
		Radius 3;
		Height 3;
		RenderStyle "Add";
		Alpha 0.65;
		Scale 0.55;
		+NoGravity
		+NoBlockMap
		+DontSplash
		+ForceXYBillboard
	}
	States
	{
		Spawn:
			TNT1 A 2;
			RCBL CDEFGHI 2 Bright;
			Stop;
	}
}