class GWM_Revenant : Revenant
{
	States
	{
		Melee:
			SKEL G 0 A_FaceTarget;
			SKEL G 6 A_SkelWhoosh;
			SKEL H 6 A_FaceTarget;
			SKEL I 6 A_CustomMeleeAttack(33, "skeleton/melee");
			Goto See;
		Missile:
			SKEL J 0 Bright A_FaceTarget;
			SKEL J 10 Bright A_FaceTarget;
			SKEL K 10 A_SpawnProjectile("GWM_RevenantTracer", 40); // change this later mayhaps
			SKEL K 10 A_FaceTarget;
			Goto See;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			SKEL LM 7;
			SKEL N 7 A_StartSound("monsters/burndeath");
			SKEL O 7 A_NoBlocking;
			SKEL P 7;
			SKEL Q -1;
			Stop;
	}
}
class GWM_RevenantTracer : RevenantTracer
{
	Default
	{
		DamageFunction (45);
	}
	States
	{
		Death:
			TNT1 A 0 A_QuakeEx(1, 1, 1, 10, 0, 512, flags: QF_SHAKEONLY);
			Goto Super::Death;
	}
}