class GWM_Zombieman : Zombieman
{
	int shotsfired;
	Default
	{
		//$Category Monsters
		Tag "$TAG_ZOMBIEMAN";
		DropItem "GWM_LowCaliberMagazine";
		AttackSound "weapons/92fsfire";
	}
	States
	{
		Spawn:
			PZOM AB 10 A_Look;
			Loop;
		See:
			PZOM AABBCCDD 4 A_Chase;
			Loop;
		Missile:
			PZOM E 10 A_FaceTarget;
		Shoot:
			PZOM F 4 Bright 
			{
			A_CustomBulletAttack(20.5, 8, 1, 9, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 46, spawnofs_xy: 0);
			A_SpawnItemEX("GWM_PistolCasing",5,0,20,frandom(-2,4),frandom(3,8),frandom(3,8));
			A_SpawnItemEx("GWM_MuzzleFlashLight",0,0,15);	
			}
			PZOM E 8
			{
			invoker.shotsfired = invoker.shotsfired+1;
			
				if (invoker.shotsfired > random(3,9))
				{
				SetStateLabel("StopFiring");
				}
			}
			TNT1 A 0 A_JumpIfinTargetLOS("Shoot");
			
			StopFiring:
			PZOM E 10
			{
				invoker.shotsfired = 0;
			}
			Goto See;
			
		Pain:
			PZOM G 3;
			PZOM G 3 A_Pain;
			Goto See;
		Death:
			TNT1 A 0 A_Jump(120,"Death2");
			PZOM H 5;
			PZOM I 5 A_Scream;
			PZOM J 5 A_NoBlocking;
			PZOM K 5;
			PZOM L -1;
			Stop;
		Death2:
			PZOM V 5;
			PZOM W 5 A_Scream;
			PZOM X 5 A_NoBlocking;
			PZOM YZ 5;
			PZOM [ -1;
			Stop;
		XDeath:
			PZOM M 5;
			PZOM N 5 A_XScream;
			PZOM O 5 A_NoBlocking;
			PZOM PQRST 5;
			PZOM U -1;
			Stop;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			PZOM M 5;
			PZOM N 5 A_StartSound("monsters/burndeath");
			PZOM O 5 A_NoBlocking;
			PZOM PQRST 5;
			PZOM U -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			PZOM KJIH 5;
			Goto See;
	}
}

class GWM_SMGGuy : Actor
{
	int shotsfired;
	Default
	{
		//$Category Monsters
		Tag "$TAG_SMGGUY";
		Health 40;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 150;
		SeeSound "grunt/sight";
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		ActiveSound "grunt/active";
		AttackSound "weapons/smgfire";
		Obituary "$OB_SMGGUY";
		DropItem "GWM_SMG";
		Monster;
		+FLOORCLIP
	}
	States
	{
		Spawn:
			MGPO AB 10 A_Look;
			Loop;
		See:
			MGPO AABBCCDD 4 A_Chase;
			Loop;
		Missile:
			MGPO E 8 A_FaceTarget();
		Shoot:
			MGPO F 2 Bright 
			{
			A_CustomBulletAttack(12, 12, 1, 9, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			A_SpawnItemEX("GWM_PistolCasing",5,0,20,frandom(-2,4),frandom(3,8),frandom(3,8));
			A_SpawnItemEx("GWM_MuzzleFlashLight",0,0,15);	
			}
			MGPO E 2
			{
			invoker.shotsfired = invoker.shotsfired+1;
			A_FaceTarget();
				if (invoker.shotsfired > random(15,20))
				{
				SetStateLabel("StopFiring");
				}
			}
			TNT1 A 0 A_JumpIfinTargetLOS("Shoot");
			
			StopFiring:
			MGPO E 10
			{
				invoker.shotsfired = 0;
			}
			Goto See;
		Pain:
			MGPO G 3;
			MGPO G 3 A_Pain;
			Goto See;
		Death:
			MGPO H 5;
			MGPO I 5 A_Scream;
			MGPO J 5 A_NoBlocking;
			MGPO K 5;
			MGPO L -1;
			Stop;
		XDeath:
			MGPO M 5;
			MGPO N 5 A_XScream;
			MGPO O 5 A_NoBlocking;
			MGPO PQRST 5;
			MGPO U -1;
			Stop;
		Death.Fire:
			TNT1 A 0 {
				bNOBLOOD = true;
				A_SetTranslation("GWM_Burnt");
			}
			MGPO M 5;
			MGPO N 5 A_XScream;
			MGPO O 5 A_NoBlocking;
			MGPO PQRST 5;
			MGPO U -1;
			Stop;
		Raise:
			TNT1 A 0 {bNOBLOOD = false;}
			MGPO KJIH 5;
			Goto See;
	}
}