class GWM_Zombieman : Zombieman
{
	Default
	{
		AttackSound "weapons/92fsfire";
	}
	States
	{
		Spawn:
			PZOM AB 10 A_Look;
			Loop;
		See:
			PZOM AABBCCDD 4 A_Chase;
			Loop;
		Missile:
			PZOM E 10 A_FaceTarget;
			PZOM F 8 Bright A_CustomBulletAttack(22.5, 0, 1, random(1,5)*3, "ZBulletPuff", 0, CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 46, spawnofs_xy: 0);
			PZOM E 8;
			Goto See;
		Pain:
			PZOM G 3;
			PZOM G 3 A_Pain;
			Goto See;
		Death:
			PZOM H 5;
			PZOM I 5 A_Scream;
			PZOM J 5 A_NoBlocking;
			PZOM K 5;
			PZOM L -1;
			Stop;
		XDeath:
			PZOM M 5;
			PZOM N 5 A_XScream;
			PZOM O 5 A_NoBlocking;
			PZOM PQRST 5;
			PZOM U -1;
			Stop;
		Raise:
			PZOM K 5;
			PZOM JIH 5;
			Goto See;
	}
}

class GWM_SMGGuy : Actor
{
	Default
	{
		Health 40;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 150;
		SeeSound "grunt/sight";
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		ActiveSound "grunt/active";
		AttackSound "weapons/smgfire";
		Obituary "$OB_SMGGUY";
		DropItem "GWM_SMG";
		Monster;
		+FLOORCLIP
	}
	States
	{
		Spawn:
			MGPO AB 10 A_Look();
			Loop;
		See:
			MGPO AABBCCDD 4 A_Chase();
			Loop;
		Missile:
			MGPO E 8 A_FaceTarget();
			MGPO F 3 BRIGHT A_CustomBulletAttack(12,0,1,random(1,5)* 3,"ZBulletPuff",0,CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			MGPO E 3;
			MGPO F 3 BRIGHT A_CustomBulletAttack(12,0,1,random(1,5)* 3,"ZBulletPuff",0,CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			MGPO E 3;
			MGPO F 3 BRIGHT A_CustomBulletAttack(12,0,1,random(1,5)* 3,"ZBulletPuff",0,CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			MGPO E 3;
			MGPO F 3 BRIGHT A_CustomBulletAttack(12,0,1,random(1,5)* 3,"ZBulletPuff",0,CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			MGPO E 3;
			MGPO F 3 BRIGHT A_CustomBulletAttack(12,0,1,random(1,5)* 3,"ZBulletPuff",0,CBAF_NORANDOM, missile: "GWM_Tracer", spawnheight: 34, spawnofs_xy: 11);
			MGPO E 10;
			Goto See;
		Pain:
			MGPO G 3;
			MGPO G 3 A_Pain();
			Goto See;
		Death:
			MGPO H 5;
			MGPO I 5 A_Scream();
			MGPO J 5 A_NoBlocking();
			MGPO K 5;
			MGPO L -1;
			Stop;
		XDeath:
			MGPO M 5;
			MGPO N 5 A_XScream();
			MGPO O 5 A_NoBlocking();
			MGPO PQRST 5;
			MGPO U -1;
			Stop;
	}
}