class GWM_Impactor : GWM_WeaponBase // not that it needs to be this way...
{
	Default
	{
		//$Category Weapons
		//$Title "Impactor Gauntlet
		Weapon.SelectionOrder 2200;
		+WEAPON.MELEEWEAPON
		Tag "$TAG_IMPACTOR";
		Inventory.Icon "IMPAZ0";
		Weapon.UpSound "weapons/IMGRaise";
		Inventory.PickupMessage "$GOTIMPACTOR";
		Obituary "$KILLIMPACTOR";
	}
	States
	{
		Spawn:
			IMPA Z -1;
			Stop;
		Select:
			IMPA A 1 A_Raise(18);
			Loop;
		Deselect:
			IMPA A 1 A_Lower(18);
			Loop;
		Ready:
			IMPA A 1 A_WeaponReady;
			Loop;
		Fire:
			IMPA AB 2;
			TNT1 A 0 A_PlaySound("weapons/IMGCok");
			IMPA CDE 2;
			TNT1 A 5;
			Goto Hold;
		Hold:
			TNT1 A 1;
			TNT1 A 0 A_ReFire;
			IMPA FGHI 1;
			TNT1 A 0 A_CustomPunch (325,1,CPF_NOTURN ,"ImpactorPuff",92, 0, 0, "ArmorBonus", "weapons/IMGHit", "weapons/IMGMiss");
			TNT1 A 0 A_Blast(BF_DONTWARN | BF_NOIMPACTDAMAGE | BF_AFFECTBOSSES, 25, 60, 20, "GauntletImpact");
			TNT1 A 0 A_Quake(3, 10, 0, 10);
			IMPA JKLMN 1;
			IMPA N 5;
			IMPA OPQRS 3;
			TNT1 A 5;
			IMPA EDCBA 2;
			Goto Ready;
		AltFire:
			IMPA AB 2;
			TNT1 A 0 A_PlaySound("weapons/IMGCok");
			IMPA CDE 2;
			TNT1 A 5;
			Goto AltHold;
		AltHold:
			TNT1 A 1;
			TNT1 A 0 A_ReFire;
			IMPA FGHI 1;
			TNT1 A 0 ThrustThing(angle * 256 / 360, 30, 1, 0);
			TNT1 A 0 A_PlaySound("weapons/IMGThrust");
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA J 1 {A_CustomPunch (16,1,CPF_NOTURN ,"ZBulletPuff",92,1, 5); A_SpawnItemEx("ImpactorDash", xofs: 32, zofs: 32);}
			IMPA OPQRS 2;
			TNT1 A 5;
			IMPA EDCBA 2;
			Goto Ready;
	}
}

class ImpactorPuff : BulletPuff
{
	Default
	{
		+PUFFONACTORS +WALLSPRITE -NOCLIP
		Scale 0.1;
		Alpha 1;
		RenderStyle "Add";
	}
	States
	{
		Melee:
			IMPA Y 1 {
				A_SetScale(0.1);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.2);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.3);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.4);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.5);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.6);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.7);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.8);
				A_FadeOut(0.1);
			}
			IMPA Y 1 {
				A_SetScale(0.9);
				A_FadeOut(0.1);
			}
			Stop;
	}
}
class ImpactorDash : ImpactorPuff
{
	Default
	{
		+NOCLIP
	}
	States
	{
		Spawn:
			Goto Melee;
	}
}

class GauntletImpact : BlastEffect
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+NOCLIP
		+NOTELEPORT
	}
	States
	{
		Spawn:
			TNT1 A 0;
			Stop;
	}
}