class GWM_HollowPointMagazine : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Hollow Point Magazine
		Inventory.PickupMessage "$GOTHOLLOWPOINTMAG";
		Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Inventory.Icon "MAGZA0";
		Inventory.PickupSound "pickups/magazine";
	}
	States
	{
		Spawn:
			MAGZ A -1;
			Stop;
	}
}
class GWM_HollowPointBox : GWM_HollowPointMagazine
{
	Default
	{
		//$Category Ammo
		//$Title "Hollow Point Box
		Inventory.PickupMessage "$GOTHOLLOWPOINTBOX";
		Inventory.Amount 50;
		Inventory.PickupSound "pickups/magazinebox";
	}
	States
	{
		Spawn:
			AMMO A -1;
			Stop;
	}
}

class GWM_FMJMagazine : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Full Metal Jacket Magazine
		Inventory.PickupMessage "$GOTFULLMETALMAG";
		Inventory.Amount 10;
		Inventory.MaxAmount 300;
		Ammo.BackpackAmount 10;
		Inventory.Icon "MAGZB0";
		Inventory.PickupSound "pickups/magazine";
	}
	States
	{
		Spawn:
			MAGZ B -1;
			Stop;
	}
}
class GWM_FMJBelt : GWM_FMJMagazine
{
	Default
	{
		//$Category Ammo
		//$Title "Full Metal Jacket Belt
		Inventory.PickupMessage "$GOTFULLMETALBELT";
		Inventory.Amount 50;
		Inventory.PickupSound "pickups/belt";
	}
	States
	{
		Spawn:
			AMMO B -1;
			Stop;
	}
}

class GWM_Shell : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Small Shell Box
		Inventory.PickupSound "pickups/shells";
		Inventory.PickupMessage "$GOTSHELLS";
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Inventory.Icon "SHELA0";
	}
	States
	{
		Spawn:
			SHEL A -1;
			Stop;
	}
}
class GWM_ShellBox : GWM_Shell
{
	Default
	{
		//$Category Ammo
		//$Title "Large Shell Box
		Inventory.PickupMessage "$GOTSHELLBOX";
		Inventory.Amount 20;
	}
	States
	{
		Spawn:
			SBOX A -1;
			Stop;
	}
}

class GWM_IceShell : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Small Ice Shell Box
		Inventory.PickupSound "pickups/shells";
		Inventory.PickupMessage "$GOTICESHELLS";
		Inventory.Amount 4;
		Inventory.MaxAmount 25;
		Ammo.BackpackAmount 4;
		Inventory.Icon "SHELB0";
	}
	States
	{
		Spawn:
			SHEL B -1;
			Stop;
	}
}
class GWM_IceShellBox : GWM_IceShell
{
	Default
	{
		//$Category Ammo
		//$Title "Large Ice Shell Box
		Inventory.PickupMessage "$GOTICESHELLBOX";
		Inventory.Amount 20;
	}
	States
	{
		Spawn:
			SBOX B -1;
			Stop;
	}
}

class GWM_RocketAmmo : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Rocket
		Inventory.PickupMessage "$GOTROCKET";
		Inventory.Amount 1;
		Inventory.MaxAmount 30;
		Ammo.BackpackAmount 1;
		Inventory.Icon "ROCKA0";
	}
	States
	{
		Spawn:
			ROCK A -1;
			Stop;
	}
}
class GWM_RocketBox : GWM_RocketAmmo
{
	Default
	{
		//$Category Ammo
		//$Title "Rocket Box
		Inventory.PickupMessage "$GOTROCKETBOX";
		Inventory.Amount 5;
	}
	States
	{
		Spawn:
			BROK A -1;
			Stop;
	}
}

class GWM_AcidVial : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Acid Vial
		Inventory.PickupMessage "$GOTACIDVIAL";
		Inventory.Amount 1;
		Inventory.MaxAmount 20;
		Ammo.BackpackAmount 2;
		Inventory.Icon "ACDVC0";
	}
	States
	{
		Spawn:
			ACDV ABCDCB 6;
			Loop;
	}
}
class GWM_LargeAcidVial : GWM_AcidVial
{
	Default
	{
		//$Category Ammo
		//$Title "Large Acid Vial
		Inventory.PickupMessage "$GOTLARGEACIDVIAL";
		Inventory.Amount 5;
	}
	States
	{
		Spawn:
			ACDV EFGHGF 6;
			Loop;
	}
}

class GWM_Cell : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Power Cell
		Inventory.PickupMessage "$GOTCELL";
		Inventory.Amount 20;
		Inventory.MaxAmount 250;
		Ammo.BackpackAmount 20;
		Inventory.Icon "CELLA0";
	}
	States
	{
		Spawn:
			CELL A -1;
			Stop;
	}
}
class GWM_CellPack : GWM_Cell
{
	Default
	{
		//$Category Ammo
		//$Title "Power Cell Pack
		Inventory.PickupMessage "$GOTCELLPACK";
		Inventory.Amount 100;
	}
	States
	{
		Spawn:
			CELL B -1;
			Stop;
	}
}
//class GWM_CellPack_SpawnHeatsink : GWM_CellPack // optionally spawns a Melter heatsink
//{
//	override void BeginPlay()
//	{
//		Super.BeginPlay();
//		if (random(0,4) == 4)
//			Spawn("GWM_MelterHeatsink", self.pos);
//	}
//}

class GWM_GasCanister : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Gas Canister
		Inventory.PickupSound "pickups/gas";
		Inventory.Amount 3;
		Inventory.MaxAmount 20;
		Ammo.BackpackAmount 5;
		Inventory.PickupMessage "$GOTGASCANISTER";
		Inventory.Icon "AGASA0";
	}
	States
	{
		Spawn:
			AGAS A -1;
			Stop;
	}
}
class GWM_GasPack : GWM_GasCanister
{
	Default
	{
		//$Category Ammo
		//$Title "Pack of Gas Canisters
		Inventory.Amount 10;
		Inventory.PickupMessage "$GOTGASPACK";
	}
	States
	{
		Spawn:
			AGAS B -1;
			Stop;
	}
}

class GWM_ImpalerBolts : Ammo replaces CrossbowAmmo
{
	Default
	{
		//$Category Ammo
		//$Title "Impaler Bolts
		Inventory.PickupMessage "$GOTBOLTS";
		Inventory.Amount 4;
		Inventory.MaxAmount 40;
		Inventory.Icon "CBWAA0";
		Ammo.BackpackAmount 2;
	}
	States
	{
		Spawn:
			CBWA A -1;
			Stop;
	}
}
class GWM_ImpalerBoltsHefty : GWM_ImpalerBolts replaces CrossbowHefty
{
	Default
	{
		//$Category Ammo
		//$Title "Quiver of Impaler Bolts
		Inventory.PickupMessage "$GOTBOLTSHEFTY";
		Inventory.Amount 8;
	}
	States
	{
		Spawn:
			CBWA B -1;
			Stop;
	}
}

Class GWM_EverIce : Ammo replaces BlasterAmmo
{
	Default
	{
		//$Category Ammo
		//$Title "Ever Ice
		Inventory.PickupMessage "$GOTEVERICE";
		Inventory.Amount 25;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 25;
		Inventory.Icon "EICEI0";
		Scale 0.4;
	}

	States
	{
		Spawn:
			EICE ABCD 6;
			Loop;
	}
}
Class GWM_LargeEverIce : GWM_EverIce replaces BlasterHefty
{
	Default
	{
		//$Category Ammo
		//$Title "Large Ever Ice Chunk
		Inventory.PickupMessage "$GOTEVERICEHEFTY";
		Inventory.Amount 50;
		Scale 0.4;
	}

	States
	{
		Spawn:
			EICE EFGH 6;
			Loop;
	}
}

class GWM_ANNIHILATORAMMO : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTANNIHILATORAMMO";
		Inventory.Amount 5;
		Inventory.MaxAmount 2500;
		Scale 0.4;
	}

	States
	{
		Spawn:
			EICE A 6;
			Loop;
	}
}

class GWM_ScrapDrum : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Scrap Drum
		Inventory.PickupMessage "$GOTSCRAPDRUM";
		Inventory.Amount 4;
		Inventory.MaxAmount 20;
		Ammo.BackpackAmount 4;
		Inventory.Icon "SCRPA0";
		Inventory.PickupSound "pickups/scrapdrum";
	}
	States
	{
		Spawn:
			SCRP A -1;
			Stop;
	}
}
class GWM_ScrapDrumPack : GWM_ScrapDrum
{
	Default
	{
		//$Category Ammo
		//$Title "Scrap Drum Pack
		Inventory.PickupMessage "$GOTSCRAPPACK";
		Inventory.Amount 20;
		Inventory.PickupSound "pickups/scrapdrumpack";
	}
	States
	{
		Spawn:
			SCRP B -1;
			Stop;
	}
}

class GWM_StomperAmmo : Ammo
{
	Default
	{
		//$Category Ammo
		//$Title "Stomper Missiles
		Inventory.PickupMessage "$GOTSTOMPERAMMO";
		Inventory.Amount 3;
		Inventory.MaxAmount 20;
		Ammo.BackpackAmount 3;
		Inventory.PickupSound "pickups/stompermissile";
		Inventory.Icon "STMPA0";
	}
	States
	{
		Spawn:
			STMP A -1;
			Stop;
	}
}
class GWM_StomperBox : GWM_StomperAmmo
{
	Default
	{
		//$Category Ammo
		//$Title "Stomper Missile Box
		Inventory.PickupMessage "$GOTSTOMPERBOX";
		Inventory.Amount 15;
		Inventory.PickupSound "pickups/stomperbox";
	}
	States
	{
		Spawn:
			STMP B -1;
			Stop;
	}
}

class GWM_WandCrystal : Ammo replaces GoldWandAmmo
{
	Default
	{
		//$Category Ammo
		//$Title "Wand Crystal
		Inventory.PickupMessage "$GOTWANDCRYSTAL";
		Inventory.Amount 10;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 10;
		Inventory.Icon "WANCA0";
	}
	States
	{
		Spawn:
			WANC A -1;
			Stop;
	}
}
class GWM_LargeWandCrystal : GWM_WandCrystal replaces GoldWandHefty
{
	Default
	{
		//$Category Ammo
		//$Title "Large Wand Crystal
		Inventory.PickupMessage "$GOTLARGEWANDCRYSTAL";
		Inventory.Amount 50;
	}
	States
	{
		Spawn:
			WANC BCDB -1;
			Stop;
	}
}

class GWM_NoteBox : Ammo
{
	Default
	{
		//$Category Ammunition
		Inventory.PickupMessage "$GOTNOTEBOX";
		Inventory.Amount 5;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "TRPAA0";
		Inventory.PickupSound "pickups/notebox";
	}
	States
	{
		Spawn:
			TRPA A -1;
			Stop;
	}
}