// DAGGER
class GWM_Dagger : CustomInventory
{
	Default
	{
		//$Category Items
		//$Title "Dagger
		Tag "$TAG_DAGGER";
		Inventory.Icon "CVDGA0";
		Inventory.PickupMessage "$GOTDAGGER";
		Inventory.MaxAmount 20;
		Inventory.Amount 1;
		Inventory.PickupSound "pickups/cvitem";
		+INVENTORY.INVBAR;
	}
	States
	{
		Spawn:
			CVDG A -1 Bright;
			Stop;
		Use:
			TNT1 A 0 {
				A_FireProjectile("GWM_ThrownDagger",0,0,0,-4);
				A_FireProjectile("GWM_ThrownDagger",5,0,0,-4);
				A_FireProjectile("GWM_ThrownDagger",-5,0,0,-4);
			}
			Stop;
	}
}

class GWM_ThrownDagger : Actor
{
	Default
	{
		Radius 6;
		Height 8;
		Speed 30;
		FastSpeed 40;
		Damage 15;
		Projectile;
		+RANDOMIZE
		+FLATSPRITE
		SeeSound "items/dagger/throw";
		DeathSound "items/dagger/rip";
	}
	States
	{
		Spawn:
			CVDG B 1 Bright A_SpawnItemEx("GWM_DaggerTrail",-10,0,-2);
			Loop;
		Death:
			TNT1 A 0;
			Stop;
	}
}

class GWM_DaggerTrail : Actor
{
	Default
	{
		Projectile;
		+NoClip
		Renderstyle "Translucent";
		Alpha 0.6;
		+FLATSPRITE
	}
	States
	{
		Spawn:
			CVDG C 1 Bright;
			CVDG C 1 Bright A_SetTranslucent(0.5);
			CVDG C 1 Bright A_SetTranslucent(0.4);
			CVDG C 1 Bright A_SetTranslucent(0.3);
			CVDG C 1 Bright A_SetTranslucent(0.2);
			Stop;
	}
}

// HOLY WATER
class GWM_HolyWater : CustomInventory
{
	Default
	{
		//$Category Items
		//$Title "Holy Water
		Tag "$TAG_HOLYWATER";
		Inventory.Icon "CVHWA0";
		Inventory.PickupMessage "$GOTHOLYWATER";
		Inventory.MaxAmount 20;
		Inventory.Amount 1;
		Inventory.PickupSound "pickups/cvitem";
		+INVENTORY.INVBAR;
	}
	States
	{
		Spawn:
			CVHW AB 8 Bright;
			Loop;
		Use:
			TNT1 A 0 A_FireProjectile("GWM_ThrownHolyWater",0,0,0,0,0,5);
			Stop;
	}
}

class GWM_ThrownHolyWater : Actor
{
	Default
	{
		Radius 6;
		Height 8;
		Speed 15;
		Damage 10;
		Projectile;
		-NOGRAVITY
		+FORCEPAIN
		+RANDOMIZE
		+BOUNCEONWALLS
		+RIPPER
		+BLOODLESSIMPACT
		+NoBlockMap
		SeeSound "items/holy_water/throw";
		DeathSound "items/holy_water/break";
	}
	States
	{
		Spawn:
			CVHW AB 8 Bright;
			Loop;
		Death:
			TNT1 A 0 Bright {
				A_SpawnItemEx("GWM_HolyFire", 5, 0, 1, 0, 0, 0, 0, SXF_NOCHECKPOSITION|CMF_TRACKOWNER);
				A_SpawnItemEx("GWM_HolyFire", 0, 0, 1, 0, 0, 0, 0, SXF_NOCHECKPOSITION|CMF_TRACKOWNER);
				A_SpawnItemEx("GWM_HolyFire", -5, 0, 1, 0, 0, 0, 0, SXF_NOCHECKPOSITION|CMF_TRACKOWNER);
				A_SpawnItemEx("GWM_HolyFire", 0, 5, 1, 0, 0, 0, 0, SXF_NOCHECKPOSITION|CMF_TRACKOWNER);
				A_SpawnItemEx("GWM_HolyFire", 0, -5, 1, 0, 0, 0, 0, SXF_NOCHECKPOSITION|CMF_TRACKOWNER);
			}
			Stop;
	}
}

class GWM_HolyFire : GWM_FlameProjectile
{
	Default
	{
		Radius 1;
		Height 1;
		+NoBlockMap
		+Painless
		+BloodlessImpact
		+Missile
		+DropOff
		GWM_FlameProjectile.FireBurnCount 30;
		DamageFunction (1);
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay Bright {
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 0,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 90,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 180,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 270,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 45,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 135,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 225,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire1", 1, 0, 315,CMF_TRACKOWNER);
			}
			Stop;
	}
}

class GWM_HolyFire1 : GWM_FlameProjectile
{
	Default
	{
		Radius 1;
		Height 1;
		+Ripper
		+NoExplodeFloor
		+Painless
		+BloodlessImpact
		+Missile
		+DropOff
		+NoBlockMap
		Speed 2;
		GWM_FlameProjectile.FireBurnCount 30;
		DamageFunction (1);
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay {
				A_SpawnProjectile("GWM_HolyFire2", 1, 8, 0,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire2", 1, 16, 16,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire2", 1, -16, -16,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire2", 1, 32, 0,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire2", 1, -32, 16,CMF_TRACKOWNER);
				A_SpawnProjectile("GWM_HolyFire2", 1, -8, -16,CMF_TRACKOWNER);
			}
			Stop;
	}
}

class GWM_HolyFire2 : GWM_FlameProjectile
{
	Default
	{
		Radius 8;
		Height 64;
		+Ripper
		+NoExplodeFloor
		+BloodlessImpact
		+DropOff
		+Randomize
		+FORCEPAIN
		+Missile
		+NoBlockMap
		Scale 0.8;
		Speed 0;
		RenderStyle "Add";
		Alpha 0.6;
		Obituary "%o was scorched by a Lantern Ghoul"; // change later
		GWM_FlameProjectile.FireBurnCount 30;
		DamageFunction (1);
	}
	States
	{
		Spawn:
			TNT1 A 8;
			FRTF A 3 Bright;
			FRTF BC 3 Bright A_Explode((1 * 1), 64,0,0);
			TNT1 A 0 A_Explode((2 * 1), 64,0);
			TNT1 A 0 A_Jump(191, "Death");
			TNT1 A 10 A_SpawnProjectile("GWM_HolyFire2", 0, 0, 0,CMF_TRACKOWNER);
		Death:
			FRTF DEFGHIJKLMNO 3 Bright;
			Stop;
	}
}

//BOOMERANG CROSS
class GWM_BoomerangCross : CustomInventory
{
	Default
	{
		//$Category Items
		//$Title "Boomerang Cross
		Tag "$TAG_BOOMERANGCROSS";
		Inventory.Icon "CVCRA0";
		Inventory.PickupMessage "$GOTBOOMERANGCROSS";
		Inventory.MaxAmount 20;
		Inventory.Amount 1;
		Inventory.PickupSound "pickups/cvitem";
		+INVENTORY.INVBAR;
	}
	States
	{
		Spawn:
			CVCR AB 8 Bright;
			Loop;
		Use:
			TNT1 A 0 A_FireProjectile("GWM_ThrownBoomerangCross",0,0,0,0);
			Stop;
	}
}

class GWM_ThrownBoomerangCross : Actor
{
	Default
	{
		Radius 10;
		Height 20;
		Speed 25;
		FastSpeed 30;
		Damage 22;
		BounceCount 2;
		Projectile;
		Renderstyle "Normal";
		+SYNCHRONIZED
		+RIPPER
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+USEBOUNCESTATE
		SeeSound "items/cross/throw";
		DeathSound "items/cross/hit";
	}
	States
	{
		Spawn:
			CVCR CDECDECDECDE 2 Bright A_SpawnItemEx("GWM_BoomerangCrossTrail", random(-4, 4), random(-1, 1), random(-2, 2), 0, 0, 0, 0, 0, 0);
		Reverse:
			TNT1 A 0 A_ChangeVelocity(-25, 0, -Vel.Z, CVF_RELATIVE|CVF_REPLACE);
		SpawnReverse:
			CVCR EDC 2 Bright A_SpawnItemEx("GWM_BoomerangCrossTrail", random(-4, 4), random(-1, 1), random(-2, 2), 0, 0, 0, 0, 0, 0);
			Loop;
		Bounce.Wall:
			CVCR EDC 2 Bright A_SpawnItemEx("GWM_BoomerangCrossTrail", random(-4, 4), random(-1, 1), random(-2, 2), 0, 0, 0, 0, 0, 0);
			Loop;
		Bounce.Floor:
			CVCR CDECDECDECDE 2 Bright A_SpawnItemEx("GWM_BoomerangCrossTrail", random(-4, 4), random(-1, 1), random(-2, 2), 0, 0, 0, 0, 0, 0);
			Goto Reverse;
		Bounce.Ceiling:
			CVCR CDECDECDECDE 2 Bright A_SpawnItemEx("GWM_BoomerangCrossTrail", random(-4, 4), random(-1, 1), random(-2, 2), 0, 0, 0, 0, 0, 0);
			Goto Reverse;
		Death:
			TNT1 A 0 A_Scream;
			CVCR FGH 2;
			Stop;
	}
}

class GWM_BoomerangCrossTrail : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		RenderStyle "Add";
		Alpha 1;
	}
	States
	{
		Spawn:
			CVCR IJK 4 Bright;
			Stop;
	}
}

//AXE
class GWM_Axe : CustomInventory
{
	Default
	{
		//$Category Items
		//$Title "Axe
		Tag "$TAG_AXE";
		Inventory.Icon "CVAXA0";
		Inventory.PickupMessage "$GOTAXE";
		Inventory.MaxAmount 20;
		Inventory.Amount 1;
		Inventory.PickupSound "pickups/cvitem";
		+INVENTORY.INVBAR;
	}
	States
	{
		Spawn:
			CVAX A -1 Bright;
			Stop;
		Use:
			TNT1 A 0 A_FireProjectile("GWM_ThrownAxe",0,0,0,0,0,22);
			Stop;
	}
}

class GWM_ThrownAxe : Actor
{
	Default
	{
		Radius 10;
		Height 31;
		Speed 18;
		Damage 25;
		Gravity 0.75;
		Projectile;
		-NoGravity
		BounceCount 2;
		BounceSound "items/axe/bounce";
		WallBounceSound "items/axe/bounce";
		+BOUNCEONCEILINGS
		+BOUNCEONFLOORS
		+BOUNCEONWALLS
		+RANDOMIZE
		+RIPPER
		RenderStyle "Normal";
		Alpha 1;
		SeeSound "items/axe/throw";
		DeathSound "items/axe/hit";
	}
	States
	{
		Spawn:
			CVAX BCDEFGHI 2;
			Loop;
		Death:
			TNT1 A 0 A_Scream;
			CVAX JK 2;
			Stop;
	}
}
// do this after work lol
/*
//HOLY BIBLE	-- BLOOD MOON ONLY SUBWEAPON

ACTOR SubBible : CustomInventory 26319
{
	+INVENTORY.PICKUPFLASH
	+INVENTORY.FANCYPICKUPSOUND
	+INVENTORY.ALWAYSPICKUP
	Inventory.Icon ""
	Inventory.PickupSound "pickups/cvitem"
	Tag "Holy Bible"
	Inventory.MaxAmount 1
	Inventory.Amount 1
	Inventory.PickupMessage "You got the Holy Bible."
	States
	{
	Spawn:
		CVBB A 8 bright
		Loop
	Pickup:
		TNT1 A 0 A_GiveInventory("Token_Bible")
	TNT1 A 0 A_TakeInventory("Token_HolyWater")
	TNT1 A 0 A_TakeInventory("Token_Knife")
	TNT1 A 0 A_TakeInventory("Token_Stopwatch")
	TNT1 A 0 A_TakeInventory("Token_Boomerang")
		TNT1 A 0 A_TakeInventory("Token_Axe")
		stop
	}
}

// consolidate these later using a function or something.
Actor BibleProj
{
	Default
	{
		Radius 1
		Height 1
		Speed 20
		Damage 5
		Projectile
		Bouncecount 15
		+SLIDESONWALLS
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+THRUACTORS
		SeeSound "items/bible"
		DeathSound ""
		Decal Scorch
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
			CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
			TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
			TNT1 A 0 A_Explode(10, 80, 0)
			TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
			CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
			TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
			TNT1 A 0 A_SpawnProjectile("BibleProj2", 0, 0, 55)
			TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
			Stop
		Death:
			TNT1 A 0
			Stop
	}
}


Actor BibleTail
{
	Projectile
	+NoClip
	RenderStyle Add
	Alpha 0.5
	States
	{
	Spawn:
		TNT1 AA 1
		CVBB EEEEEEE 1 Bright
	CVBB EE 1 Bright A_SetRenderStyle(0.2,STYLE_Add)
		TNT1 A 0 A_Explode(10, 100, 0)
		Stop
	}
}

Actor BibleProj2 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj3", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj3 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj4", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj4 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj5", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj5 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj6", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj6 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj7", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj7 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj8", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj8 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj9", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj9 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj10", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj10 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj11", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj11 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj12", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj12 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj13", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj13 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj14", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj14 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj15", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj15 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj16", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj16 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj17", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj17 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj18", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj18 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj19", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj19 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		TNT1 A 0 A_SpawnProjectile("BibleProj20", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}

Actor BibleProj20 : BibleProj
{
	States
	{
	Spawn:
		TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION )
		CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
	TNT1 A 0 A_Explode(10, 80, 0)
	TNT1 A 0 A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	CVBB D 1 Bright A_Warp(AAPTR_MASTER,0,0,0,0,WARPF_INTERPOLATE | WARPF_COPYVELOCITY | WARPF_NOCHECKPOSITION	)
	TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		//TNT1 A 0 A_SpawnProjectile("BibleProj15", 0, 0, 55)
		TNT1 A 0 A_SpawnItemEx("BibleTail", 0, 0, 0, 0, 0, 0, 0, 0)
		Stop
	Death:
		TNT1 A 0
		Stop
	}
}
*/