class GWM_Stimpack : CustomInventory replaces Stimpack
{
	Default
	{
		Inventory.PickupMessage "";
		Inventory.PickupSound "pickups/healthitem";
	}
	States
	{
		Spawn:
			STIM A 1;
			loop;
		Pickup:
			TNT1 A 0 A_Jumpifhealthlower(GetMaxHealth(true),"Heal");
			goto FailToHeal;
		Heal:
			TNT1 A 0 {
				if (Health < 25)
					A_Log("$GOTSTIMPACKNEED", true);
				else
					A_Log("$GOTSTIMPACK", true);
			}
			TNT1 A 0 GiveInventory("GWM_HealAmount",10);
			stop;
		FailToHeal:
			TNT1 A 0;
			fail;
	}
}

class GWM_Medkit : CustomInventory replaces Medikit
{
	Default
	{
		Inventory.PickupMessage "";
		Inventory.PickupSound "pickups/healthitem";
	}
	States
	{
		Spawn:
			MEDI A 1;
			loop;
		Pickup:
			TNT1 A 0 A_Jumpifhealthlower(GetMaxHealth(true),"Heal");
			goto FailToHeal;
		Heal:
			TNT1 A 0 {
				if (Health < 25)
					A_Log("$GOTMEDKITNEED", true);
				else
					A_Log("$GOTMEDKIT", true);
			}
			TNT1 A 0 GiveInventory("GWM_HealAmount",25);
			stop;
		FailToHeal:
			TNT1 A 0;
			fail;
	}
}

class GWM_HealthBonus : HealthBonus replaces HealthBonus
{
	Default
	{
		//$Category Pickups
		//$Title "Health Bonus
		Inventory.PickupSound "pickups/healthbonus";
		Inventory.PickupMessage "$GOTHEALTHBONUS";
	}
}

class GWM_ArmorBonus : ArmorBonus replaces ArmorBonus
{
	Default
	{
		//$Category Pickups
		//$Title "Armor Bonus
		Armor.MaxSaveAmount 300;
		Inventory.PickupSound "pickups/armorbonus";
		Inventory.PickupMessage "$GOTARMORBONUS";
	}
}