class GWM_Stimpack : CustomInventory replaces Stimpack
{
	Default
	{
		Inventory.PickupMessage "";
		Inventory.PickupSound "pickups/healthitem";
	}
	States
	{
		Spawn:
			STIM A 1;
			loop;
		Pickup:
			TNT1 A 0 A_Jumpifhealthlower(GetMaxHealth(true),"Heal");
			goto FailToHeal;
		Heal:
			TNT1 A 0 {
				if (Health < 25)
					A_Log("$GOTSTIMPACKNEED", true);
				else
					A_Log("$GOTSTIMPACK", true);
			}
			TNT1 A 0 GiveInventory("GWM_HealAmount",10);
			stop;
		FailToHeal:
			TNT1 A 0;
			fail;
	}
}

class GWM_Medkit : CustomInventory replaces Medikit
{
	Default
	{
		Inventory.PickupMessage "";
		Inventory.PickupSound "pickups/healthitem";
	}
	States
	{
		Spawn:
			MEDI A 1;
			loop;
		Pickup:
			TNT1 A 0 A_Jumpifhealthlower(GetMaxHealth(true),"Heal");
			goto FailToHeal;
		Heal:
			TNT1 A 0 {
				if (Health < 25)
					A_Log("$GOTMEDKITNEED", true);
				else
					A_Log("$GOTMEDKIT", true);
			}
			TNT1 A 0 GiveInventory("GWM_HealAmount",25);
			stop;
		FailToHeal:
			TNT1 A 0;
			fail;
	}
}

class GWM_HealthBonus : HealthBonus replaces HealthBonus
{
	Default
	{
		//$Category Pickups
		//$Title "Health Bonus
		Inventory.PickupSound "pickups/healthbonus";
		Inventory.PickupMessage "$GOTHEALTHBONUS";
	}
}

class GWM_ArmorBonus : ArmorBonus replaces ArmorBonus
{
	Default
	{
		//$Category Pickups
		//$Title "Armor Bonus
		Armor.MaxSaveAmount 300;
		Inventory.PickupSound "pickups/armorbonus";
		Inventory.PickupMessage "$GOTARMORBONUS";
	}
}

class GWM_Backpack : Backpack replaces Backpack
{
	Default
	{
		//$Category Pickups
		//$Title "Backpack
		Inventory.PickupSound "pickups/backpack";
	}
}

class GWM_Berserk : Berserk
{
	override void Touch(Actor toucher) {
		if (CVar.GetCVar('gwm_shutupmerc', toucher.player).GetBool() == false) 
			toucher.A_StartSound("player/berserk", CHAN_VOICE);
		Super.Touch(toucher);
	}
	Default
	{
		//$Category Pickups
		//$Title "Berserk
	}
	States
	{
		Pickup:
			TNT1 A 0 {
				A_GiveInventory("GWM_PowerStrength");
				HealThing(100, 0);
				A_SetBlend("Red", .25, 35); // from Supercharge
			}
			Stop;
	}
}
class GWM_PowerStrength : PowerStrength replaces PowerStrength
{
	Default
	{
		Powerup.Duration 1;
		Powerup.Color "000000", 0.0;
		+INVENTORY.HUBPOWER
	}
}

class GWM_Soulsphere : Soulsphere
{
	Default
	{
		//$Category Pickups
		//$Title "Soulsphere
	}
}
class GWM_BlurSphere : BlurSphere
{
	Default
	{
		//$Category Pickups
		//$Title "Partial Invisibility
	}
}

class GWM_DrainSphere : PowerupGiver
{
	Default
	{
		//$Category Pickups
		//$Title "Life Drain
		Inventory.PickupMessage "$GOTLIFEDRAIN";
		Inventory.Icon "VAMPA0";
		Powerup.Color "FF0000", 0.25;
		Inventory.MaxAmount 0;
		Inventory.UseSound "pickups/slowmo";
		Powerup.Type "PowerDrain";
		Powerup.Duration 1000;
		+INVENTORY.AUTOACTIVATE
		+RANDOMIZE
	}
	States
	{
		Spawn:
			VAMP ABCD 4 Bright;
			Loop;
	}
}

class GWM_InvulnerabilitySphere : InvulnerabilitySphere
{
	Default
	{
		//$Category Pickups
		//$Title "Invulnerability
	}
}

class GWM_ReflectSphere : PowerupGiver
{
	Default
	{
		//$Category Pickups
		//$Title "Reflective Shots
		Inventory.PickupMessage "$GOTREFLECTIVE";
		Inventory.Icon "REFLA0";
		Powerup.Color "0011FF", 0.25;
		Inventory.MaxAmount 0;
		Inventory.UseSound "pickups/slowmo";
		Powerup.Type "PowerInvulnerable";
		Powerup.Mode "Reflective";
		Powerup.Duration -30; // 30 seconds
		+INVENTORY.AUTOACTIVATE
		+RANDOMIZE
	}
	States
	{
		Spawn:
			REFL ABCD 4 Bright;
			Loop;
	}
}

class GWM_LightAmpVisor : Infrared replaces Infrared // Exists solely to free up the PVIS sprite name for mapsets like Valiant, so Pyro Knights don't turn into light-amp goggles.
{
	States
	{
		Spawn:
			AMPV A 6 Bright;
			AMPV B 6;
			Loop;
	}
}