class GWM_PlasmaRifle : GWM_WeaponBase
{
	Default
	{
		//$Category Weapons
		//$Title "Plasma Rifle
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 40;
		Weapon.SelectionOrder 100;
		Weapon.AmmoType "GWM_Cell";
		Weapon.AmmoType2 "GWM_Cell";
		Decal "RailScorch";
		Tag "$TAG_PLASMARIFLE";
		Inventory.PickupMessage "$GOTPLASMARIFLE";
		Obituary "$KILLPLASMARIFLE_RAIL";
		ZWeapon.MaxCharge 100;
	}
	States
	{
		Recoil:
			TNT1 AAA 1 A_SetPitch(pitch+1);
			TNT1 AAAAAA 1 A_SetPitch(pitch-0.50);
			Stop;
		Ready:
			PLSG A 1 ZWL_WeaponReady();
			Loop;
		Deselect:
			PLSG A 1 A_Lower(18);
			Loop;
		Select:
			PLSG A 1 A_Raise(18);
			Loop;
		AltFire:
			TNT1 A 0 A_StartSound("weapons/icechrg", CHAN_WEAPON);
		AltHold:
			PLSG A 2
			{
				A_WeaponOffset(0+frandom(-0.4,0.4)*(invoker.chargeLevel/10), 32+frandom(0,0.8)*(invoker.chargeLevel/10), WOF_INTERPOLATE);	// G: edited the second frandom call to not allow edges of the weapon to be seen
//				A_SpawnItemEx("IceFog", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));

				switch(invoker.chargeLevel)
				{
					case 1:
						A_StartSound("weapons/icelv2", CHAN_BODY);
						break;
					case 25:
						A_StartSound("weapons/icelv2", CHAN_BODY);
						break;
					case 50:
						A_StartSound("weapons/icelv2", CHAN_BODY);
						break;
					case 75:
						A_StartSound("weapons/icelv2", CHAN_BODY);
						break;
					case 99:
						A_StartSound("weapons/icelv3", CHAN_BODY);
						break;
				}
/*				if (invoker.chargeLevel >= 0)
					A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				if (invoker.chargeLevel >= 10)
					A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));
				if (invoker.chargeLevel >= 20)
					A_SpawnItemEx("IceFog2", 24, 0, 32, 0.5, 0, FRandom(-0.5, 0.5), Random(-12, 12));*/
			}
			ISHT A 0
			{
				if (invoker.chargeLevel < 1 && invoker.Ammo2.Amount < 5)
					A_Refire();
				if (invoker.chargeLevel < 25 && invoker.Ammo2.Amount < 10)
					A_Refire();
				if (invoker.chargeLevel < 50 && invoker.Ammo2.Amount < 20)
					A_Refire();
				if (invoker.chargeLevel < 75 && invoker.Ammo2.Amount < 30)
					A_Refire();
				if (invoker.chargeLevel < 100 && invoker.Ammo2.Amount < 40)
					A_Refire();
			}
			ISHT A 0 ZWL_Charge();
			ISHT A 0 A_Refire();
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 100, "Fire.Level6");
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 75, "Fire.Level5");
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 50, "Fire.Level4");
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 25, "Fire.Level3");
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 1, "Fire.Level2");
			PLSG A 0 A_Jumpif(invoker.chargeLevel >= 0, "Fire.Level1");
			Goto AltFire;
		Fire:
		Fire.Level1:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/plasshot", CHAN_WEAPON);
				A_FireProjectile("GWM_PlasmaBall", 0);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
			}
			PLSG AA 1 {
				A_WeaponOffset(0, -4, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.05, 0, WOF_ADD);
			}
			Goto Fire.Done;
		Fire.Level2:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				invoker.Ammo2.Amount -= 4;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/railshot", CHAN_WEAPON);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_FireProjectile("GWM_PlasmaBallLevel2", spawnofs_xy: 0, spawnheight: 0);
			}
			PLSG AA 1 {
				A_WeaponOffset(0, -4, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.05, 0, WOF_ADD);
			}
			Goto Fire.Done;
		Fire.Level3:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				invoker.Ammo2.Amount -= 9;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/railshot", CHAN_WEAPON);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_Recoil(1);
				A_FireProjectile("GWM_PlasmaBallLevel3", spawnofs_xy: 0, spawnheight: -6);
			}
			Goto Fire.ChargeShotDone;
		Fire.Level4:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				invoker.Ammo2.Amount -= 19;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/railshot", CHAN_WEAPON);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_Recoil(2);
				A_FireProjectile("GWM_PlasmaBallLevel3", spawnofs_xy: 0, spawnheight: -6);
				A_FireProjectile("GWM_PlasmaBallLevel4", spawnofs_xy: 0, spawnheight: 6);
			}
			Goto Fire.ChargeShotDone;
		Fire.Level5:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				invoker.Ammo2.Amount -= 29;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/railshot", CHAN_WEAPON);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_Recoil(3);
				A_FireProjectile("GWM_PlasmaBallLevel3", spawnofs_xy: 0, spawnheight: -6);
				A_FireProjectile("GWM_PlasmaBallLevel5_1", spawnofs_xy: -5.196, spawnheight: 3);
				A_FireProjectile("GWM_PlasmaBallLevel5_2", spawnofs_xy: 5.196, spawnheight: 3);
			}
			Goto Fire.ChargeShotDone;
		Fire.Level6:
			PLSG A 1 {
				invoker.chargeLevel = 0;
				invoker.Ammo2.Amount -= 39;
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_StartSound("weapons/railshot", CHAN_WEAPON);
				A_SpawnItemEx("GWM_PlasmaFlash");
				A_GunFlash();
				A_WeaponOffset(0, 8, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_Recoil(4);
//				A_FireProjectile("GWM_PlasmaBallLevel3", spawnofs_xy: 0, spawnheight: -6);
				A_FireProjectile("GWM_PlasmaBallLevel4", spawnofs_xy: 0, spawnheight: 6);
//				A_FireProjectile("GWM_PlasmaBallLevel6_1", spawnofs_xy: -6, spawnheight: 0);
				A_FireProjectile("GWM_PlasmaBallLevel6_2", spawnofs_xy: 6, spawnheight: 0);
			}
			Goto Fire.ChargeShotDone;
		Fire.Done:
			TNT1 A 0 A_CheckReload;
			PLSG B 3 A_ReFire;
			PLSG C 9;
			PLSG B 3;
			Goto Ready;
		Fire.ChargeShotDone:
			PLSG AA 1 {
				A_WeaponOffset(0, -4, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.05, 0, WOF_ADD);
			}
			TNT1 A 0 A_CheckReload;
			PLSG E 7 A_StartSound("weapons/railchrg", CHAN_BODY);
			PLSG CFGH 7;
			PLSG I 5;
			Goto Ready;
		Flash:
			PLSF A 1 Bright {
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
				A_OverlayScale(OverlayID(), 1.10, 0, WOF_INTERPOLATE);
				A_Light1();
			}
			PLSF BC 1 Bright {
				A_OverlayScale(OverlayID(), -0.05, 0, WOF_ADD);
				A_Light1();
			}
			Goto LightDone;
		Spawn:
			PLSG Z -1;
			Stop;
	}
}
class GWM_PlasmaBall : PlasmaBall
{
	Default
	{
		Decal "PlasmaScorch";
		Obituary "$KILLPLASMARIFLE";
		DamageFunction (23);
		Renderstyle "Add";
		Alpha 1.0;
		SeeSound "weapons/plasfly";
		DeathSound "weapons/plasxpl";
	}
	States
	{
		Spawn:
			PLSS A 1 nodelay A_ChangeVelocity(frandom(-0.3,0.3),frandom(-0.3,0.3),frandom(-0.3,0.3));
		Spawnloop:
			PLSS ABADAFACAEAG 1 bright A_SpawnItemEX("GWM_PlasmaBallFlareFX");
			loop;
	}
}
class GWM_PlasmaBallLevel2 : GWM_PlasmaBall
{
	Default
	{
		Scale 3.0;
		+SHOOTABLE
		Obituary "$KILLPLASMARIFLE";
		DamageFunction (46);
	}
}
class GWM_PlasmaBallLevel3 : GWM_PlasmaBallLevel2
{
	Default
	{
		Scale 1.5;
		WeaveIndexXY 0;
		WeaveIndexZ 48;
	}
	States
	{
		Spawn:
			PLSS A 1 nodelay {
				A_ChangeVelocity(frandom(-0.3,0.3),frandom(-0.3,0.3),frandom(-0.3,0.3));
				A_Weave(4, 4, 0.75, 0.75);
			}
		Spawnloop:
			PLSS ABADAFACAEAG 1 bright {
				A_SpawnItemEX("GWM_PlasmaBallFlareFX");
				A_Weave(4, 4, 0.75, 0.75);
			}
			loop;
	}
}
class GWM_PlasmaBallLevel4 : GWM_PlasmaBallLevel3
{
	Default
	{
		WeaveIndexXY 32;
		WeaveIndexXY 16;
	}
}
class GWM_PlasmaBallLevel5_1 : GWM_PlasmaBallLevel3
{
	Default
	{
		WeaveIndexXY 21;
		WeaveIndexXY 5;
	}
}
class GWM_PlasmaBallLevel5_2 : GWM_PlasmaBallLevel3
{
	Default
	{
		WeaveIndexXY 42;
		WeaveIndexXY 26;
	}
}
class GWM_PlasmaBallLevel6_1 : GWM_PlasmaBallLevel3
{
	Default
	{
		WeaveIndexXY 16;
		WeaveIndexXY 0;
	}
}
class GWM_PlasmaBallLevel6_2 : GWM_PlasmaBallLevel3
{
	Default
	{
		WeaveIndexXY 48;
		WeaveIndexXY 32;
	}
}

class GWM_PlasmaBallFlareFX : actor
{
	Default
	{
		+NOINTERACTION;
		Renderstyle "add";
		Scale 1.7;
		Alpha 0.15;
	}
States
	{
	Spawn:
	PLSS X 2 nodelay bright;
	stop;
	}
}
	
	
	
	