class GWM_BurstRifle : GWM_WeaponBase
{
	action void A_FireRifle()
	{
		A_SpawnItemEx("GWM_Flash");
		A_StartSound("weapons/riflesht", CHAN_WEAPON);
		A_FireBullets(5.6, 0, 1, 5, "ZBulletPuff", missile: "GWM_Tracer", spawnheight: 0);
		A_WeaponOffset(0, 6, WOF_ADD);
		ZWL_EjectCasing("GWM_PistolCasing");
	}
	Default
	{
		Weapon.SelectionOrder 700;
		Weapon.UpSound "weapons/draw_primary";
		Weapon.AmmoType "Clip";
		Tag "Burst Rifle";
		Inventory.PickupMessage "$GOTBURSTRIFLE";
		Obituary "$KILLBURSTRIFLE";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
	}
	States
	{
		Ready:
			RIFL A 1 A_WeaponReady;
			Loop;
		Deselect:
			RIFL A 1 A_Lower(12);
			Loop;
		Select:
			RIFL A 1 A_Raise(12);
			Loop;
		Fire:
			RIFL B 1 Bright A_FireRifle;
			RIFL CA 1 A_WeaponOffset(0, -3, WOF_ADD);
			RIFL B 1 Bright A_FireRifle;
			RIFL CA 1 A_WeaponOffset(0, -3, WOF_ADD);
			RIFL B 1 Bright A_FireRifle;
			RIFL CA 1 A_WeaponOffset(0, -3, WOF_ADD);
			RIFL A 5;
			RIFL A 1 A_ReFire;
			Goto Ready;
		Spawn:
			RIFL Z -1;
			Stop;
	}
}