class GWM_MadVulcan : GWM_WeaponBase
{
	bool raging;

	//action void A_Tick()
	//{
	//if (GWM_Player(player.mo).VulcanRage < 1)
	//			{
	//			 invoker.raging == false;
	//			}
	//}

	action void A_FireMVulcan2() // identical to FireMVulcan in everything but name
	{
		A_SpawnItemEx("GWM_Flash");
		ZWL_FireHitscan(0, 8, pellets: 2, spread: 11, tracerType: "GWM_Tracer");
		ZWL_EjectCasing("GWM_RifleCasing", true, -23, 8, 16, (24, 0, -16));
		A_ChangeVelocity(-Cos(pitch)*0.1, 0, sin(pitch)*0.1,CVF_RELATIVE);
		A_SetPitch(pitch+frandom(-.5,.5));
		A_Setangle(angle+frandom(-.5,.5));
	}

	action void A_FireMVulcan()
	{
		A_SpawnItemEx("GWM_Flash");
		ZWL_FireHitscan(0, 8, pellets: 2, spread: 11, tracerType: "GWM_Tracer");
		ZWL_EjectCasing("GWM_RifleCasing", true, -23, 8, 16, (24, 0, -16));
		A_ChangeVelocity(-Cos(pitch)*0.1, 0, sin(pitch)*0.1,CVF_RELATIVE);
		A_SetPitch(pitch+frandom(-.5,.5));
		A_Setangle(angle+frandom(-.5,.5));
	}

	action void A_FireRagingVulcan()
	{
		A_SpawnItemEx("GWM_MuzzleFlashLight3");
		ZWL_FireHitscan(0, 9, pellets: 6, spread: 18, tracerType: "GWM_Tracer");
		ZWL_EjectCasing("GWM_RifleCasing", true, -23, 8, 16, (24, 0, -16));
		ZWL_EjectCasing("GWM_RifleCasing", true, -23, 8, 16, (24, 0, -16));
		ZWL_EjectCasing("GWM_RifleCasing", true, -23, 8, 16, (24, 0, -16));
		A_ChangeVelocity(-Cos(pitch)*0.175, 0, sin(pitch)*0.175,CVF_RELATIVE);
		A_SetPitch(pitch+frandom(-.7,.7));
		A_Setangle(angle+frandom(-.7,.7));
	}
	Default
	{
		//$Category Weapons
		//$Title ""Mad Vulcan" Minigun
		Weapon.SelectionOrder 800; // Has a wind-up, so +100
		Weapon.UpSound "weapons/draw_vulcan";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 120;
		Weapon.AmmoType "GWM_FMJMagazine";
		AttackSound "weapons/vulcanfire";
		Inventory.PickupMessage "$GOTMADVULCAN";
		Obituary "$KILLMADVULCAN";
		Tag "$TAG_MADVULCAN";

		GWM_WeaponBase.BaseVersion "GWM_Minigun";
	}
	States
	{
		Ready:
			VLCG A 0 A_Jumpif(invoker.raging == true, "ReadyRage");
			VLCG A 1 A_WeaponReady;
			Loop;

		ReadyRage:
			VLCG ABCD 1 A_WeaponReady;
			VLCG A 0
			{
			 GWM_Player(player.mo).VulcanRage = GWM_Player(player.mo).VulcanRage-1;
				if (GWM_Player(player.mo).VulcanRage < 1)
				{
				 invoker.raging = false;
				}
			}
			VLCG A 0 A_Jumpif(invoker.raging == true, "ReadyRage");
			Goto Release;

		Deselect:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			VLCG A 1 A_Lower(18);
			Loop;
		Select:
			VLCG A 1 A_Raise(18);
			Loop;

		Altfire:
			//rage mode baby
			VLCG A 1 A_Jumpif(GWM_Player(player.mo).VulcanRage < 50, "Ready");
			VLCG A 0 A_StartSound("weapons/vulcanup", CHAN_BODY);
			VLCG AAABBBCCD 1;
			VLCG A 0 A_StartSound("weapons/vulcanloop", CHAN_BODY, CHANF_LOOPING);
			VLCG A 0 { invoker.raging = true; }
			goto Ready;

		Fire:
			// rev the chaingun
			VLCG A 0 A_Jumpif(invoker.raging == true, "FireRage");
			VLCG A 1 A_StartSound("weapons/vulcanup", CHAN_BODY);
			VLCG AABBBBCCCDDAABCDACAC 1;
			VLCG A 0 A_StartSound("weapons/vulcanloop", CHAN_BODY, CHANF_LOOPING);
			VLCG A 0 A_ReFire("Hold");
			Goto Release;
		Hold:
			VLCG A 0 A_Jumpif(invoker.raging == true, "FireRage");
			TNT1 A 0
				{
					++ GWM_Player(player.mo).VulcanInc;
					if(GWM_Player(player.mo).VulcanInc > 12)
					{
						++ GWM_Player(player.mo).VulcanRage;
						GWM_Player(player.mo).VulcanInc == 0;
					}
				}
			VLCG E 1 {A_FireMVulcan(); A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,5);}
			VLCG F 1 {
				A_FireMVulcan2();
				return ZWL_JumpIfEmpty("Release");
			}
			VLCG G 1 {A_FireMVulcan(); A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,5);}
			VLCG H 1 {
				A_FireMVulcan2();
				return ZWL_JumpIfEmpty("Release");
			}
			VLCG E 0 A_ReFire;
			Goto Release;
		Release:
			VLCG D 1 A_StartSound("weapons/vulcandn", CHAN_BODY);
			VLCG ABCDAABBBCCCCDDDDD 1;
			//VLCG GFFEEDDDCCCBBBBAAA 1;
			TNT1 A 0 A_CheckReload;
			Goto Ready;

		FireRage:
			VLCG EG 1 {
				A_FireRagingVulcan();
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,5);
				return ZWL_JumpIfEmpty("Release");
			}
			VLCG E 0
			{
			 GWM_Player(player.mo).VulcanRage = GWM_Player(player.mo).VulcanRage-1;
			 if (GWM_Player(player.mo).VulcanRage < 1)
				{
				 invoker.raging = false;
				}
			 A_ReFire();
			}
			Goto Ready;

		Spawn:
			VLCG Z -1;
			Stop;
	}
}