// I know. ANOTHER bullet-based weapon. However, this one DID exist before, and there's better sprites now, so I'll add it back.
class GWM_MP40 : GWM_WeaponBase
{
	Default
	{
		Weapon.SelectionOrder 1800;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 32;
		Weapon.AmmoType "GWM_LowCaliberClip";

		ZWeapon.MagazineSize 32;
		ZWeapon.ReloadSound "weapons/smgclipin";
		ZWeapon.ClickSound "weapons/92fsdryfire";

		+WEAPON.WIMPY_WEAPON
		Weapon.UpSound "weapons/draw_secondary";
		AttackSound "weapons/mp40fire";
		Obituary "$KILLMP40";
		Inventory.PickupMessage "$GOTMP40";
		Tag "$TAG_MP40";
	}
	States
	{
		Ready:
			MP4G A 1 ZWL_WeaponReady(); // find a way to make this not have 33 rounds. maybe just reduce the mag size to 31 to compensate for zwl's wacky ass
			Loop;
		Deselect:
			MP4G A 1 A_Lower(18);
			Loop;
		Select:
			MP4G A 1 A_Raise(18);
			Loop;
		Fire:
			MP4G A 2 {
				ZWL_FireHitscan(3, 14, tracerType: "GWM_Tracer");
//				A_FireBullets(7.6, 0, 1, 4, "ZBulletPuff", missile: "GWM_Tracer", spawnheight: 0);
				A_SpawnItemEx("GWM_Flash");
				A_SpawnItemEx("GWM_MuzzleFlashLight",0,0,5);
				A_Overlay(-2, "Flash");
				A_WeaponOffset(0, 4, WOF_ADD);
				ZWL_EjectCasing("GWM_PistolCasing");//, offset: (24, 0, -10));
			}
			MP4G B 1 A_WeaponOffset(0, -1, WOF_ADD);
			MP4G B 1 A_WeaponOffset(0, -3, WOF_ADD);
			MP4G A 1 ZWL_ReFire;
			Goto Ready;
		Flash:
			MP4F A 2 Bright A_Light1;
			MP4F B 2 Bright A_Light2;
			Goto LightDone;
		Reload:
			// todo: add reload animation
			TNT1 A 0 ZWL_Reload(-1);
			Goto Ready;
		Spawn:
			MP4G Z -1;
			Loop;
	}
}