class GWM_GoldWand : GWM_WeaponBase replaces GoldWand
{
	Default
	{
		Weapon.SelectionOrder 1900;
		Weapon.SlotNumber 2;
		Weapon.UpSound "weapons/draw_secondary";
		Inventory.PickupMessage "$GOTWAND";
		Obituary "$KILLWAND";
		Tag "$TAG_WAND";
		AttackSound "weapons/wandhit";
		Weapon.AmmoUse1 1;
		Weapon.AmmoType1 "GWM_WandCrystal";
		Weapon.AmmoUse2 3;
		Weapon.AmmoType2 "GWM_WandCrystal";
		Weapon.AmmoGive 25;
	}
	States
	{
		Spawn:
			WNDW Z -1;
			Stop;
		Ready:
			WNDW A 1 A_WeaponReady;
			Loop;
		Select:
			WNDW A 1 A_Raise(18);
			Loop;
		Deselect:
			WNDW A 1 A_Lower(18);
			Loop;
		Fire:	
			TNT1 A 0 A_JumpifInventory("PowerWeaponlevel2",1,"PowerFire");
			WNDW B 3 ;
			WNDW C 3 
			{
				A_Railattack((15), 0, 1, 0, 0,RGF_SILENT|RGF_NOPIERCING, 0, "GWM_GoldWandPuff", 3, 2, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_Startsound("weapons/wandhit",CHAN_AUTO);
			}
			WNDW D 3;
			WNDW D 0 A_ReFire;
			Goto Ready;
			
		PowerFire:
			WNDW B 5 ;
			WNDW C 5 
			{
				A_FireProjectile("GWM_GoldWeave1",0,false);
				A_FireProjectile("GWM_GoldWeave2",0,false);
				A_Railattack((15), 0, 1, 0, 0,RGF_SILENT, 0, "GWM_GoldWandPuff2", 0, 0, 0, 0, 10, 0, "GWM_GoldWandFX2", -2);
				A_Railattack((10), 0, 1, 0, 0,RGF_SILENT|RGF_NOPIERCING|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", 5, 0, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_Railattack((10), 0, 0, 0, 0,RGF_SILENT|RGF_NOPIERCING|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", -5, 0, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_Startsound("weapons/wandhit",CHAN_AUTO);
			}
			WNDW D 5;
			WNDW D 0 A_ReFire;
			Goto Ready;
			
		AltFire:
			TNT1 A 0 A_JumpifInventory("PowerWeaponlevel2",1,"PowerAltFire");
			WNDW B 5 ;
			WNDW C 4 ;
			
			WNDW C 1 
			{
				A_Railattack((40), 0, 1, 0, 0,RGF_SILENT, 0, "GWM_GoldWandPuff2", 0, 0, 0, 0, 10, 0, "GWM_GoldWandFX2", -2);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_Startsound("weapons/wandhit",CHAN_AUTO);
			}
			
			WNDW DD 3;
			WNDW D 0 A_ReFire;
			Goto Ready;
			
		PowerAltFire:
			WNDW B 5 ;
			WNDW C 4 ;
			
			WNDW C 1 
			{
				A_Railattack((50), 0, 1, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff2", 0, 0, 0, 0, 10, 0, "GWM_GoldWandFX2", -2);
				A_Railattack((0), 0, 1, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff2", 0, 0, 0, 0, 10, 0, "GWM_GoldWandFX2", -2);
				
				A_Railattack((30), 0, 0, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", -6, 0, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_Railattack((30), 0, 0, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", 6, 0, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_Railattack((30), 0, 0, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", 0, -6, 0, 0, 10, 0, "GWM_GoldWandFX", -2);
				A_Railattack((30), 0, 0, 0, 0,RGF_SILENT|RGF_EXPLICITANGLE , 0, "GWM_GoldWandPuff", 0, 6, 0, 0, 10, 0, "GWM_GoldWandFX", -2);

				A_FireProjectile("GWM_GoldWeave1",0,false);
				A_FireProjectile("GWM_GoldWeave2",0,false);
				
				A_FireProjectile("GWM_GoldWeave3",0,false);
				A_FireProjectile("GWM_GoldWeave4",0,false);
				
				
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_SpawnItemEx("GWM_MuzzleFlashLight2",0,0,18);
				A_Startsound("weapons/wandhit",CHAN_AUTO);
			}
			
			WNDW DD 3;
			WNDW D 0 A_ReFire;
			Goto Ready;
			
	}
}
class GWM_GoldWandFX : actor
{
	Default
	{
		+NOINTERACTION
		Renderstyle "add";
	}
	States
	{
		Spawn:
			WZAP ABCDEF 2 bright;
			stop;
	}
}
class GWM_GoldWandFX2 : GWM_GoldWandFX
{
	Default
	{
		Scale 1.5;
	}
	States
	{
		Spawn:
			TNT1 AA 0 NoDelay A_SpawnItemEX("GWM_GoldWandFX",0,0,0,frandom(-1,1),frandom(-2,2),frandom(-2,1)); // this line
			WZAP ABCDEF 2 bright;
			stop;
	}
}
class GWM_GoldWandPuff : actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+PUFFONACTORS
		Renderstyle "add";
		Scale 1.5;
		+ALWAYSPUFF
	}
	States
	{
		Spawn:
			PUF2 ABCDE 4 bright;
			stop;
	}
}
class GWM_GoldWandPuff2 : GWM_GoldWandPuff
{
	Default
	{
		Scale 2.5;
	}
	States
	{
		Spawn:
			TNT1 AAAAAAAAAAAA 0 NoDelay A_SpawnItemEX("GWM_GoldWandFX2",0,0,0,frandom(-3,3),frandom(-3,3),frandom(-3,3));
			PUF2 ABCDE 4 bright;
			stop;
	}
}
Class GWM_GoldWeave1 : Actor
{
	int WeaveDist;
	property WeaveDist: WeaveDist;
	int WeaveSpeed;
	property WeaveSpeed: WeaveSpeed;
	
	Default
	{
		Projectile;
		+FORCEXYBILLBOARD
		DamageType "WaveShooter";
		damagefunction (15);
		radius 18;
		height 18;
		speed 25;
		Decal "BulletChip";
		Renderstyle "Add";
		
		GWM_GoldWeave1.WeaveDist 4;
		GWM_GoldWeave1.WeaveSpeed 3;
	}
	States
	{
		Spawn:
			FX01 CCCCDDDD 1 bright
			{
				A_Weave(WeaveSpeed,0,WeaveDist,0);
				A_Spawnitemex("GWM_GoldWandFX");
			}
			loop;
		Death:
			FX01 EFGH 5;
			stop;
	}
}
Class GWM_GoldWeave2 : GWM_GoldWeave1
{
	States
	{
		Spawn:
			FX01 CCCCDDDD 1 bright
			{
				A_Weave(WeaveSpeed,0,-WeaveDist,0);
				A_Spawnitemex("GWM_GoldWandFX");
			}
			loop;
	}
}
Class GWM_GoldWeave3 : GWM_GoldWeave1
{
	States
	{
		Spawn:
			FX01 CCCCDDDD 1 bright
			{
				A_Weave(0,WeaveSpeed,0,-WeaveDist*0.5);
				A_Spawnitemex("GWM_GoldWandFX");
			}
			loop;
	}
}
Class GWM_GoldWeave4 : GWM_GoldWeave1
{
	States
	{
		Spawn:
			FX01 CCCCDDDD 1 bright
			{
				A_Weave(0,WeaveSpeed,0,WeaveDist*0.5);
				A_Spawnitemex("GWM_GoldWandFX");
			}
			loop;
	}
}