class GWM_GoldWand : GoldWand replaces GoldWand // Okay, this DOES actually need to be inheriting from GoldWand, for the attacks.
{
	Default
	{
		Weapon.SelectionOrder 1900;
		Weapon.UpSound "weapons/draw_secondary";
		Inventory.PickupMessage "$GOTWAND";
		Obituary "$KILLWAND";
		Weapon.SisterWeapon "GWM_GoldWandPowered";
	}
	States
	{
		Spawn:
			WNDW Z -1;
			Stop;
		Ready:
			WNDW A 1 A_WeaponReady;
			Loop;
		Select:
			WNDW A 1 A_Raise(18);
			Loop;
		Deselect:
			WNDW A 1 A_Lower(18);
			Loop;
		Fire:
			WNDW B 3 ;
			WNDW C 5 A_FireGoldWandPL1;
			WNDW D 3;
			WNDW D 0 A_ReFire;
			Goto Ready;
	}
}
class GWM_GoldWandPowered : GoldWandPowered // Okay, this DOES actually need to be inheriting from GoldWandPowered, for the attacks.
{
	Default
	{
		Weapon.UpSound "weapons/draw_secondary";
		Obituary "$KILLWAND_POWERED";
		Weapon.SisterWeapon "GWM_GoldWand";
	}
	States
	{
		Spawn:
			WNDW Z -1;
			Stop;
		Ready:
			WNDW A 1 A_WeaponReady;
			Loop;
		Select:
			WNDW A 1 A_Raise;
			WNDW A 0 A_Raise;
			Loop;
		Deselect:
			WNDW A 1 A_Lower;
			WNDW A 0 A_Lower;
			Loop;
		Fire:
			WNDW B 3;
			WNDW C 4 A_FireGoldWandPL2;
			WNDW D 3;
			WNDW D 0 A_ReFire;
			Goto Ready;
	}
}