class GWM_Pistol : GWM_WeaponBase replaces Pistol
{
	Default
	{
		Weapon.SelectionOrder 1900;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "Clip";
		+WEAPON.WIMPY_WEAPON
		+WEAPON.NOAUTOFIRE
		Inventory.PickupSound "weapons/92fspickup";
		Weapon.UpSound "weapons/draw_secondary";
		Obituary "$KILL92FS";
		Inventory.PickupMessage "$GOT92FS";
		Tag "Beretta 92FS";
	}
	States
	{
		Ready:
			92FG A 1 A_WeaponReady;
			Loop;
		Deselect:
			92FG A 1 A_Lower(12);
			Loop;
		Select:
			92FG A 1 A_Raise(12);
			Loop;
		Fire:
			92FG B 2 {
				A_FireBullets (5.6, 0, 1, 5, "ZBulletPuff", missile: "GWM_Tracer", spawnheight: 0);
				A_StartSound("weapons/92fsfire", CHAN_WEAPON);
				A_SpawnItemEx("GWM_Flash");
				A_GunFlash();
				ZWL_EjectCasing("GWM_PistolCasing");
			}
			92FG CDE 1;
			92FG EEDDCCBBAAA 1 A_WeaponReady;
			TNT1 A 0 A_ReFire;
			Goto Ready;
		Flash:
			92FF A 1 Bright A_Light1;
			92FF B 1 Bright A_Light2;
			Goto LightDone;
		Spawn:
			92FG Z -1;
			Stop;
	}
}