#library "PandorasBox"
#include "zcommon.acs"

script "PandorasBox" (void)
{

	if(CheckInventory("GWM_PANDORAPOINTS") < CheckInventory("GWM_PandoraPointsCap"))
	{
		Print(s:"Not enough souls have been collected. The box remains shut.");
		terminate;
	}
	else
	{
	
    int buttons, oldbuttons;
	int menutime;
	int menusel;
	int rolled;
	
	int wepslot;
	int upgslot;
	int itmslot;
	
	
	SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
	SetActorProperty(0,1,APROP_Invulnerable);
	
	SetHudSize(360,256,0);
	Delay(1);
	
	wepslot = random(0,11);
	upgslot = random(0,3);
	itmslot = random(0,2);
    
	MENUSEL = 1;
			
	while(1)
    {

		SetHudSize(360,256,0);
		SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
		SetActorProperty(0,1,APROP_Invulnerable);
	
		
		buttons = GetPlayerInput(-1,INPUT_BUTTONS);
		oldbuttons = GetPlayerInput(-1,INPUT_OLDBUTTONS);
		
		if(menutime == 0);
		{
			
			menutime = 1;
			
		}
		
		if (menutime == 1)
		{	
			menutime = 1;
			Giveinventory("PowerTimeFreezer2",1);
			SetFont("SUBBAK");
			HudMessage(s:"a";HUDMSG_PLAIN,321001,0,180.0,118.0,0.1);
			
			if (buttons & BT_FORWARD && !(oldbuttons & BT_FORWARD))
			{
				if(menusel!=4) {}
				else
				{
					LocalAmbientSound("menu/cursor",127);
					menusel = 2;
				}
			}

			if (buttons & BT_BACK && !(oldbuttons & BT_BACK))
			{
				if(menusel==4) {}
				else
				{
					LocalAmbientSound("menu/cursor",127);
					menusel = 4;
				}
			}
			

			if (buttons & BT_MOVELEFT && !(oldbuttons & BT_MOVELEFT))
			{
				if (menusel==4||menusel==1) {}
				else
				{
					LocalAmbientSound("menu/cursor",127);
					menusel = menusel-1;
				}
			}

			if (buttons & BT_MOVERIGHT && !(oldbuttons & BT_MOVERIGHT))
			{
				if (menusel==4||menusel==3) {}
				else
				{
					LocalAmbientSound("menu/cursor",127);
					menusel = menusel+1;
				}
			}
			
			if (menusel == 1) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,100.0,100.0,0.06);}
			if (menusel == 2) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,180.0,100.0,0.06);}
			if (menusel == 3) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,260.0,100.0,0.06);}
			if (menusel == 4) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,180.0,215.0,0.06);}
			
			if (wepslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"MP40";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"Kahuna";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"SSG";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 3) { SetFont("SMALLFONT"); HudMessage(s:"ScrapGun";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 4) { SetFont("SMALLFONT"); HudMessage(s:"Magnum";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 5) { SetFont("SMALLFONT"); HudMessage(s:"AcidGun";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 6) { SetFont("SMALLFONT"); HudMessage(s:"Flamer";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 7) { SetFont("SMALLFONT"); HudMessage(s:"IceShot";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 8) { SetFont("SMALLFONT"); HudMessage(s:"Rocket";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 9) { SetFont("SMALLFONT"); HudMessage(s:"Plasma";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 10) { SetFont("SMALLFONT"); HudMessage(s:"Perforator";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			if (wepslot == 11) { SetFont("SMALLFONT"); HudMessage(s:"Stomper";HUDMSG_PLAIN,1,0,100.0,100.0,0.06);}
			
			if (itmslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"SoulSphere";HUDMSG_PLAIN,3,0,260.0,100.0,0.06);}
			if (itmslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"Assault Armor";HUDMSG_PLAIN,3,0,260.0,100.0,0.06);}
			if (itmslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"HellFire Armor";HUDMSG_PLAIN,3,0,260.0,100.0,0.06);}
			
			
			if (menusel == 1) {HudMessage(s:"Pick a Weapon";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
			if (menusel == 2) {HudMessage(s:"Obtain an upgrade";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
			if (menusel == 3) {HudMessage(s:"Obtain an item";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
			if (menusel == 4) {HudMessage(s:"Go to Extra Screen.";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
			
			if (buttons & BT_ATTACK && !(oldbuttons & BT_ATTACK) || buttons & BT_USE && !(oldbuttons & BT_USE))
			{
				Takeinventory("PowerTimeFreezer2",1);
				
				if (menusel == 1)
				{
					if (wepslot == 0) { GiveInventory("GWM_MP40",1);}
					if (wepslot == 1) { GiveInventory("GWM_Shotgun",1);}
					if (wepslot == 2) { GiveInventory("GWM_SuperShotgun",1);}
					if (wepslot == 3) { GiveInventory("GWM_Scrapgun",1);}
					if (wepslot == 4) { GiveInventory("GWM_Revolver",1);}
					if (wepslot == 5) { GiveInventory("GWM_VenomCannon",1);}
					if (wepslot == 6) { GiveInventory("GWM_Flamethrower",1);}
					if (wepslot == 7) { GiveInventory("GWM_IceShotgun",1);}
					if (wepslot == 8) { GiveInventory("GWM_RocketLauncher",1);}
					if (wepslot == 9) { GiveInventory("GWM_PlasmaRifle",1);}
					if (wepslot == 10) { GiveInventory("GWM_Perforator",1);}
					if (wepslot == 11) { GiveInventory("GWM_Stomper",1);}
				}
				
				
				if (menusel == 3)
				{
					if (itmslot == 0) { GiveInventory("SoulSphere",1);}
					if (itmslot == 1) { GiveInventory("GWM_AssaultArmor",1);}
					if (itmslot == 2) { GiveInventory("GWM_HellArmor",1);}
				}
				
				
				Takeinventory("GWM_PandoraPoints",CheckInventory("GWM_PandoraPointsCap"));
				GiveInventory("GWM_PandoraPointsCap",50);
				
				SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
				SetActorProperty(0,0,APROP_Invulnerable);
				
				terminate;
			}

			

		}


        delay(1);
		Giveinventory("PowerTimeFreezer2",1);
    }
	}


}