#library "PandorasBox"
#include "zcommon.acs"

script "PandorasBox" (void)
{

	if(CheckInventory("GWM_PANDORAPOINTS") < CheckInventory("GWM_PandoraPointsCap"))
	{
		Print(s:"Not enough souls have been collected. The box remains shut.");
		terminate;
	}
	else
	{
		
		int buttons, oldbuttons;
		int menutime;
		int menusel;
		int rolled;
		
		int wepslot;
			int weprarity;
		int upgslot;
		int refslot;
		int itmslot;
		
		
		SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
		SetActorProperty(0,1,APROP_Invulnerable);
		
		SetHudSize(360,256,0);
		wepslot = random(-1,25); // G: -1? Why? So you can pull *nothing*...?
		weprarity = random(0,40);
		
		upgslot = random(0,13);
		itmslot = random(0,6);
		refslot = random(0,10);
		
		MENUSEL = 0;
		
		
		//ROLL FOR WEAPONS
		
		if (wepslot == 0) //SMG
		{
		if (CheckInventory("GWM_SMG")) {restart;}
		if (CheckInventory("GWM_MP40")) {restart;}
		if (weprarity < 1) {restart;}
		}
		
		if (wepslot == 1) //MP40
		{
		if (CheckInventory("GWM_SMG")==0) {if (weprarity < 20) {restart;}}
		if (CheckInventory("GWM_MP40")) {restart;}
		if (weprarity < 15) {restart;}
		}
		
		if (wepslot == 2) //Magnum
		{
		if (CheckInventory("GWM_Revolver")) {restart;}
		if (weprarity < 8) {restart;}
		}
		
		if (wepslot == 3) //Shotgun
		{
		if (CheckInventory("GWM_ZombieShotgun")) {restart;}
		if (CheckInventory("GWM_SlayersKahuna")) {restart;}
		if (weprarity < 1) {restart;}
		}
		
		if (wepslot == 4) //Kahuna
		{
		if (CheckInventory("GWM_ZombieShotgun")==0) {if (weprarity < 22) {restart;}}
		if (CheckInventory("GWM_SlayersKahuna")) {restart;}
		if (weprarity < 6) {restart;}
		}
		
		if (wepslot == 5) //Sawed-Off Shotgun
		{
		if (CheckInventory("GWM_SawedOffShotgun")) {restart;}
		if (weprarity < 3) {restart;}
		}
		
		if (wepslot == 6) //Super Shotgun
		{
		if (CheckInventory("GWM_SuperShotgun")) {restart;}
		if (weprarity < 20) {restart;}
		}
		
		if (wepslot == 7) //Scrapgun
		{
		if (CheckInventory("GWM_Scrapgun")) {restart;}
		if (weprarity < 32) {restart;}
		}
		
		if (wepslot == 8) //Minigun
		{
		if (CheckInventory("GWM_Minigun")) {restart;}
		if (CheckInventory("GWM_MadVulcan")) {restart;}
		if (CheckInventory("GWM_Basilisk")) {restart;}
		if (weprarity < 7) {restart;}
		}
		
		if (wepslot == 9) //Mad Vulcan
		{
		if (CheckInventory("GWM_Minigun")==0) {if (weprarity < 25) {restart;}}
		if (CheckInventory("GWM_MadVulcan")) {restart;}
		if (CheckInventory("GWM_Basilisk")) {restart;}
		if (weprarity < 14) {restart;}
		}
		
		if (wepslot == 10) //Assault Rifle
		{
		if (CheckInventory("GWM_AssaultRifle")) {restart;}
		if (CheckInventory("GWM_BurstRifle")) {restart;}
		if (weprarity < 5) {restart;}
		}
		
		if (wepslot == 11) //Burst Rifle
		{
		if (CheckInventory("GWM_AssaultRifle")==0) {if (weprarity < 20) {restart;}}
		if (CheckInventory("GWM_BurstRifle")) {restart;}
		if (weprarity < 10) {restart;}
		}
		
		if (wepslot == 12) //Rocket Launcher
		{
		if (CheckInventory("GWM_RocketLauncher")) {restart;}
		if (weprarity < 6) {restart;}
		}
		
		if (wepslot == 13) //Grenade Launcher
		{
		if (CheckInventory("GWM_GrenadeLauncher")) {restart;}
		if (CheckInventory("GWM_Bouncer")) {restart;}
		if (CheckInventory("GWM_GoldenBouncer")) {restart;}
		if (weprarity < 5) {restart;}
		}
		
		if (wepslot == 14) //Bouncer
		{
		if (CheckInventory("GWM_GrenadeLauncher")==0) {if (weprarity < 33) {restart;}}
		if (CheckInventory("GWM_Bouncer")) {restart;}
		if (CheckInventory("GWM_GoldenBouncer")) {restart;}
		if (weprarity < 26) {restart;}
		}
		
		if (wepslot == 15) //Stomper
		{
		if (CheckInventory("GWM_Stomper")) {restart;}
		if (weprarity < 29) {restart;}
		}
		
		if (wepslot == 16) //Plasma
		{
		if (CheckInventory("GWM_PlasmaRifle")) {restart;}
		if (weprarity < 12) {restart;}
		}
		
		if (wepslot == 17) //Noise
		{
		if (CheckInventory("GWM_NoiseCrusher")) {restart;}
		if (weprarity < 12) {restart;}
		}
		
		if (wepslot == 18) //Acid
		{
		if (CheckInventory("GWM_AcidCannon")) {restart;}
		if (weprarity < 8) {restart;}
		}
		
		if (wepslot == 19) //Ice
		{
		if (CheckInventory("GWM_IceShotgun")) {restart;}
		if (weprarity < 5) {restart;}
		}
		
		if (wepslot == 20) //FlameShot
		{
		if (CheckInventory("GWM_Flamethrower")) {restart;}
		if (weprarity < 9) {restart;}
		}
		
		if (wepslot == 21) //Perforshitter
		{
		if (CheckInventory("GWM_Perforator")) {restart;}
		if (weprarity < 31) {restart;}
		}
		
		if (wepslot == 22) //Wand
		{
		if (CheckInventory("GWM_GoldWand")) {restart;}
		if (weprarity < 20) {restart;}
		}
		
		if (wepslot == 23) //The PEENIX
		{
		if (CheckInventory("GWM_GrenadeLauncher")==0) {restart;}
		if (CheckInventory("GWM_Bouncer")==0) {if (weprarity < 35) {restart;}}
		if (CheckInventory("GWM_GoldenBouncer")) {restart;}
		if (weprarity < 33) {restart;}
		}
		
		if (wepslot == 24) //Spicy gun
		{
		if (CheckInventory("GWM_Minigun")==0) {restart;}
		if (CheckInventory("GWM_MadVulcan")==0) {if (weprarity < 35) {restart;}}
		if (CheckInventory("GWM_Basilisk")) {restart;}
		if (weprarity < 14) {restart;}
		}
		
		if (wepslot == 25) //The WHITE WEDDING
		{
		if (CheckInventory("GWM_ZombieShotgun")==0) {restart;}
		if (CheckInventory("GWM_SlayersKahuna")==0) {if (weprarity < 40) {restart;}}
		if (CheckInventory("GWM_WhiteWedding")) {restart;}
		if (weprarity < 36) {restart;}
		}
		
		if (wepslot == 26) // Railgun
		{
		if (CheckInventory("GWM_Railgun")) {restart;}
		if (weprarity < 12) {restart;}
		}

		while(1)
		{

			SetHudSize(360,256,0);
			//SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
			//SetActorProperty(0,1,APROP_Invulnerable);
		
			
			buttons = GetPlayerInput(-1,INPUT_BUTTONS);
			oldbuttons = GetPlayerInput(-1,INPUT_OLDBUTTONS);
			
			if(menutime == 0);
			{
				
				menutime = 1;
				
			}
			
			if (menutime == 1)
			{	
				menutime = 1;
				Giveinventory("PowerTimeFreezer2",1);
				Giveinventory("PowerMenuInvul",1);
				SetFont("SUBBAK");
//				HudMessage(s:"a";HUDMSG_PLAIN,321001,0,180.0,118.0,0.1);
				
				if (buttons & BT_FORWARD && !(oldbuttons & BT_FORWARD))
				{
					if(menusel==3) 
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 0;
					}
					else
					if(menusel==1) 	{}
					else
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 1;
					}
				}

				if (buttons & BT_BACK && !(oldbuttons & BT_BACK))
				{
					if(menusel==1) 
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 0;
					}
					else
					if(menusel==3) 	{}
					else
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 3;
					}
				}
				

				if (buttons & BT_MOVELEFT && !(oldbuttons & BT_MOVELEFT))
				{
					if(menusel==2) 
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 0;
					}
					else
					if(menusel==4) 	{}
					else
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 4;
					}
				}

				if (buttons & BT_MOVERIGHT && !(oldbuttons & BT_MOVERIGHT))
				{
					if(menusel==4) 
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 0;
					}
					else
					if(menusel==2) 	{}
					else
					{
						LocalAmbientSound("menu/cursor",127);
						menusel = 2;
					}
				}

/*				// this is dumb and causes lag
				//well you're mother!!!!!!!!!!!!
				if (wepslot == 1 && CheckInventory("GWM_MP40")) {restart;}
				if (wepslot == 2 && CheckInventory("GWM_Revolver")) {restart;}
				if (wepslot == 3 && CheckInventory("GWM_SlayersKahuna")) {restart;}
				if (wepslot == 4 && CheckInventory("GWM_SuperShotgun")) {restart;}
				if (wepslot == 5 && CheckInventory("GWM_Scrapgun")) {restart;}
				if (wepslot == 6 && CheckInventory("GWM_MadVulcan")) {restart;}
				if (wepslot == 7 && CheckInventory("GWM_BurstRifle")) {restart;}
				if (wepslot == 8 && CheckInventory("GWM_RocketLauncher")) {restart;}
				if (wepslot == 9 && CheckInventory("GWM_Bouncer")) {restart;}
				if (wepslot == 10 && CheckInventory("GWM_Stomper")) {restart;}
				if (wepslot == 11 && CheckInventory("GWM_PlasmaRifle")) {restart;}
				if (wepslot == 12 && CheckInventory("GWM_NoiseCrusher")) {restart;}
				if (wepslot == 13 && CheckInventory("GWM_AcidCannon")) {restart;}
				if (wepslot == 14 && CheckInventory("GWM_IceShotgun")) {restart;}
				if (wepslot == 15 && CheckInventory("GWM_Flamethrower")) {restart;}
				if (wepslot == 16 && CheckInventory("GWM_Perforator")) {restart;}
				if (wepslot == 17 && CheckInventory("GWM_GoldWand")) {restart;}
*/				
				if (menusel == 0) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,180.0,140.0,0.06);}
				if (menusel == 1) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,180.0,120.0,0.06);}
				if (menusel == 2) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,200.0,140.0,0.06);}
				if (menusel == 3) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,180.0,160.0,0.06);}
				if (menusel == 4) { SetFont("SMALLFONT"); HudMessage(s:"X";HUDMSG_PLAIN,88,0,160.0,140.0,0.06);}
				
				
				
				if (menusel == 0) {HudMessage(s:"Let fate decide";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
				if (menusel == 1) {HudMessage(s:"Obtain an upgrade";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
				if (menusel == 2) {HudMessage(s:"Gain an item.";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
				if (menusel == 3) {HudMessage(s:"Refill a supply.";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
				if (menusel == 4) {HudMessage(s:"Obtain a weapon.";HUDMSG_PLAIN,13,CR_WHITE,180.0,248.0,0.1);}
				
				//SLOT 1 (UPGRADE)
				if (upgslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"+Health";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"+Speed";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"+Defense";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 3) { SetFont("SMALLFONT"); HudMessage(s:"+Bullets";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 4) { SetFont("SMALLFONT"); HudMessage(s:"+Shells";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 5) { SetFont("SMALLFONT"); HudMessage(s:"+Full Metal Jackets";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 6) { SetFont("SMALLFONT"); HudMessage(s:"+Rockets";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 7) { SetFont("SMALLFONT"); HudMessage(s:"+Cells";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 8) { SetFont("SMALLFONT"); HudMessage(s:"+Ice Shells";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 9) { SetFont("SMALLFONT"); HudMessage(s:"+Acid";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 10) { SetFont("SMALLFONT"); HudMessage(s:"+Flame";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 11) { SetFont("SMALLFONT"); HudMessage(s:"+Scrap";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 12) { SetFont("SMALLFONT"); HudMessage(s:"+Stomper";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 13) { SetFont("SMALLFONT"); HudMessage(s:"+Wand Crystals";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				if (upgslot == 14) { SetFont("SMALLFONT"); HudMessage(s:"+Healing Speed";HUDMSG_PLAIN,4,0,180.0,100.0,0.06);}
				
				
				
				//SLOT 2 (ITEMS)
				if (itmslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"SoulSphere";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"Assault Armor";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"HellFire Armor";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 3) { SetFont("SMALLFONT"); HudMessage(s:"Bomb Suit";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 4) { SetFont("SMALLFONT"); HudMessage(s:"Blursphere";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 5) { SetFont("SMALLFONT"); HudMessage(s:"Drainsphere";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				if (itmslot == 6) { SetFont("SMALLFONT"); HudMessage(s:"Stopwatch";HUDMSG_PLAIN,3,0,280.0,140.0,0.06);}
				
				//SLOT 3 (REFILL)
				if (refslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"Health";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"Armor";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"Hollow Points";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 3) { SetFont("SMALLFONT"); HudMessage(s:"Shells";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 4) { SetFont("SMALLFONT"); HudMessage(s:"Full Metal Jackets";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 5) { SetFont("SMALLFONT"); HudMessage(s:"Rockets";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 6) { SetFont("SMALLFONT"); HudMessage(s:"Cells";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 7) { SetFont("SMALLFONT"); HudMessage(s:"Elements";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 8) { SetFont("SMALLFONT"); HudMessage(s:"Scrap";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 9) { SetFont("SMALLFONT"); HudMessage(s:"Stomper";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				if (refslot == 10) { SetFont("SMALLFONT"); HudMessage(s:"Wand Crystals";HUDMSG_PLAIN,2,0,180.0,180.0,0.06);}
				
				//SLOT 4 (WEAPON)
				if (wepslot == 0) { SetFont("SMALLFONT"); HudMessage(s:"SMG";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 1) { SetFont("SMALLFONT"); HudMessage(s:"MP40";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 2) { SetFont("SMALLFONT"); HudMessage(s:"Magnum";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 3) { SetFont("SMALLFONT"); HudMessage(s:"Zombie Shotgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 4) { SetFont("SMALLFONT"); HudMessage(s:"Slayer's Kahuna";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 5) { SetFont("SMALLFONT"); HudMessage(s:"Sawed-Off Shotgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 6) { SetFont("SMALLFONT"); HudMessage(s:"Super Shotgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 7) { SetFont("SMALLFONT"); HudMessage(s:"Scrapgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 8) { SetFont("SMALLFONT"); HudMessage(s:"Minigun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 9) { SetFont("SMALLFONT"); HudMessage(s:"Mad Vulcan";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 10) { SetFont("SMALLFONT"); HudMessage(s:"Assault Rifle";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 11) { SetFont("SMALLFONT"); HudMessage(s:"Burst Rifle";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 12) { SetFont("SMALLFONT"); HudMessage(s:"Rocket Launcher";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 13) { SetFont("SMALLFONT"); HudMessage(s:"Grenade Launcher";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 14) { SetFont("SMALLFONT"); HudMessage(s:"Bouncer";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 15) { SetFont("SMALLFONT"); HudMessage(s:"Stomper";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 16) { SetFont("SMALLFONT"); HudMessage(s:"Plasma Rifle";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 17) { SetFont("SMALLFONT"); HudMessage(s:"Noise Crusher";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 18) { SetFont("SMALLFONT"); HudMessage(s:"Acid Cannon";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 19) { SetFont("SMALLFONT"); HudMessage(s:"Ice Shotgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 20) { SetFont("SMALLFONT"); HudMessage(s:"Flame Shot";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 21) { SetFont("SMALLFONT"); HudMessage(s:"Perforator";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 22) { SetFont("SMALLFONT"); HudMessage(s:"Gold Wand";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 23) { SetFont("SMALLFONT"); HudMessage(s:"Phoenix";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 24) { SetFont("SMALLFONT"); HudMessage(s:"Basilisk";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 25) { SetFont("SMALLFONT"); HudMessage(s:"White Wedding";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				if (wepslot == 26) { SetFont("SMALLFONT"); HudMessage(s:"Railgun";HUDMSG_PLAIN,1,0,80.0,140.0,0.06);}
				
				if (buttons & BT_ATTACK && !(oldbuttons & BT_ATTACK) || buttons & BT_USE && !(oldbuttons & BT_USE))
				{
					LocalAmbientSound("menu/choose",127);
					Takeinventory("PowerTimeFreezer2",1);
					if (menusel == 0) //Random
					{
					ACS_NamedExecute("RandomBoxPicker",0,0,0,0);
					}
					
					if (menusel == 1) //UPGRADE
					{
						if (upgslot == 0) { GiveInventory("GWM_HPupgrade", 50);}
						if (upgslot == 1) { GiveInventory("GWM_Speedupgrades", 1);}
						//if (upgslot == 2) { GiveInventory("GWM_Defenseupgrades", 1);}
						if (upgslot == 3) { SetAmmoCapacity("GWM_HollowPointMagazine",GetAmmoCapacity("GWM_HollowPointMagazine")+150);}
						if (upgslot == 4) { SetAmmoCapacity("GWM_Shell",GetAmmoCapacity("GWM_Shell")+25);}
						if (upgslot == 5) { SetAmmoCapacity("GWM_FMJMagazine",GetAmmoCapacity("GWM_FMJMagazine")+100);}
						if (upgslot == 6) { SetAmmoCapacity("GWM_RocketAmmo",GetAmmoCapacity("GWM_RocketAmmo")+20);}
						if (upgslot == 7) { SetAmmoCapacity("GWM_Cell",GetAmmoCapacity("GWM_Cell")+175);}
						if (upgslot == 8) { SetAmmoCapacity("GWM_IceShell",GetAmmoCapacity("GWM_IceShell")+20);}
						if (upgslot == 9) { SetAmmoCapacity("GWM_AcidVial",GetAmmoCapacity("GWM_AcidVial")+10);}
						if (upgslot == 10) { SetAmmoCapacity("GWM_GasCanister",GetAmmoCapacity("GWM_GasCanister")+10);}
						if (upgslot == 11) { SetAmmoCapacity("GWM_ScrapDrum",GetAmmoCapacity("GWM_ScrapDrum")+10);}
						if (upgslot == 12) { SetAmmoCapacity("GWM_StomperAmmo",GetAmmoCapacity("GWM_StomperAmmo")+10);}
						if (upgslot == 13) { SetAmmoCapacity("GWM_WandCrystal",GetAmmoCapacity("GWM_WandCrystal")+10);}
						if (upgslot == 14) { GiveInventory("GWM_Healspeed", 1);}
						
					}
					if (menusel == 2) //ITEM
					{
						if (itmslot == 0) {GiveInventory("GWM_Soulsphere",100);} // difference between this and the HealThing below is that this can overheal
						if (itmslot == 1) {GiveInventory("GWM_AssaultArmor",1);}
						if (itmslot == 2) {GiveInventory("GWM_HellArmor",1);}
						if (itmslot == 3) {GiveInventory("GWM_Bombsuit",1);}
						if (itmslot == 4) {GiveInventory("GWM_Blursphere",1);}
						if (itmslot == 5) {GiveInventory("GWM_Drainsphere",1);}
						if (itmslot == 6) {GiveInventory("GWM_Stopwatch",1);}
					}
					if (menusel == 3) //REFILL
					{
						if (refslot == 0) {HealThing(1000);}
						if (refslot == 1) {GiveInventory("GWM_CombatArmor",1);}
						if (refslot == 2) {GiveInventory("GWM_HollowPointMagazine",1000);}
						if (refslot == 3) {GiveInventory("GWM_Shell",1000);}
						if (refslot == 4) {GiveInventory("GWM_FMJMagazine",1000);}
						if (refslot == 5) {GiveInventory("GWM_RocketAmmo",1000);}
						if (refslot == 6) {GiveInventory("GWM_Cell",1000);}
						if (refslot == 7) {
							GiveInventory("GWM_IceShell",1000);
							GiveInventory("GWM_AcidVial",1000);
							GiveInventory("GWM_GasCanister",1000);
						}
						if (refslot == 8) {GiveInventory("GWM_ScrapDrum",1000);}
						if (refslot == 9) {GiveInventory("GWM_StomperAmmo",1000);}
						if (refslot == 10) {GiveInventory("GWM_WandCrystal",1000);}
					}
					if (menusel == 4) //WEAPON
					{
						if (wepslot == 0) { GiveInventory("GWM_SMG",1);}
						if (wepslot == 1) { GiveInventory("GWM_MP40",1);}
						if (wepslot == 2) { GiveInventory("GWM_Revolver",1);}
						if (wepslot == 3) { GiveInventory("GWM_ZombieShotgun",1);}
						if (wepslot == 4) { GiveInventory("GWM_SlayersKahuna",1);}
						if (wepslot == 5) { GiveInventory("GWM_SawedOffShotgun",1);}
						if (wepslot == 6) { GiveInventory("GWM_SuperShotgun",1);}
						if (wepslot == 7) { GiveInventory("GWM_Scrapgun",1);}
						if (wepslot == 8) { GiveInventory("GWM_Minigun",1);}
						if (wepslot == 9) { GiveInventory("GWM_MadVulcan",1);}
						if (wepslot == 10) { GiveInventory("GWM_AssaultRifle",1);}
						if (wepslot == 11) { GiveInventory("GWM_BurstRifle",1);}
						if (wepslot == 12) { GiveInventory("GWM_RocketLauncher",1);}
						if (wepslot == 13) { GiveInventory("GWM_GrenadeLauncher",1);}
						if (wepslot == 14) { GiveInventory("GWM_Bouncer",1);}
						if (wepslot == 15) { GiveInventory("GWM_Stomper",1);}
						if (wepslot == 16) { GiveInventory("GWM_PlasmaRifle",1);}
						if (wepslot == 17) { GiveInventory("GWM_NoiseCrusher",1);}
						if (wepslot == 18) { GiveInventory("GWM_AcidCannon",1);}
						if (wepslot == 19) { GiveInventory("GWM_IceShotgun",1);}
						if (wepslot == 20) { GiveInventory("GWM_Flamethrower",1);}
						if (wepslot == 21) { GiveInventory("GWM_Perforator",1);}
						if (wepslot == 22) { GiveInventory("GWM_GoldWand",1);}
						if (wepslot == 23) { GiveInventory("GWM_GoldenBouncer",1);}
						if (wepslot == 24) { GiveInventory("GWM_Basilisk",1);}
						if (wepslot == 25) { GiveInventory("GWM_WhiteWedding",1);}
						if (wepslot == 26) { GiveInventory("GWM_Railgun",1);}
						
					}
					
					Takeinventory("GWM_PandoraPoints",CheckInventory("GWM_PandoraPointsCap"));
					
					if (menusel == 0)
					{GiveInventory("GWM_PandoraPointsCap",20);}
					if (menusel == 1)
					{GiveInventory("GWM_PandoraPointsCap",45);}
					if (menusel == 2)
					{GiveInventory("GWM_PandoraPointsCap",40);}
					if (menusel == 3)
					{GiveInventory("GWM_PandoraPointsCap",35);}
					if (menusel == 4)
					{GiveInventory("GWM_PandoraPointsCap",50);}
					
					
					SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
					
					terminate;
				}
			}

			delay(1);
			Giveinventory("PowerTimeFreezer2",1);
		}
	}
}