#library "WepSwitch"
#include "zcommon.acs"

script "GWM_FireWepSwitch" (void) 
{
	if (Checkinventory("GWM_Volcannon")==1&&CheckWeapon("GWM_Volcannon")==0)
			{
				SetWeapon("GWM_Volcannon");
			}
}

script "GWM_IceWepSwitch" (void) 
{
	if (Checkinventory("GWM_PFMissileLauncher")==1 && CheckWeapon("GWM_PFMissileLauncher")==0)
			{
				SetWeapon("GWM_PFMissileLauncher");
			}
	if (Checkinventory("GWM_IceShotgun")==1 && CheckWeapon("GWM_IceShotgun")==0)
			{
				SetWeapon("GWM_IceShotgun");
			}
}

script "GWM_AcidWepSwitch" (void) 
{
	if (Checkinventory("GWM_AcidCannon")==1&&CheckWeapon("GWM_AcidCannon")==0)
			{
				SetWeapon("GWM_AcidCannon");
			}
}

