class PrimaryCharge : Inventory
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}

class GWM_Flash : Actor
{
	Default
	{
		+NOGRAVITY
	}
	States
	{
		Spawn:
			TNT1 AAAAAA 1 {
				A_Warp(AAPTR_TARGET, 0, 0, 32, 0, WARPF_COPYINTERPOLATION);
			}
			Stop;
	}
}
class GWM_IceFlash : GWM_Flash {}
class GWM_PlasmaFlash : GWM_Flash {}

class GWM_IceDamageEffect : Actor
{
	Default
	{
		+THRUACTORS;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 {
				if ((target != null && target.Health >= 0) && (!target.player))
				{
					target.Speed = target.Speed / 2;
				}
			}
			TNT1 A 45;
			stop;
	}
}

class GWM_FlameDamageEffect : Actor
{
	Default
	{
		+NoInteraction;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jumpifinventory("PrimaryCharge",20,"Death");
			FCFX AAA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX BBB 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CCC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX DDD 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			TNT1 A 0 A_Giveinventory("PrimaryCharge",1);
			Loop;
		Death:
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			Stop;
	}
}

class GWM_PoisonDamageEffect : Actor
{
	Default
	{
		+NoInteraction;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jumpifinventory("PrimaryCharge",20,"Death");
			FCFX AAA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX BBB 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CCC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX DDD 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			TNT1 A 0 A_Giveinventory("PrimaryCharge",1);
			Loop;
		Death:
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XBX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CXC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX XDX 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			Stop;
	}
}