class PrimaryCharge : Inventory
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}

class GWM_Flash : Actor
{
	Default
	{
		+NOGRAVITY
	}
	States
	{
		Spawn:
			TNT1 AAAAAA 1 {
				A_Warp(AAPTR_TARGET, 0, 0, 32, 0, WARPF_COPYINTERPOLATION);
			}
			Stop;
	}
}
class GWM_IceFlash : GWM_Flash {}
class GWM_PlasmaFlash : GWM_Flash {}

class GWM_IceDamageEffect : Actor
{
	Default
	{
		+THRUACTORS;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 {
				if ((target != null && target.Health >= 0) && (!target.player))
				{
					target.Speed = target.Speed / 2;
				}
			}
			TNT1 A 45;
			stop;
	}
}

class GWM_FlameDamageEffect : Actor
{
	Default
	{
		+NoInteraction;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jumpifinventory("PrimaryCharge",10,"Death");
			FCFX AAA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX BBB 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX CCC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			FCFX DDD 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			TNT1 A 0 A_Giveinventory("PrimaryCharge",1);
			Loop;
		Death:
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Fire");
			Stop;
	}
}

class GWM_PoisonDamageEffect : Actor
{
	Default
	{
		+NoInteraction;
		Scale 1.75;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jumpifinventory("PrimaryCharge",10,"Death");
			FCFX AAA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX BBB 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX CCC 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			FCFX DDD 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			TNT1 A 0 A_Giveinventory("PrimaryCharge",1);
			Loop;
		Death:
			FCFX AXA 1 Bright A_Warp(AAPTR_TARGET,0,0,15);
			TNT1 A 0 A_Damagetarget(1,"Poison");
			Stop;
	}
}

Class IceFog : Actor
{
	Default
	{
		Radius 1;
		Height 1;
		RenderStyle "Add";
		Alpha 0.2;
		XScale 0.4;
		YScale 0.2;
		+NoGravity
		+NoClip
	}

	States
	{
	Spawn:
		IFOG A 4 A_FadeOut(0.1);
		Loop;
	}
}
Class IceFog2 : Actor
{
	Default
	{
		Radius 1;
		Height 1;
		RenderStyle "Add";
		Alpha 0.2;
		XScale 0.6;
		YScale 0.4;
		+NoGravity
		+NoClip
	}

	States
	{
	Spawn:
		IFOG A 4 A_FadeOut(0.03);
		Loop;
	}
}