class IceCubeGrenadeLauncher : DoomWeapon // since GrenadeLauncher just isn't defined in (G)ZDoom, and only in Skulltag
{
	Default
	{
		Radius 20;
		Height 16;
		Weapon.SelectionOrder 2500;
		+WEAPON.NOAUTOFIRE
		+WEAPON.NOAUTOAIM
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "RocketAmmo";
		Inventory.PickupMessage "You got the Ice Cube Grenade Launcher!";
		// i think there was something else here, but i forgor :skull:
	}
	States
	{
		Spawn:
			ICGL Z -1;
			Stop;
		Ready:
			ICGL A 1 A_WeaponReady;
			Loop;
		Deselect:
			ICGL A 1 A_Lower;
			Loop;
		Select:
			ICGL A 1 A_Raise;
			Loop;
		Fire:
			ICGL A 1 {
				A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
//				A_StartSound("weapons/iceglfire", CHAN_WEAPON); // will probably be from tf2 or something
				A_FireProjectile("IceCubeGrenade", 0, true, 0, 0, 0, -6.328125); // what is that number.
				A_Overlay(-2, "Flash");
				A_SpawnItemEx("IceSGFlash"); // oh boy it's not a shotgun but it sure does use this
				A_WeaponOffset(0, 17, WOF_ADD);
				A_OverlayScale(OverlayID(), 1.15, 0, WOF_INTERPOLATE);
				A_OverlayScale(-2, 1.15, 0, WOF_INTERPOLATE);
			}
			ICGL A 2;
			ICGL AA 2 {
				A_WeaponOffset(0, -8.5, WOF_ADD);
				A_OverlayScale(OverlayID(), -0.075, 0, WOF_ADD);
			}
			ICGL A 4;
			ICGL B 6;
			ICGL C 6 A_CheckReload;
			ICGL D 4 A_StartSound("weapons/sshoto", CHAN_WEAPON);
			ICGL E 8;
		// skipping this part for now
			ICGL F 4;
			ICGL G 3 A_StartSound("weapons/sshotc", CHAN_WEAPON);
			ICGL A 6 A_ReFire;
			Goto Ready;
		Flash:
			TNT1 A 0 A_OverlayOffset(OverlayID(), 158, 96);
			SGFL ABCCDE 1 Bright A_OverlayPivotAlign(OverlayID(), PSPA_CENTER, PSPA_BOTTOM);
			Stop;
	}
}